CU-CommunityApps/cu-kfs

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java
src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentFileServiceImpl.java
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml

This is an updated version of today's earlier KFSPTS-4771 pull request, which now implements Bryan's suggestions and contains only the files that were actually updated.

KFSPTS-4771: Added ability to send warning emails when XML-loaded PDP payments reference inactive vendors.

---

src/main/java/edu/cornell/kfs/fp/document/service/impl/YearEndGeneralLedgerPendingEntriesServiceImpl.java
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml

This commit changes the YEJV document so that, when necessary, it can create "C & G Balance Forward" GL pending entries (which will have a "CB" fiscal period). It is mostly code and logic copied from BalanceServiceImpl, BalanceDaoOjb and BalanceForwardRuleHelper that has been adapted for creating GL pending entries instead of origin entries.
As noted on the in-code comments, there is one "if" block that is meant to replicate existing selection behavior in KFS, even though the existing behavior could contain a bug. (The functionals requested that the selection logic remain the same for now.) I will be creating a separate JIRA ticket to look into that problem further, and if changes do indeed need to be made as a result of that, then they will be made for a different story JIRA.

KFSPTS-4528: Updated the YEJV document to allow for generating CB-period GL pending entries.

---

src/main/java/edu/cornell/kfs/pdp/CUPdpPropertyConstants.java
src/main/java/edu/cornell/kfs/pdp/businessobject/CuACHPayee.java
src/main/java/edu/cornell/kfs/pdp/businessobject/lookup/CuACHPayeeLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/pdp/businessobject/lookup/CuPayeeACHAccountLookupableHelperServiceImpl.java
src/main/java/org/kuali/kfs/pdp/businessobject/PayeeACHAccount.java
src/main/resources/edu/cornell/kfs/cu-spring-kfs.xml
src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/ACHPayee.xml
src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PayeeACHAccount.xml
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
src/main/resources/edu/cornell/kfs/pdp/document/datadictionary/CuPayeeACHAccountMaintenanceDocument.xml

Functional users discovered some issues with the changes from the original KFSPTS-5169 pull request (#20), so those changes have been reverted and this new pull request has been created to implement the correct functionality.
This should be almost the same as the #20 pull request, except that the new lookupable helper service now extends from a different class. This was necessary to prevent usage of potentially-buggy code in the base KFS lookupable helper for Payee ACH Accounts.

KFSPTS-5169: Added principal name to Payee ACH Account document, lookup and inquiry, as well as ACH Payee lookup.

---

src/main/resources/edu/cornell/kfs/fp/document/datadictionary/YearEndTransferOfFundsDocument.xml
src/main/resources/edu/cornell/kfs/fp/document/validation/configuration/CuYearEndTransferOfFundsValidation.xml

This was originally a story sub-task but later moved to its own story, hence the odd branch name.

KFSPTS-5236: Replaced org review with account review on YETF documents, and removed its org-assigned validation.

---

src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardFlatInputFileType.java
src/main/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/fp/businessobject/ProcurementCardTransactionDetailExtendedAttribute.java
src/main/java/edu/cornell/kfs/fp/businessobject/ProcurementCardTransactionExtendedAttribute.java
src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataBase.java
src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataDetail.java
src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataRecord.java
src/main/java/edu/cornell/kfs/fp/businessobject/USBankAddendumRecord.java
src/main/java/edu/cornell/kfs/fp/businessobject/USBankRecordFieldUtils.java
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionDetail.xml
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionDetailExtendedAttribute.xml
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionExtendedAttribute.xml
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/PurchasingDataDetail.xml
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/PurchasingDataRecord.xml
src/main/resources/edu/cornell/kfs/fp/cu-ojb-fp.xml

Implements processing and viewing for the Type 50 record for our US Bank PCard files. More information (including an example upload file) can be found in KFSPTS-4030 (which was the only JIRA for Level3 PCard data originally).
Level3 information is already included in the upload files, this simply adds the ability to read, store, and display it. We're also only dealing with the Type 50 data in this JIRA. After processing a pcard flat file, find a PCDO doc and click on the Transaction Reference Number on its inquiry page. This will show the Procurement Card Transaction Detail Inquiry, which should have the Type 50 (Purchasing Data) information below it.
See the JIRA for the associated SQL file.
If you wish to test this out without tampering with what's in devlocal right now, I can explain …

[KFSPTS-4808] Level3 PCard Type 50 record implementation

---

src/main/java/edu/cornell/kfs/gl/batch/service/impl/CuPosterServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/resources/CU-ApplicationResources.properties

This is a different version of Kyle's feature for having ICR accounts use the continuation accounts instead when closed at Poster job time. Kyle's original implementation performed this processing at Poster batch step 4 (ICR Generation); this implementation does so at Poster batch step 6 (ICR Entries) instead, to minimize the amount of custom coding needed and to allow for outputting continuation-related errors to the "gl_icrerrs" output file.

KFSPTS-4390: Modified ICR poster continuation account fix to be applied at a later poster step that allows for error file output.

---

src/main/resources/edu/cornell/kfs/module/receiptProcessing/cu-spring-receiptProcessing.xml

This change simply allows for one of the Receipt Processing base directory paths to be configurable via a property.

KFSPTS-5214: Added ability to configure Receipt Processing output directory via a config property.

---

src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/org/kuali/kfs/gl/batch/service/impl/CuScrubberProcessImpl.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/gl/cu-spring-gl.xml

This change allows for closed Cost Sharing accounts to post to their continuation accounts when the Scrubber runs. This is similar to the recent feature for allowing ICR accounts to post to continuation accounts, except that this feature is in the Scrubber instead of the Poster (due to Cost Sharing being processed at the Scrubber phase).
Note that, due to limitations of the KFS-delivered ScrubberProcessImpl, the new CU-specific subclass needs to be in the same package as the superclass in order to access a required internal class.

KFSPTS-4905: Updated Scrubber so that closed Cost Sharing accounts will post to their continuation accounts.

---

src/main/resources/edu/cornell/kfs/module/receiptProcessing/cu-spring-receiptProcessing.xml

This updates the Receipt Processing Service to use a different input/output file directory path. The new path is relative to the KFS staging directory.
The original version of this enhancement was going to use a property to control the whole path. However, after further discussion, it was decided to use this other path instead, and the old enhancement version has been reverted.

KFSPTS-5214: Changed the Receipt Processing directory path to one that is relative to the KFS staging directory.

---

src/main/java/edu/cornell/kfs/gl/batch/service/impl/CuPostExpenditureTransaction.java
src/main/resources/edu/cornell/kfs/gl/cu-spring-gl.xml
src/test/java/edu/cornell/kfs/gl/batch/service/impl/CuPostExpenditureTransactionTest.java

This is a cu customization of PostExpenditureTransaction.hasExclusionByAccount where we only want active rules, the KualiCo code doesn't consider the active/inactive flag.  I also created a new unit test for this functionality.  It requires the spring context as it needs to query the database.

KFSPTS-5322 excluding inactive ICR records from GL Poster Job

---

src/main/java/edu/cornell/kfs/krad/businessobject/NoteExtendedAttribute.java
src/main/java/edu/cornell/kfs/module/purap/document/CuRequisitionDocument.java
src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuPurchaseOrderServiceImpl.java
src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/module/purap/document/web/struts/CuRequisitionAction.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/resources/edu/cornell/kfs/cu-spring-rice-krad-overrides.xml
src/main/resources/edu/cornell/kfs/krad/businessobject/datadictionary/NoteExtendedAttribute.xml
src/main/resources/edu/cornell/kfs/krad/cu-ojb-krad.xml
src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/RequisitionDocument.xml
src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/Note.xml
src/main/webapp/WEB-INF/tags/module/purap/notes-sciquest.tag
src/main/webapp/scripts/module/purap/reqsNotes.js

This feature allows users to specify whether REQS notes without attachments should copy over to the PO, by means of a new extended attribute for KRAD Note objects. (REQS notes with attachments will always copy to the PO if they were created before routing termination, and the UI will prevent editing of that flag on such lines, including addLines that specify an attachment.) Daniela originally started the development of the feature, and I finished up the remainder.
Some new SQL is required for this change, and is attached to the story JIRA. In addition, a new KRAD override file has been added, which will require updating a KFS config property for KRAD overrides. This change has already been made for the config file used by the PR-triggered unit tests.
There were some places where OJB's …

KFSPTS-4490: Added checkbox on REQS notes to indicate whether they should be copied to the PO.

---

src/main/resources/com/rsmart/kuali/kfs/fp/spring-fp.xml
src/main/webapp/static/xsd/fp/disbursementVoucher.xsd

Batch job for this feature already exists but it is not yet set up to run through Tidal. The service used by the batch job is currently used by a manual DV batch upload link in KFS.
The only code changes were:
- create a separate folder for attachment files: /staging/fp/disbursementVoucher/attachment. This is to keep the files clean: data files and attachments separate, and also to keep this consistent with other similar KFS batch jobs.
- remove reference to rsmartTypes.xsd as it was not used, file did not even exist in our project and it was confusing for our customers

KFSPTS-4278 Change attachments folder; remove rsmartTypes.xsd reference

---

src/main/java/edu/cornell/kfs/gl/CuGeneralLedgerConstants.java
src/main/java/org/kuali/kfs/gl/batch/service/impl/CuScrubberProcessImpl.java

Users need to be able to limit generation of plant indebtedness entries based on document type, similar to how an existing parameter is used for limiting capitalization entry generation. This feature adds a new parameter to control the inclusion/exclusion of doc types for plant indebtedness processing by the Scrubber. It is very similar to the related parameter for capitalization entry generation.
This has been implemented to limit the amount of code needing overrides, while also following similar logic from the Scrubber's capitalization entry doc-type-based handling.

KFSPTS-5483: Added new parameter to control the Scrubber's generation of plant indebtedness entries based on document type.

---

src/main/java/edu/cornell/kfs/module/purap/document/service/CuPaymentRequestService.java
src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuPaymentRequestServiceImpl.java
src/test/java/edu/cornell/kfs/module/purap/document/service/impl/CuPaymentRequestServiceImplTest.java
src/test/java/edu/cornell/kfs/module/purap/fixture/PurchaseOrderFixture.java
src/test/java/edu/cornell/kfs/module/purap/fixture/RequisitionFixture.java
src/test/java/edu/cornell/kfs/module/purap/fixture/RequisitionItemFixture.java

This is a newer version of the code from PR #91, which has removed the prompt to the FO/delegate users and now has some unit tests to go along with it.
I spread out the logic of the new PREQ service functionality to several methods to simplify testing the new logic via unit tests. And in the unit test itself, I added a forced update to a particular dependent parameter to ensure that its value would work with the item amounts from the associated fixtures. I think the change will get rolled back after the test runs; if you think that is not the case or if you have suggestions on improving that test, please let me know. (Due to it being in a Spring-dependent test, a mock service may not be suitable.)

KFSPTS-5643: Require positive approval for PREQs whose POs' amounts equal or exceed a given limit, if the PO has quantity-type items.

---

src/main/java/edu/cornell/kfs/fp/businessobject/CuDisbursementVoucherPayeeDetail.java
src/main/java/edu/cornell/kfs/fp/businessobject/CuDisbursementVoucherPayeeDetailExtension.java
src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocument.java
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/DisbursementVoucherPayeeDetail.xml
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/DisbursementVoucherPayeeDetailExtension.xml
src/main/resources/edu/cornell/kfs/fp/cu-ojb-fp.xml
src/test/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocumentTest.java

This adds a new Payee Type Suffix property to the Payee Detail Extension object so that when a vendor payee is selected, its vendor type will be displayed to the right of the regular Payee Type value. The suffix is expected to be auto-refreshable prior to routing or ad hoc completion, but after that it is expected to remain static even if the vendor's type is changed later. This allows for directly displaying the vendor's type on the DV, and for showing what that value was as of the time that it started routing.
I also updated one of the existing microtest classes to add some microtests for this. I did have to modify some existing parts and tests slightly because it previously had incorrect usage of vendor ID values.

KFSPTS-5486: Add Vendor Type name to the Payee Type name on DVs.

---

src/main/java/edu/cornell/kfs/module/cg/businessobject/AwardExtendedAttribute.java
src/main/java/edu/cornell/kfs/module/cg/document/validation/impl/AwardExtensionRule.java
src/main/java/edu/cornell/kfs/module/ezra/businessobject/EzraProposalAward.java
src/main/java/edu/cornell/kfs/module/ezra/service/impl/EzraServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/Award.xml
src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/AwardExtendedAttribute.xml
src/main/resources/edu/cornell/kfs/module/cg/cu-ojb-cg.xml
src/main/resources/edu/cornell/kfs/module/cg/document/datadictionary/AwardMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/module/ezra/cu-ojb-ezra.xml
src/test/java/edu/cornell/kfs/module/ezra/service/ezraUpdateAwardImplTest.java

This feature adds Budget Start, Budget Stop, and Budget Total fields to our Award extension objects, which can be populated via the corresponding fields from our EZRA integration tables and can also be edited via the Award maintenance document. Our EZRA-related OJB mappings in KFS have been updated to add the missing field references, but no SQL is required on the EZRA end because those fields already exist in the relevant table; we only need SQL for adding the fields to the AwardExtendedAttribute table.
The only extra business rule needed at this time is to make sure the Budget End is after the Budget Start. The new fields are not configured as required ones, to avoid potentially breaking older Award maintenance docs or objects.

KFSPTS-5484: Added Budget Start/Stop/Total fields from our EZRA integration to the Award extended attribute.

---

src/main/java/edu/cornell/kfs/tax/CUTaxConstants.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1099Processor.java
src/main/java/edu/cornell/kfs/tax/service/DocumentType1099BoxService.java
src/main/java/edu/cornell/kfs/tax/service/impl/DocumentType1099BoxServiceImpl.java
src/main/resources/edu/cornell/kfs/tax/cu-spring-tax.xml
src/test/java/edu/cornell/kfs/tax/service/impl/DocumentType1099BoxServiceImplTest.java

This updates the 1099 tax file generation process so that specific document types will be explicitly mapped to a given 1099 tax box. (A new parameter controls these mappings.) This takes precedence over (and has been implemented in a similar manner as) the new payment-reason-based 1099 box mappings from KFSPTS-5409.

KFSPTS-5411: Updated 1099 processing to allow for specifying mappings between doc types and 1099 boxes.

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/document/web/struts/CuFinancialMaintenanceDocumentAction.java
src/main/webapp/kr/WEB-INF/cu-struts-config.xml
src/test/java/edu/cornell/kfs/sys/document/web/struts/CuFinancialMaintenanceDocumentActionTest.java

This adds an altered version of the Rice 2.5.x BO note add/delete fix, which has been specifically modified to only apply to Account maintenance documents for the present time. It requires some new Struts-related files, which also require a property change to KFS to load them in. (KFS should still be able to boot up without the property change, though.)
We may be able to remove this customization for our next KFS upgrade if users do not need it limited to Account documents afterwards.

KFSPTS-5501: Added a Rice 2.5.x fix for immediately saving BO note adds/deletes, and tweaked it to only apply to Account maintenance docs.

---

src/main/java/edu/cornell/kfs/module/purap/CUPurapParameterConstants.java
src/main/java/edu/cornell/kfs/module/purap/document/service/CuPaymentRequestService.java
src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuPaymentRequestServiceImpl.java
src/test/java/edu/cornell/kfs/module/purap/document/service/impl/CuPaymentRequestServiceImplTest.java
src/test/java/edu/cornell/kfs/module/purap/fixture/PurchaseOrderFixture.java
src/test/java/edu/cornell/kfs/module/purap/fixture/RequisitionFixture.java
src/test/java/edu/cornell/kfs/module/purap/fixture/RequisitionItemFixture.java

This is a newer version of the forced-positive-approval feature from PR #108, which now applies to both non-quantity and quantity-based POs on the given PREQs, and which now relies on a new parameter instead of reusing an existing one.

KFSPTS-5643: Require positive approval for PREQs whose POs' amounts equal or exceed a given limit.

---

src/main/java/edu/cornell/kfs/coa/businessobject/CuAccountGlobal.java
src/main/java/edu/cornell/kfs/coa/businessobject/GlobalObjectWithIndirectCostRecoveryAccounts.java
src/main/java/edu/cornell/kfs/coa/businessobject/IndirectCostRecoveryAccountChange.java
src/main/java/edu/cornell/kfs/coa/businessobject/SubAccountGlobal.java
src/main/java/edu/cornell/kfs/coa/document/validation/impl/AccountGlobalPreRules.java
src/main/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRule.java
src/main/java/edu/cornell/kfs/coa/service/GlobalObjectWithIndirectCostRecoveryAccountsService.java
src/main/java/edu/cornell/kfs/coa/service/impl/GlobalObjectWithIndirectCostRecoveryAccountsServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/org/kuali/kfs/coa/document/validation/impl/AccountGlobalRule.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountGlobal.xml
src/main/resources/edu/cornell/kfs/coa/cu-ojb-coa.xml
src/main/resources/edu/cornell/kfs/coa/cu-spring-coa.xml
src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountGlobalMaintenanceDocument.xml
src/test/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRuleTest.java
src/test/java/edu/cornell/kfs/coa/fixture/A21IndirectCostRecoveryAccountFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/A21SubAccountFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/AccountFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/AccountGlobalDetailFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/AccountGlobalFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/IndirectCostRecoveryAccountChangeFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/IndirectCostRecoveryAccountFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/SubAccountGlobalDetailFixture.java
src/test/java/edu/cornell/kfs/coa/fixture/SubAccountGlobalFixture.java
src/test/java/edu/cornell/kfs/coa/service/impl/GlobalObjectWithIndirectCostRecoveryAccountsServiceImplTest.java

The only change between this branch (KFSPTS-3599-transient)  and the last merged branch for the Account Global additional attributes branch (KFSPTS-3599-new-4) is the addition of "transient" to the local variable GlobalObjectWithIndirectCostRecoveryAccountsService in class CuAccountGlobal.
If you do a comparison between these two stated branches, you will see a change that has been added to develop for CuDisbursementVoucherDocument, which the KFSPTS-3599-transient changes are based on so it will not be lost.
This single addition of "transient" deals with all of the stack traces that the users have reported thus far.

KFSPTS-3599-transient

---

src/main/resources/edu/cornell/kfs/core/documentstore/InstitutionPreferences.json

This updates the JSON to use the correct permission to look up to determine if links should be shown or not.  I also added headers and footers so this JSON can be directly loaded into dynamo DB.  I am not sure if we should put that here or not, but seems like a descent idea to make it easier to apply JSON changes

KFSPTS-6312 updating permission check from institution preferences

---

src/main/resources/institutional-config.properties

This updates our institutional config properties to point to Cynergy's new Location override bean file, allowing us to finally remove the old FIPS bean files from Cynergy in a future PR.

KFSPTS-6181: Updated KFS to point to new Cynergy Location bean files.

---

src/main/java/edu/cornell/kfs/krad/dao/impl/CuDocumentDaoOjb.java
src/main/resources/edu/cornell/kfs/krad/config/CUKRADSpringBeans.xml

For some reason, KFS 7.x is not performing proper transaction interception for DocumentService operations, even though DocumentServiceImpl has the "TransactionalNoValidationExceptionRollback" annotation. KFS 5.x was using the Rice-delivered DocumentDaoProxy around the OJB DAO (where the proxy had the "Transactional" annotation), so perhaps that was why we didn't encounter issues in the past.
This PR introduces a workaround similar to the one in use by Rice and earlier KFS versions. Rather than creating an explicit DAO proxy class, though, this fix just creates a DAO subclass that has the "Transactional" annotation on it, and overrides methods as needed to allow the related Spring/Rice utilities to perform interception accordingly.
I went with this workaround since it's closer to what base …

KFSPTS-7538: Fixed transaction issue with doc-related KFS batch jobs.

---

src/main/java/edu/cornell/kfs/gl/businessobject/lookup/CuCurrentAccountBalanceLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSParameterKeyConstants.java
src/main/resources/edu/cornell/kfs/gl/cu-spring-gl.xml

We had numerous customizations to the Current Account/Funds Balance lookup in KFS 5.x, and those needed to be added back in for the uprgade. Because the lookup logic requiring alteration was in a large method on the superclass, the resulting subclass had to just copy the superclass method contents and tweak them accordingly.

KFSPTS-7808: Added CU changes to Current Acct Balance lookup

---

src/main/java/edu/cornell/kfs/concur/batch/businessobject/ConcurStandardAccountingExtractDetailLine.java
src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml

This adds another SAE file field to the detail POJO, which will be needed for the Collector processing.

KFSPTS-7911: Added Report End Date to the SAE detail POJO.

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCreateCollectorFileServiceImpl.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCreateCollectorFileServiceImplTest.java

This fixes the issue where the .done file is not being created for the generated Collector file. The fix involves updating the appropriate code to return just the file name and not the full file path.
Also, as per a recent discussion with Nancy, I've updated the code so that it will not report a header-level validation error when writing the Collector data to a flat file. If more report-related logging for such errors is needed, then that will be addressed in a future user story.

KFSPTS-8357: Fixed SAE Collector .done file creation and error report.

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilder.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilderTest.java

The SAE-to-Collector processing was adding the absolute values of the line amounts for some of its report totals. As per follow-up with the functionals, this PR changes the affected code to sum up the actual amounts instead. I also included a minor logging fix.
The existing SAE-to-PDP processing appears to be summing the actual amounts properly, so that code has been left as-is.

KFSPTS-8353: Fix calculation of amount totals for SAE report.

---

src/main/java/edu/cornell/kfs/concur/businessobjects/ValidationResult.java
src/main/java/edu/cornell/kfs/concur/service/impl/ConcurEventNotificationServiceImpl.java
src/main/java/edu/cornell/kfs/concur/service/impl/ConcurReportsServiceImpl.java
src/test/java/edu/cornell/kfs/concur/businessobjects/ValidationResultTest.java
src/test/java/edu/cornell/kfs/concur/service/impl/ConcurEventNotificationServiceImplTest.java

This fix truncates the error message list to 2000 characters before database insertion.  We are also aggregating error messages so there isn't duplication.

Kfspts 8219 error message handling

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurDetailLineGroupForCollector.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurDetailLineGroupForCollectorHelper.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilder.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilderTest.java

This updates the SAE-to-Collector processing so that the detail lines are grouped differently. Instead of a single grouping layer by Report ID and accounting info, there's now a primary grouping by Report ID and a secondary grouping by accounting info. This is needed because some of the future SAE-to-Collector work will require additional processing for lines with the same Report ID.
As a result of this change, much of the OriginEntry-creating code has been moved into the line-grouping class (and tweaked accordingly), and an extra helper class has been introduced to help with passing data between the builder class and the grouping one.

KFSPTS-8452: Refactor SAE Collector code to support future changes.

---

src/main/java/edu/cornell/kfs/concur/batch/businessobject/ConcurStandardAccountingExtractDetailLine.java
src/main/java/edu/cornell/kfs/concur/batch/service/ConcurBatchUtilityService.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImpl.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurDetailLineGroupForCollectorHelper.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilder.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCreateCollectorFileServiceImpl.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractValidationServiceImpl.java
src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
src/test/java/edu/cornell/kfs/concur/ConcurTestConstants.java
src/test/java/edu/cornell/kfs/concur/batch/fixture/ConcurSAEDetailLineFixture.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilderTest.java

The SAE-related processing for PDP and Collector needs to look at additional SAE fields to determine if the line is a personal expense paid on a corporate card, and to grab the appropriate accounting data if so. (Such lines don't have accounting data in the usual SAE allocation fields.) This PR adds the needed fields to the SAE detail line POJO, as well as the associated unit test fixture.
I also updated the SAE validation service so that it can potentially view such rows as being valid. This update should theoretically not break the existing SAE-to-PDP processing (which is currently ignoring non-CASH lines), and I've added a temporary hack on the SAE-to-Collector side to ignore the personal expenses until KFSPTS-8359 has been implemented. Please look at the validation changes carefully …

KFSPTS-8531: Add personal-expense-related fields to SAE POJO.

---

src/main/webapp/WEB-INF/tags/module/purap/iWantDocumentOverview.tag

This just updates the readOnly attribute on the IWNT doc description field so that its editability is being controlled properly. (The IWNT refactoring for 7.x had accidentally introduced a bug with that field.)

KFSPTS-8305: Fixed editing of IWNT document description.

---

src/main/webapp/jsp/module/purap/IWant.jsp

This PR adds the superuser tab to the IWNT document, which got missed during the 7.x conversion. When the IWNT is displayed in its normal/full view, the tab will be placed at the bottom just before the action buttons, like what we do on other documents. When the IWNT is displayed in its "wizard" mode, the tab will be placed beneath the notes/attachments tab on the third "wizard" step, to line up with what the functionals had requested for placement.

KFSPTS-8592: Add superuser tab to IWNT document.

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractValidationServiceImpl.java

Since we're overriding the object code and omitting the sub-object code on personal expense SAE lines anyway, we need to exclude the sub-object code from the validation of such lines. Otherwise, the validation of those lines may fail (due to the report/header sub-object code possibly not existing under those lines' object codes), causing them to be excluded from the Collector processing.
This fix allows such lines to be properly included on the Collector side, and should prevent them from being logged as errors under the "original" accounting data validation on the PDP side.

KFSPTS-8726: Fix validation of SAE personal expense lines.

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/batch/service/impl/CuBatchFileAdminAuthorizationServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This updates the batch file authorization process so that a new "Download Batch File" permission template can be used to grant download-only access to batch files from the associated lookup. The existing "Administer Batch File" template for granting download and delete access should still function the same as before.
Note that there's a related nonprod-sql PR. Please make sure both are good to go before merging them.

KFSPTS-9248: Add perm template for download-only batch file access.

---

src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PayeeACHAccount.xml

Our Payee ACH Account customizations accidentally excluded the setup of a special formatter on the ID field, and this absence was causing stack traces on PAAT doc searches as a result. This fixes the issue by adding the formatter config back in.

KFSPTS-9424: Fix missing formatter setup on Payee ACH Account ID.

---

src/main/java/edu/cornell/kfs/fp/document/web/struts/CuAdvanceDepositAction.java
src/main/resources/edu/cornell/kfs/fp/document/datadictionary/AdvanceDepositDocument.xml
src/main/webapp/WEB-INF/institutional-struts-config.xml
src/main/webapp/jsp/fp/AdvanceDeposit.jsp

Advanced deposit has been brought into our overlay project so we can add one override line:
<kul:notes attachmentTypesValuesFinderClass="${documentEntry.attachmentTypesValuesFinderClass}" />

KFSPTS-9441: Add Confidential attachment type to AD documents.

---

src/main/java/edu/cornell/kfs/module/cam/batch/service/impl/CuBatchExtractServiceImpl.java
src/main/resources/edu/cornell/kfs/module/cam/cu-spring-cam.xml
src/test/java/edu/cornell/kfs/module/cam/CuCamsTestConstants.java
src/test/java/edu/cornell/kfs/module/cam/batch/service/impl/CuBatchExtractServiceImplTest.java
src/test/java/edu/cornell/kfs/module/cam/fixture/EntryFixture.java
src/test/java/edu/cornell/kfs/module/purap/fixture/VendorCreditMemoDocumentFixture.java

This updates CuBatchExtractServiceImpl to rely only on injected services, so that SpringContext.getBean() does not need to be used there. Also, the superclass already has a protected variable for the ReconciliationService, so I did not need to add one to this class.
In addition, the associated unit test has been rewritten to be a micro-test, and to perform some other related cleanup. The associated fixtures were updated as well.

KFSPTS-5548: Update CuBatchExtractServiceImpl to inject services.

---

src/main/java/org/kuali/kfs/module/purap/document/web/struts/PurchasingActionBase.java

This is an updated version of the KFSPTS-9313 fix. I've significantly narrowed its effects so that it only impacts the auto-generated note from cases where the "Send to Vendor" flag gets changed.
I've reworked this fix to incorporate certain note-updating behavior similar to that from the KFSPTS-4490 enhancement and from the base KualiDocumentActionBase.insertBONote() code.
Please let me know if you have questions or concerns about this version of the fix, or if you think someone else should review this as well.

KFSPTS-9653: Fix auto-generated note when changing send-to-vendor flag

---

src/main/resources/edu/cornell/kfs/fp/document/datadictionary/RecurringDisbursementVoucherDocument.xml

Because of the changes made to one of our overlay files for the 07/13 KualiCo patch, the DV screens are now displaying the ACH Status flag. However, the Recurring DV was missing the data dictionary configuration for this field, so we need to add that in order for the document to render correctly.

KFSPTS-9920: Add missing config to fix Recurring DV display issue

---

src/main/resources/institutional-config.properties

NOTE: There are three PRs for this change across these projects: cornell_customizations, cynergy-server-customizations, and cu-kfs.
Also, I recently added a comment on the related user story pertaining to the search warning message. Please wait for a response from me or Cathy on that before merging.
I'm not sure if the unit tests will pass yet, depending on whether the application can still boot up if the new config property references a nonexistent customizer (since the cornell_customizations PR needs merging to move that customizer into the codebase).

KFSPTS-9849: Update KIM JPA metadata to fix bounded person searches

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/A21SubAccount.xml
src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountGlobal.xml
src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/IndirectCostRecoveryRateDetail.xml

The 08-10 KualiCo patch reorganized and revised various data dictionary beans, and this caused our customization for ICR ID alphanumeric validation to not affect all of the needed objects. (We overrode the ICR Rate ID property bean in our existing code, but the 08-10 patch caused other BOs' DD config to not extend from this bean.) I was able to fix this in my local environment by adding some more bean overrides to add the customization back in where needed.

KFSPTS-10100: Fix ICR ID validation issue on KFS docs

---

pom.xml
src/main/java/edu/cornell/kfs/concur/service/impl/ConcurAccessTokenServiceImpl.java
src/main/java/edu/cornell/kfs/concur/service/impl/ConcurReportsServiceImpl.java
src/main/java/edu/cornell/kfs/fp/service/impl/AmazonWebServicesBillingServiceImpl.java
src/main/java/edu/cornell/kfs/fp/xmlObjects/AmazonAccountDetail.java
src/main/java/edu/cornell/kfs/fp/xmlObjects/AmazonAccountDetailContainer.java
src/main/java/edu/cornell/kfs/sys/util/CURestClientUtils.java
src/main/java/org/kuali/kfs/sys/web/controller/DataObjectRestServiceController.java
src/main/webapp/WEB-INF/tags/module/purap/vendor.tag
src/main/webapp/WEB-INF/web.xml
src/test/java/edu/cornell/kfs/fp/service/impl/AmazonWebServicesBillingServiceImplTest.java

NOTE: There are PRs in both cu-kfs and nonprod-sql for this change. Please make sure both are good to go before merging.
The biggest coding impact from this release was the upgrade to Jersey and JAX-RS 2.x, which required some rewrites to our REST client code to make them use the 2.x Client API instead. If you notice any errors or omissions in the refactored code, please let me know.

KFSPTS-9931: Upgrade to 2017-08-24 version of financials

---

src/main/resources/edu/cornell/kfs/coreservice/config/CUCoreServiceSpringBeans.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
src/main/resources/institutional-config.properties

NOTE: There are two PRs for this change: One in cu-kfs and one in nonprod-sql. Please make sure both are good to go before merging.
There appears to be a service-naming clash between the Rice CoreService and KFS CoreService cache admin services, which could be why the locking parameters are not being cache-cleared appropriately. I've included a fix to deploy the KFS CoreService cache admin service under a different namespace and path, so that should fix the clash.
In addition, I've updated the lock/unlock jobs to include more steps accordingly. They now have all the steps from KFS base code except the problematic CAB one (which is going to be removed in the 09/07 KualiCo patch anyway), and I've included steps for new and existing modules that didn't have them before but which still had …

KFSPTS-9312: Fix module locking and parameter cache clearing

---

src/main/java/edu/cornell/kfs/pdp/CUPdpPropertyConstants.java
src/main/java/edu/cornell/kfs/pdp/businessobject/inquiry/CuPaymentDetailInquirable.java
src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PaymentDetail.xml
src/test/java/edu/cornell/kfs/pdp/businessobject/inquiry/CuPaymentDetailInquirableTest.java

This fixes a country display error on the Payment Detail inquiry in the 09/07 patch, so that the country-code-to-name conversion will be skipped if the value represents a country name or other value that cannot be converted.
This is only a temporary fix; we should remove it once KualiCo fixes it and we bring in a patch containing that fix.

KFSPTS-10391: Fix country handling on Payment Detail inquiry

---

src/main/java/org/kuali/kfs/gl/service/impl/ScrubberValidatorImpl.java

This is an updated version of the #491 code changes, which now rely on an overlay instead of subclasses and bean overrides. This variant minimizes the number of files that need to be modified, and we can remove this overlay altogether once we upgrade cu-kfs to the 01/11/2018 KualiCo patch.

KFSPTS-10631: Fix sub-object validation issue in Scrubber

---

src/main/java/edu/cornell/kfs/concur/ConcurKeyConstants.java

There key constant for the employee not found error message did not exist in the CU-ApplicationResources.properties file. This caused a null pointer exception when generating the report and the email notification not to be sent. I have fixed this by using the correct key for the error message.

KFSPTS-10544 fix key for employee not found error message

---

src/main/java/edu/cornell/kfs/module/purap/document/validation/impl/CuPurchaseOrderAmendmentAccountValidation.java
src/main/java/edu/cornell/kfs/module/purap/service/impl/CuPurchaseOrderAmendmentAccountingLineRuleHelperServiceImpl.java
src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml
src/main/resources/edu/cornell/kfs/module/purap/document/validation/configuration/PurapValidatorDefinitions.xml
src/main/resources/edu/cornell/kfs/module/purap/document/validation/configuration/PurchaseOrderAmendmentValidation.xml

This PR updates POAs to allow for specifying expired accounts, as per the associated user story.
Note that, due to the way the code was structured, the CuPurchaseOrderAmendmentAccountValidation class had to copy nearly all of the code from the PurchaseOrderAmendmentAccountValidation parent class in order to make the necessary changes. If you think it would be better to just overlay PurchaseOrderAmendmentAccountValidation instead, please let me know.

KFSPTS-10604: Allow expired accounts on POA documents

---

src/main/java/edu/cornell/kfs/fp/batch/service/impl/AccountingXmlDocumentDownloadAttachmentServiceImpl.java
src/test/java/edu/cornell/kfs/fp/CuFPTestConstants.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTest.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentBackupLinkFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentEntryFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentListWrapperFixture.java
src/test/java/edu/cornell/kfs/sys/businessobject/fixture/WebServiceCredentialFixture.java
src/test/java/edu/cornell/kfs/sys/util/MockObjectUtils.java
src/test/resources/edu/cornell/kfs/fp/batch/xml/di-full-account-line-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/di-single-element-lists-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-di-document-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-di-plus-bad-attachments-doc-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-di-plus-bad-rules-doc-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-di-plus-invalid-doc-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/single-di-document-test.xml

The runtime-only changes are fairly minor for this, but I had to do a significant amount of unit test rework so that the affected code could be tested. If you think that the rework is too extensive for what this PR is trying to fix, please let me know.

KFSPTS-10917: Make Cred Group Code required on backup links

---

src/main/java/edu/cornell/kfs/module/ld/CuLaborKeyConstants.java
src/main/java/edu/cornell/kfs/module/ld/batch/service/impl/CuScrubberValidatorImpl.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/module/ld/cu-spring-ld.xml

The override of "checkAccountFringeIndicator" is almost the same as the superclass code, I just added a call to the new method that handles the sub-account fix.
Also, the new "removedSubAccountFromFringeEntry" variable is similar to an existing variable on the superclass that is also used for skipping the sub-account validation in certain cases.

KFSPTS-11099: Clear sub-accounts on modified LD fringe entries

---

src/main/java/edu/cornell/kfs/module/purap/service/impl/CuElectronicInvoiceHelperServiceImpl.java
src/test/java/edu/cornell/kfs/module/purap/CuPurapTestConstants.java
src/test/java/edu/cornell/kfs/module/purap/fixture/CuElectronicInvoiceHelperServiceFixture.java
src/test/java/edu/cornell/kfs/module/purap/service/impl/CuElectronicInvoiceHelperServiceXmlNamespaceTest.java

This is just a temporary workaround for an issue that was discovered during the 03/15 patch validation. We will tentatively be removing it in the near future, once we've corrected the CU application that is adding the bad namespace prefixes.
Please make sure the unit tests pass, since I modified some existing CXML testing code to be compatible with micro-testing.

KFSPTS-11710: Filter invalid namespace prefixes from CXML

---

src/main/java/edu/cornell/kfs/vnd/document/CuVendorMaintainableImpl.java

This change fixes the optimistic lock exception encountered when data is entered in the PVEN header explanation field while also tracking the header generated id - vendor detailed assigned id that is created when a PVEN edoc is approved in KFS.

KFSPTS-11657: Track PVEN approve-disapprove actions in KFS PMW stagingg table for newly created vendors.

---

pom.xml
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksKeyConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksRefreshAuthorizationTokenStep.java
src/main/java/edu/cornell/kfs/pmw/batch/service/PaymentWorksWebServiceCallsService.java
src/main/java/edu/cornell/kfs/pmw/batch/service/PaymentWorksWebServiceConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java
src/main/java/edu/cornell/kfs/pmw/web/struts/PaymentWorksManageAuthorizationTokenAction.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/pmw/cu-spring-pmw.xml
src/main/webapp/WEB-INF/institutional-struts-config.xml
src/main/webapp/jsp/pmw/manageAuthorizationToken.jsp
src/test/java/edu/cornell/kfs/pmw/PaymentWorksTestConstants.java
src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceRefreshTokenTest.java
src/test/java/edu/cornell/kfs/pmw/web/mock/MockPaymentWorksRefreshTokenEndpoint.java
src/test/java/edu/cornell/kfs/sys/util/IOExceptionProneFunction.java
src/test/java/edu/cornell/kfs/sys/web/mock/MockServiceEndpointBase.java

I've added Nancy as a co-reviewer on this. Please let me know if this feature does not conform to the requirements. I also moved the PaymentWorks URL property to a web service credential; please let me know if that property should not be moved there.
I did manage to find a way to unit test this new code. I originally tried using Jersey's testing framework, but I couldn't get it to work as expected, so I went with the Apache HttpClient test classes instead (which are also used by a unit test in cornell_customizations). If you notice anything in the unit test setup that could pose problems for our other tests, please let me know.

KFSPTS-10559: Add PMW token refresh feature

---

src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml

Since our Cornell AR module config bean does not override the "arModuleConfiguration" bean, we need to set an empty "fiscalYearMakers" list so that we don't end up with invalid duplication of fiscal year makers.

KFSPTS-12158: Fix AR beans to prevent FY Maker Job failures

---

src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java

This reverts commit a083c50624b0e70e828ee4caa45c0250a9658f39.

Revert "Use parameter values instead of parameter Names. (#608)"

---

src/main/java/edu/cornell/kfs/module/ar/dataaccess/impl/CuMilestoneDaoOjb.java
src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml

Avoid Exception on UpcomingMilestoneNotificationJob by converting java.util.Date to java.sql.Date before querying Milestones. Would converting to Timestamp be better?

KFSPTS-11599 Override MilestoneDaoOjb to avoid Exception

---

src/main/java/edu/cornell/kfs/coa/businessobject/CuAccountGlobal.java

I believe the function CuAccountGlobal.updateAccountRestrictedStatusCodeForAccountBeingEdited is no longer needed. AccountGlobalPreRules.checkForDefaultSubFundGroupStatus properly sets AccountRestrictedStatusCode to the correct value based on the sub fund group code.  So in AccountGlobal, we just need to set the restriction code on the account from the value on the account global doc.  I noticed the new lines appear to be differently indented than the existing code.  I double checked my eclipse preferences, and they appear to be correct, so I suspect the existing code's format is off.  I didn't want to format the whole file considering there were only a few lines added.

KFSPTS-6361 properly handling acct restriction status code in account global doc

---

src/main/java/edu/cornell/kfs/coa/businessobject/CuAccountGlobal.java
src/main/java/edu/cornell/kfs/coa/document/validation/impl/CuAccountGlobalRule.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountGlobalMaintenanceDocument.xml

I remove CuAccountGlobal.java.updateAccountRestrictedStatusCodeForAccountBeingEdited as the account global document resets the restriction code based on the sub fund group selected, so this code is no longer needed and causes accounts to not be properly updated with the desired restriction code.
This PR represents a second attempt to solve this problem.  Additional code has been added to check if the restriction code on the account global document is correct for the list of account's existing sub fund group code, when the account global document doesn't try and change the sub fund group code

 KFSPTS-6361 properly handling acct restriction status code in account global

---

src/main/java/edu/cornell/kfs/pmw/batch/service/PaymentWorksWebServiceCallsService.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorPayeeAchServiceImpl.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java

As per further PMW and functional feedback, we need to avoid sending Rejected status back to PMW, and the functionals will handle things manually as needed if the KFS PVEN doc gets disapproved.
The new-vendor job has been reworked so that the request will always get marked as Processed after being handled, to prevent failed ones from being picked back up on the next run. Please let me know if you find any problems with that approach.
I've also updated the related Confluence pages to reflect this PR's changes as well as some of the changes from other recent PRs. Please let me know if any of those Confluence pages need further updates.
I also wasn't sure if I was using the correct method naming conventions in the create-ACH job changes, so let me know if you have any suggestions on how to …

KFSPTS-13068: Updated PMW jobs to not send Rejected status

---

src/main/webapp/WEB-INF/tags/module/purap/purCams.tag
src/main/webapp/jsp/module/purap/Requisition.jsp

There were a couple additional tag and jsp changes that needed to be made as a result of the 08/30 financials upgrade. This PR includes the needed changes to prevent errors on REQS and PO documents.
These updates allow for the REQS and PO docs to follow the same full-entry restriction logic that we had before. Some future restriction changes may be needed on the REQS side, but I'll create a separate user story to handle that.

KFSPTS-13465: Fix bug with opening REQS and PO docs

---

src/main/resources/edu/cornell/kfs/module/cg/cu-ojb-cg.xml

This just updates the AwardAccount OJB metadata to reference CuAward instead of Award.

KFSPTS-13641: Fix issue with creating manual CGB invoice

---

src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java
src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksUploadSuppliersTest.java
src/test/java/edu/cornell/kfs/pmw/web/mock/MockPaymentWorksUploadSuppliersEndpoint.java
src/test/java/edu/cornell/kfs/sys/web/mock/MockServiceEndpointBase.java

The known KFSPTS-12898 issue is causing our JAX-RS code to use the CXF REST client instead, and that client will auto-chunk large requests by default. This fix updates the relevant code to prevent the supplier-upload process from chunking the requests, since that PaymentWorks endpoint doesn't appear to support chunked requests.

KFSPTS-13696: Disable chunking when uploading vendors to PMW

---

src/main/java/edu/cornell/kfs/sys/broker/accesslayer/RowReaderMappingBaseClassToSingleExtentClass.java
src/main/resources/edu/cornell/kfs/module/cg/cu-ojb-cg.xml
src/test/java/edu/cornell/kfs/sys/broker/accesslayer/RowReaderMappingBaseClassToSingleExtentClassTest.java

This fix allows for Award-related OJB queries to map to CuAward instead, and also affects Award-related reference descriptors similarly. I did have to override the Award OJB metadata to implement this fix, but apart from adding a row-reader attribute and an extent-class element, the Award OJB XML should be the same as in base code.
This change also acts as an alternative fix to KFSPTS-13641 (from PR #665), so I have removed its related OJB XML override as well.

KFSPTS-13687: Force OJB Award references to map to CuAward

---

src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalPreRules.java
src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalRule.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/resources/CU-ApplicationResources.properties

This updates the KFSPTS-12164 feature to perform better handling of closed and expired accounts during sub-account creation (including handling of the continuation-accounts prompt), and to also properly show the off-campus-indicator prompt when any of the new sub-accounts are flagged as off-campus.

KFSPTS-13778: More fixes for Sub-Account Global

---

src/main/java/edu/cornell/kfs/module/ar/CuArConstants.java
src/main/java/edu/cornell/kfs/module/ar/document/validation/impl/CuTotalAmountBilledToDateExceedsAwardTotalSuspensionCategory.java
src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml
src/test/java/edu/cornell/kfs/module/ar/document/validation/impl/CuTotalAmountBilledToDateExceedsAwardTotalSuspensionCategoryTest.java

This continuation of work done on https://github.com/CU-CommunityApps/cu-kfs/pull/670 .  The previous commit needed to be reverted as it did not handle award budget totals possibly being null.  That is corrected in this new PR.  A unit test was added to test this scenario as well.  This also references a new parameter that was approved on https://github.com/CU-CommunityApps/nonprod-sql/pull/476

KFSPTS-13257 award invoice suspension by award budget total

---

src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1042SProcessor.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1099Processor.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPrintProcessor.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowProcessorBuilder.java
src/main/resources/edu/cornell/kfs/tax/batch/Default1042STaxOutputDefinition.xml
src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml

The foreign vendor address fields (except line1 address) were accidentally being seen as duplicates and were being set to the values of the domestic address fields by mistake. This PR fixes the problem by converting the relevant fields to the "derived" field type, since that was the simplest way to have the job see those fields as distinct without making major changes to the tax job's current framework.
Some further work will eventually be needed to make this batch job conform to our cleaner coding standards, but that is well beyond the scope of this PR.

KFSPTS-13851 Fix foreign addresses in tax file output

---

src/main/java/edu/cornell/kfs/module/ar/document/service/impl/CuContractsGrantsInvoiceDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/module/ar/report/CuPdfFormattingMap.java
src/test/java/edu/cornell/kfs/module/ar/report/CuPdfFormattingMapTest.java

This PR introduces a custom subclass of PdfFormattingMap to fix a one-line bug in one of that class's methods. We plan to notify KualiCo about this bug, so that we can potentially remove this customization in the near future once they fix the issue in base code.

KFSPTS-12897 Fix currency formatting on invoice PDFs

---

src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardFlatInputFileType.java

PCDO processing already over wrote the account number if it was invalid.  We just needed to allow the bank file to have a NULL account number.

KFSPTS-13989 handle NULL account numbers on PCDO bank files

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCreateCollectorFileServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCreateCollectorFileServiceImplTest.java

The 2018-12-13 financials patch required us to switch this one file-searching area of Concur to use the updated batch file lookup. However, that lookup is now expecting the search directory criteria to be specified as relative directories. This PR updates the appropriate section to use relative directory criteria instead.

KFSPTS-14402 Fix CNCR job to do file search by relative path

---

src/main/java/edu/cornell/kfs/kns/datadictionary/validation/fieldlevel/IntegerValidationPattern.java
src/main/java/edu/cornell/kfs/krad/datadictionary/validation/fieldlevel/IntegerValidationPattern.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/InternalBillingItem.xml
src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/KfsBaseAttributeDefinitions.xml

The functionals have requested that certain IB/SB item fields should allow negative values, so this PR implements those changes. Note that IB/SB items only undergo very simple validation and I believe they are informational only; thus, these changes should not negatively affect any GL entries that get generated.
Unlike other item BOs, the ones for IB/SB docs treat quantity as an integer instead of a decimal number. The existing Rice/KFS validation patterns are either for decimal numbers or nonnegative integers, so I added a new pattern that allows for a larger integer range. I did that to replace the quantity field's existing validation pattern, which only allowed for nonnegative integers before.

KFSPTS-13473 Allow negative item quantity/amount on IB/SB

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/dataaccess/ActionItemNoteDetailDto.java
src/main/java/edu/cornell/kfs/sys/dataaccess/DocumentMaintenanceDao.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java
src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java

Please don't merge this yet.  I need to do some more local validation, and I want to see what happens with the prod document requeuer issue.
I used SpringContext and service locator functions to get services instead of using Spring XML configuration as these services are registered in Spring when he applicable spring context is loading.  Also, to keep this transactional, I apparently need to get  a reference to the services inside the for loop.

KFSPTS-14446 persist action notes in document requeuer job

---

src/main/java/edu/cornell/kfs/module/purap/document/validation/impl/CuAccountsPayableBankCodeValidation.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/edu/cornell/kfs/sys/document/validation/impl/CuBankCodeValidation.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/module/purap/document/validation/configuration/PurapValidatorDefinitions.xml

This PR updates our customized bank code validation to be much cleaner, and to also make use of superclass functionality where possible. The customization has also been modified to be more consistent with the superclass changes that were made in base code.
The old customization had a feature for auto-clearing the bank account (and warning the user) in certain cases. We do not appear to need such cases anymore, so that part of the functionality has been removed.
I also added a new static method to properly allow the CuDisbursementVoucherBankCodeValidation class to call our custom code. (No changes were needed to CuDisbursementVoucherBankCodeValidation itself, due to the way it was trying to call the static method before.)

KFSPTS-9705 clean up custom bank code validation

---

src/main/webapp/WEB-INF/tags/kr/page.tag

This is nearly identical to the "page.tag" file from the base financials code. The only change is to the generation of the "body" tag within the "c:otherwise" block, where instead of invoking the restoreScrollPosition() function directly, the function is now being passed into a setTimeout() function call so that its execution will be delayed slightly. This fixes an issue where some browsers (most notably IE) are not properly restoring the previous scroll position immediately following a change to the field focus.

KFSPTS-14884 Fix scroll position bug in some browsers

---

src/main/java/edu/cornell/kfs/module/ar/service/impl/CuAREmailServiceImpl.java

One of our custom service implementations has a method override that is preventing a 2019-04-11 patch fix from taking effect. This PR updates that method override so that it includes the appropriate fix from base code.

KFSPTS-15664 Add fund manager email fix from 2019-04-11 patch

---

src/main/java/org/kuali/kfs/module/ar/businessobject/MilestoneSchedule.java
src/main/java/org/kuali/kfs/module/ar/businessobject/PredeterminedBillingSchedule.java
src/main/java/org/kuali/kfs/module/ar/document/MilestoneScheduleMaintainableImpl.java
src/main/java/org/kuali/kfs/module/ar/document/PredeterminedBillingScheduleMaintainableImpl.java

This PR takes the FINP-4678 milestone/PDBS fix from the 2019-05-02 KualiCo patch, and integrates it into our current cu-kfs code. This fix has been included by using overlays of the relevant files, so that we can easily remove the overlays once we upgrade cu-kfs to financials version 2019-05-02 or newer.
These overlays should be the same as the 2019-04-25 versions of the files, except that the FINP-4678 fixes have been added and a few explanation comments have also been added.

KFSPTS-15575 Add FINP-4678 milestone/PDBS fix from KualiCo

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/SubFundProgram.xml

The Sub-Fund Program Description field was not allowing the same number of characters as what the database currently allows. This PR fixes the problem by adjusting the DD XML so that the program description max length matches the 255 character max length from the database.
In addition, I made a few quick fixes to make the Sub-Fund Program label more user-friendly, and to make the title attribute actually reference an appropriate Sub-Fund Program field so that the lookup results will generate related inquiry links. This will make it easier for users to view the longer Sub-Fund Program Description values, since the lookup will only show a portion of the descriptions that are too long.

KFSPTS-15510 Fix sub-fund program description max length

---

src/test/java/edu/cornell/kfs/rass/batch/xml/RassXmlDocumentWrapperMarshalTest.java
src/test/resources/edu/cornell/kfs/rass/rass_complex_example.xml
src/test/resources/edu/cornell/kfs/rass/rass_single_agency_only.xml
src/test/resources/edu/cornell/kfs/rass/rass_single_award_only.xml

This PR updates RassXmlDocumentWrapperMarshalTest.java to include a larger variety of test cases. The changes currently just import some RASS XML data from other related unit tests, though I did have to add new files for the ones that did not yet have an XML file associated with them.

KFSPTS-15101 Add more RASS XML parsing unit tests

---

src/main/java/edu/cornell/kfs/rass/RassConstants.java
src/main/java/edu/cornell/kfs/rass/RassKeyConstants.java
src/main/java/edu/cornell/kfs/rass/batch/RassBatchJobReport.java
src/main/java/edu/cornell/kfs/rass/batch/RassStep.java
src/main/java/edu/cornell/kfs/rass/batch/RassXmlFileProcessingResult.java
src/main/java/edu/cornell/kfs/rass/batch/service/RassReportService.java
src/main/java/edu/cornell/kfs/rass/batch/service/RassService.java
src/main/java/edu/cornell/kfs/rass/batch/service/impl/RassReportServiceImpl.java
src/main/java/edu/cornell/kfs/rass/batch/service/impl/RassServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/resources/edu/cornell/kfs/rass/cu-rass-resources.properties
src/main/resources/edu/cornell/kfs/rass/cu-spring-rass.xml
src/test/java/edu/cornell/kfs/rass/RassTestConstants.java
src/test/java/edu/cornell/kfs/rass/batch/service/impl/FileWithExpectedResults.java
src/test/java/edu/cornell/kfs/rass/batch/service/impl/RassMockServiceFactory.java
src/test/java/edu/cornell/kfs/rass/batch/service/impl/RassReportServiceImplTest.java
src/test/java/edu/cornell/kfs/rass/batch/service/impl/RassServiceImplTest.java
src/test/java/edu/cornell/kfs/rass/batch/xml/fixture/RassXmlDocumentWrapperFixture.java
src/test/resources/edu/cornell/kfs/rass/batch/cu-spring-rass-report-test.xml
src/test/resources/edu/cornell/kfs/rass/reports/agency-errors.txt
src/test/resources/edu/cornell/kfs/rass/reports/empty-input.txt
src/test/resources/edu/cornell/kfs/rass/reports/errors-for-multi-files.txt
src/test/resources/edu/cornell/kfs/rass/reports/errors-for-single-file.txt
src/test/resources/edu/cornell/kfs/rass/reports/mixed-items.txt
src/test/resources/edu/cornell/kfs/rass/reports/single-items.txt

This PR updates the RASS batch job so that each processable XML file will have a unique report file generated for it, rather than lumping all of the report data into one file. For any files that have a complete parsing failure (such as from malformed XML), those files will be lumped into one error report file.
I had to perform a fair amount of refactoring for the RASS service (and related unit test(s)) so that the agency/proposal/award updates would be organized on a per-file basis. I've also added a new unit test to perform some basic testing of the report file generation process.
Please let me know if you notice any obvious problems with these refactoring changes.

KFSPTS-16513 Create RASS reports for each XML file

---

src/main/java/edu/cornell/kfs/rass/batch/RassProjectDirectorConverter.java
src/main/resources/edu/cornell/kfs/rass/cu-spring-rass.xml
src/test/java/edu/cornell/kfs/rass/batch/service/impl/RassMockServiceFactory.java
src/test/resources/edu/cornell/kfs/rass/batch/cu-spring-rass-service-test.xml

The heart of this change is to assign the project director role to those who don't have the role when RASS attempts to add or update a project director on a proposal or an award.  The RASS integration checks to see if the person has the role before adding them to the role.  Ezra had no check, and always added them to the role.
Also, I fixed the formating on RassProjectDirectorConverter.
People without an active employee affiliation don't seem to cause a problem when they are added a project director, so no changes where made to check that.

KFSPTS-16676 update handing of RASS project directors

---

src/main/java/edu/cornell/kfs/rass/batch/AwardTranslationDefinition.java

Our RASS code generally auto-handles inserting filler objects into old-maint-BO lists when needed. However, the fund managers list is not affected by the current auto-handling, due to its custom setup for populating that list. This PR updates the RASS Award handling to auto-insert into the old-BO fund managers list when needed, which is necessary to prevent document-rendering problems when RASS edits an existing Award to add a fund manager.

KFSPTS-16733 Fix AWRD-edit rendering when RASS adds fund mgr

---

src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java
src/main/java/edu/cornell/kfs/tax/businessobject/TransactionDetail.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1042SProcessor.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowBuilder.java
src/main/resources/edu/cornell/kfs/tax/batch/Default1042STaxOutputDefinition.xml
src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml
src/main/resources/edu/cornell/kfs/tax/batch/DefaultTransactionRowOutputDefinition.xml
src/main/resources/edu/cornell/kfs/tax/cu-ojb-tax.xml

Note that there are two PRs for this: One in cu-kfs and one in nonprod-sql.
As per the feedback on the user story, the functionals are fine with the province being added to the output for all foreign country entries if present, not just for Canada.

KFSPTS-16111 Add foreign vendor province to 1042S output

---

src/main/java/edu/cornell/kfs/coa/businessobject/options/CuCheckingSavingsValuesFinder.java
src/main/java/edu/cornell/kfs/coa/businessobject/options/CuSimpleChartValuesFinder.java
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
src/main/java/edu/cornell/kfs/sys/businessobject/options/CuConfidentialAttachmentTypeValuesFinder.java
src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PayeeACHAccount.xml
src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/KfsBaseAttributeDefinitions.xml
src/main/resources/edu/cornell/kfs/sys/cu-sys-lookup-beans.xml
src/main/webapp/WEB-INF/tags/module/purap/iWantNotes.tag
src/main/webapp/WEB-INF/tags/module/purap/notes-sciquest.tag
src/main/webapp/WEB-INF/tags/module/purap/ponotesSciquest.tag
src/main/webapp/jsp/fp/AdvanceDeposit.jsp
src/main/webapp/jsp/fp/DistributionOfIncomeAndExpense.jsp
src/main/webapp/jsp/module/purap/IWant.jsp
src/main/webapp/jsp/module/purap/Requisition.jsp
src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java

With the 07/18/2019 financials patch, the values finders are expected to follow certain naming conventions for their classnames and beans, and we had a few such classes/beans that needed to be updated to match those conventions. (Some KFS pages would fail to load completely if they referenced a values finder that was not set up properly.) There were also some areas where our code/JSP files still needed to update their "...ValuesFinderClass" references to be "...ValuesFinder" references instead. This PR adds some fixes to address both issues.
If you notice any other areas where the values finder setup needs further tweaking, please let me know.

KFSPTS-16937 Fix values finder setup

---

src/main/java/org/kuali/kfs/module/purap/document/AccountsPayableDocumentBase.java

Our KFSUPGRADE-1124 ticket corrected an issue that was preventing certain PURAP docs (such as Payment Requests and Credit Memos) from properly updating the items' extended costs when clicking the doc's "Calculate" button. However, we accidentally removed this fix when we upgraded cu-kfs to the 2019-07-18 financials patch. This PR reintroduces our extended cost fix, and also adds a nearby comment to help point out the area that was customized.

KFSPTS-16954 Reintroduce fix for PURAP extended prices

---

src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentFileServiceImpl.java

There are cases where a bad PDP file will throw an exception other than ParseException, which interferes with sending error emails since such code normally only does so for ParseException. This fix changes the PDP Load Payments code so that other types of exceptions can also trigger PDP error emails.

KFSPTS-16992 Fix error email handling in PDP Load Payments

---

src/main/java/org/kuali/kfs/module/purap/document/PurchaseOrderDocument.java

Our changes for the 07/18/2019 financials patch accidentally removed our KFSPTS-1458 customization, which properly copies vendor emails from the REQS doc to the PO doc. This PR reintroduces that fix.

KFSPTS-16990 Reimplement vendor email fix for POs

---

src/main/resources/edu/cornell/kfs/sys/document/workflow/CampusMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/CampusTypeMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/CountryMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/CountyMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/PostalCodeMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/StateMaintenanceDocument.xml

We had forgotten to ingest the workflow XML for the new KFS-side Location documents, which are active in the 2019-07-18 financials patch. This PR adds the relevant workflow XML to our cu-kfs project and tweaks it accordingly.

KFSPTS-16986 Add doc types for KFS Location documents

---

src/main/java/com/rsmart/kuali/kfs/cr/batch/CheckReconciliationImportStep.java
src/main/java/com/rsmart/kuali/kfs/cr/businessobject/CheckReconciliation.java
src/main/java/com/rsmart/kuali/kfs/cr/dataaccess/impl/CheckReconciliationDaoOjb.java
src/main/resources/com/rsmart/kuali/kfs/cr/businessobject/datadictionary/CheckReconciliation.xml
src/main/resources/com/rsmart/kuali/kfs/cr/ojb-cr.xml

There are two PRs for this: One in cu-kfs and one in nonprod-sql.
This PR replaces the Check Recon "lastUpdate" field with the base financials "lastUpdatedTimestamp" field (inherited from PersistableBusinessObjectBase). KFS will auto-update this field with the current timestamp just prior to saving the Check Recon object to the database, so the lines for manually setting this timestamp have been removed.

KFSPTS-7344 Rename Check Recon timestamp field

---

src/main/resources/edu/cornell/kfs/module/ar/cu-ar-resources.properties

The 2019-07-25 financials patch accidentally broke the Lockbox Upload page by removing the config property for its title text. This PR reinserts the missing config property into one of our CU-specific resource files as a temporary fix, and we can remove this fix once we upgrade to the 2019-08-22 financials patch (where KualiCo added their own fix for this).

KFSPTS-17381 Fix 2019-07-25 patch bug with Lockbox Upload

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/SubFundProgram.xml

Note that there are two PRs for this change: One in cu-kfs and one in nonprod-sql.
The Sub-Fund Program objects were still on the old lookup framework, which is capable of truncating certain field values that are too long. This PR migrates the Sub-Fund Program lookup to the new framework so that it doesn't experience the truncation issue.

KFSPTS-16809 Move Sub-Fund Program to new lookup framework

---

src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentFileValidationServiceImpl.java
src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PaymentDetail.xml
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml

The PDP Load Payments Job was not properly validating certain Payment Detail field lengths on the input files, which could lead to unexpected errors when saving to the database. This PR adds in some Payment Detail field length checks that are similar to those for the job's Payment Group validation. Additionally, some of the Payment Detail data dictionary configuration was overridden, so that the max lengths would be consistent with the column lengths in the database.
There are still some account-related fields that would be good to add to this validation, but that work will be deferred to a future sprint, as per the input from the functionals.

KFSPTS-17118 Fix detail validation for PDP Load Payments

---

src/main/java/org/kuali/kfs/sys/document/web/renderers/GroupTitleLineRenderer.java

Our values finder classes were recently modified to have their dependent services inserted via Spring injection instead. However, the GroupTitleLineRenderer was manually instantiating one of the affected values finders at runtime, resulting in NullPointerExceptions that could cause certain pages (like the REQS doc) to not finish rendering.
This PR fixes the issue by retrieving and setting the dependent service on the values finder manually. I do not believe GroupTitleLineRenderer can be reconfigured to avoid SpringContext.getBean() calls at this time, which was what I needed for retrieving the dependent service.

KFSPTS-17562 Fix REQS render issue related to values finder

---

src/main/java/edu/cornell/kfs/module/purap/CUPurapConstants.java
src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java

There are PRs for this change in cu-kfs, einvoice-api-server, and einvoice-website. Please make sure all three are good to go before merging.
This PR set implements multiple vendor-related eInvoice enhancements, as outlined on the related user story.
For the extent of the changes that involve the cu-kfs project, this PR just adds an endpoint that allows for retrieving all of KFS's active Units of Measure. Please let me know if you think that the API path needs to be changed.

KFSPTS-17681 eInvoice Vendor-related screen improvements

---

src/main/java/edu/cornell/kfs/sec/document/CuSecurityModelMaintainableImpl.java
src/main/resources/edu/cornell/kfs/sec/document/datadictionary/SecurityModelMaintenanceDocument.xml

Base code's buildModelRoleId function prepends "KFS-SEC-" to the security model's ID.  This customization is to just. use the security model's ID without anything in front.

KFSPTS-11929 make security model generated roleID be just numeric

---

src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml
src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/IWantDocVendorDetail.xml

A couple of our Spring beans were missing some service injection that is now required as a result of the 2019-09-05 financials upgrade. This PR fixes the two known cases where the extra injection is needed.

KFSPTS-18143 Fix bean setup for 2019-09-05 patch

---

src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherDocument.java

This PR backports the FINP-6585 fix for a particular DV field. However, KualiCo's fix relies upon a data dictionary service method that was not introduced until the 2020-02-27 financials patch. Thus, our version of the fix uses a different service method that has almost the same functionality.

KFSPTS-18321 Fix Documentation Location Code on DVs

---

pom.xml
src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurDTOMarshalTest.java
src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurEventNotificationListDTOTest.java

There are PRs for this in cornell_customizations, cynergy-server-customizations, cynergy-standalone, and cu-kfs.
This PR adds in some cu-kfs POM changes that are similar to those that Jay temporarily added when making cu-kfs work with Java 11. It also tweaks the Cynergy version number slightly to account for the changes proposed in the related Cynergy PRs. If you think some of these POM changes are unneeded, please let me know.
I'm not certain if the PR unit tests are running on Java 11 yet. Please check with DevOps on whether that has been set up.
Also, depending on what artifacts have already been deployed to nexus as a result of the IntDev testing, this PR's unit tests might not pass until the cornell_customizations PR has been merged and the build jobs have executed appropriately.

KFSPTS-17530 Update cu-kfs POM for Java 11 use

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/SubFundProgram.xml
src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/AgencyOrigin.xml

This PR fixes both KFSPTS-18436 and KFSPTS-18548, since each only involved quick one-line changes to the data dictionary XML.

KFSPTS-18436 Fix Sub-Fund Program and Agency Origin lookups

---

pom.xml

This PR fixes the Eclipse-specific error concerning the lifecycle setup for the Maven Checkstyle plugin. The fix just ignores the plugin for cases when Eclipse builds the code itself. (This should not affect the Checkstyle plugin that is part of the Eclipse IDE itself.)
Note that this change only impacts the build of the code from within Eclipse; it should not affect building/testing/packaging the code from command line.

KFSPTS-18098 Add Eclipse lifecycle mapping for Checkstyle

---

src/main/java/edu/cornell/kfs/module/purap/CUPurapConstants.java
src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java

There are PRs for this in cu-kfs and einvoice-api-server.
Also, I realized that this PR's new getPurchaseOrderShippingAddress() method shares a lot of the same code as getPurchaseOrder(). It would be good to consolidate some of the common logic, but that might make more sense to do in a subsequent user story. Please let me know your thoughts on this.

KFSPTS-18609 Add PO shipping address to eInvoice CXML

---

src/test/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImplTest.java
src/test/java/edu/cornell/kfs/module/ld/batch/service/impl/CuFileEnterpriseFeederServiceImplTest.java
src/test/java/edu/cornell/kfs/module/receiptProcessing/service/CuReceiptProcessingServiceImplPositiveTest.java

One of the failing tests was trying to create (and copy a file to) a directory that could not be auto-created properly on the new Jenkins instance. I was also unable to get the test to run locally in its old state. I fixed it by having the test derive the directory based on a property of the ReceiptProcessingService, so that the path would involve a more file-friendly location (such as the staging directory).
Two other tests were failing in the new Jenkins instance, but were succeeding locally. It turns out that the new Jenkins instance didn't have its Java locale settings set up as expected, which caused the tests to be unable to format currency values properly. Now that DevOps has fixed the Jenkins issue, these two tests can succeed as-is (apart from removing the "Ignore" annotations).

KFSPTS-18575 Fix unit tests to work with Java 11

---

src/main/java/edu/cornell/kfs/kns/lookup/LookupableHelperServiceWithPrincipalNameHandling.java
src/main/java/edu/cornell/kfs/kns/lookup/PrincipalNameHandlingLookupableHelperService.java
src/main/java/edu/cornell/kfs/kns/lookup/PrincipalNameHandlingLookupableHelperServiceBase.java
src/main/java/edu/cornell/kfs/module/ar/CuArPropertyConstants.java
src/main/java/edu/cornell/kfs/module/ar/businessobject/lookup/InvoiceRecurrenceLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/module/ar/document/service/impl/CuContractsGrantsInvoiceDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/sec/businessobject/lookup/AccessSecurityAccountDelegateLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/sec/businessobject/lookup/AccessSecurityPrincipalNameHandlingLookupableHelperServiceBase.java
src/main/java/edu/cornell/kfs/sec/businessobject/lookup/AccessSecurityProjectCodeLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/sec/businessobject/lookup/SecurityPrincipalLookupableHelperServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/edu/cornell/kfs/sys/businessobject/lookup/UserProcurementProfileLookupableHelperServiceImpl.java
src/main/resources/edu/cornell/kfs/module/ar/businessobject/datadictionary/InvoiceRecurrence.xml
src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml
src/main/resources/edu/cornell/kfs/sec/businessobject/datadictionary/SecurityPrincipal.xml
src/main/resources/edu/cornell/kfs/sec/cu-spring-sec.xml
src/main/resources/edu/cornell/kfs/sec/datadictionary/AccessSecurityOverrides-lookups.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

NOTE: This PR fixes the unit tests that broke with the 03/20 patch upgrade. Please make sure the unit tests pass before merging.
One of the unit tests was failing because CuContractsGrantsInvoiceDocumentServiceImpl accidentally specified the wrong rounding mode in one spot. I have fixed the problematic area to use the correct rounding mode.
The other broken test was failing because its lookup lacked conversion of principal name criteria to principal ID criteria, which now seems to be required if the principal name property reference is tied to a Person instance on the BO. I fixed the lookup that the test depended on, as well as a few other lookups that also appear to have broken for the same reason. (KualiCo was inconsistent with fixing this lookup issue in base code.)

KFSPTS-19226 Fix broken unit tests and lookups

---

src/main/java/edu/cornell/kfs/kns/service/impl/CuBusinessObjectAuthorizationServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/resources/edu/cornell/kfs/kim/bo/datadictionary/CuKimBaseBeans.xml
src/main/resources/edu/cornell/kfs/kim/cu-spring-kim.xml
src/main/resources/edu/cornell/kfs/kim/impl/identity/PersonImpl.xml
src/main/resources/edu/cornell/kfs/kim/impl/identity/address/EntityAddressBo.xml
src/main/resources/edu/cornell/kfs/kim/impl/identity/email/EntityEmailBo.xml
src/main/resources/edu/cornell/kfs/kim/impl/identity/name/EntityNameBo.xml
src/main/resources/edu/cornell/kfs/kim/impl/identity/phone/EntityPhoneBo.xml
src/main/resources/edu/cornell/kfs/krad/config/CUKRADSpringBeans.xml

The various KIM entity objects (name, address, etc.) have their own custom data-masking setup that is built into the BOs themselves. However, this prevents the proper unmasking of their fields when viewed through the regular inquiry pages, and the KIM-to-KFS move now displays Person objects on the regular inquiry instead of the custom Person-document-related inquiry.
To work around the issue, this PR updates the Person inquiry to use the unmasked property getters for the potentially-masked fields. In addition, some customizations have been added to set up DD-based masking for the unmasked getters, and to make the relevant service allow for unmasking these properties under the appropriate circumstances.

KFSPTS-19279 Fix viewing of masked fields on Person inquiry

---

src/main/java/org/kuali/kfs/sys/rest/resource/businessobject/LookupResource.java

This PR updates the refactored lookups so that, like with the old lookups, they will auto-insert an empty drop-down entry if the values finder does not return one already. Because the change involved updating a private method (buildLookupControlValuesMap), the fix has been implemented as an overlay.

KFSPTS-19339 Auto-insert empty entries in lookup drop-downs

---

src/main/java/org/kuali/kfs/kim/bo/ui/PersonDocumentGroup.java
src/main/java/org/kuali/kfs/kim/document/IdentityManagementPersonDocument.java
src/main/java/org/kuali/kfs/kim/web/struts/action/IdentityManagementPersonDocumentAction.java
src/main/webapp/WEB-INF/tags/kim/personGroup.tag

The Person document has a bug where the group membership "Inactivate" buttons are visible on uneditable documents. This PR fixes that by adding new group-action-checking logic. The new logic is similar to what the Person doc already uses for showing the role membership actions.
Implementing the changes via overlays seemed like the simplest and least invasive way to do so, given the types of code and config areas that needed adjustment.

KFSPTS-19317 Fix group member button display on Person doc

---

src/main/java/org/kuali/kfs/kim/service/impl/KimModuleService.java
src/main/java/org/kuali/kfs/kns/web/struts/action/KualiInquiryAction.java
src/main/webapp/WEB-INF/tags/kim/roleAssignees.tag
src/main/webapp/WEB-INF/tags/kr/documentPageWithModalInquiryMode.tag
src/main/webapp/WEB-INF/tags/kr/stayOnPage.tag
src/main/webapp/jsp/kim/IdentityManagementPersonDocument.jsp
src/main/webapp/jsp/kim/IdentityManagementRoleDocument.jsp
src/main/webapp/scripts/modal-inquiry-setup.js

There are changes for this in both cu-kfs and cynergy-server-customizations. Please make sure both PRs are good to go before merging.
This PR updates KFS so that it will use the older-style KIM inquiry pages for the Person and Role inquiries. Much of this behavior has been implemented via overlays (with comments indicating what changed), in case we decide to contribute any of it back to KualiCo.
Various areas have been customized accordingly so that these inquiries can open in modal/popup boxes. The main inquiry action class has also been customized, so that custom redirects can be used without marking the objects as "externalizable" (which would have required specifying additional custom searching behavior and such).
In addition, a new script has been added that allows for certain Role …

KFSPTS-19382 Fix older-style Person and Role inquiries

---

src/main/java/edu/cornell/kfs/kim/CuKimConstants.java
src/main/java/edu/cornell/kfs/kim/datadictionary/validation/fieldlevel/CuKimPhoneNumberValidationPattern.java
src/main/resources/edu/cornell/kfs/kim/bo/datadictionary/PersonDocumentPhone.xml
src/main/resources/edu/cornell/kfs/kim/cu-kim-attribute-beans.xml
src/main/resources/edu/cornell/kfs/kim/cu-kim-resources.properties
src/main/resources/edu/cornell/kfs/kim/impl/identity/PersonImpl.xml
src/main/resources/institutional-config.properties
src/test/java/edu/cornell/kfs/kim/datadictionary/validation/fieldlevel/CuKimPhoneNumberValidationPatternTest.java

We have an existing customization in standalone Cynergy that allows for a larger number of valid phone number formats. This PR adds that customization to the KFS side, but restricts it to the Person document and its related pages (which might be the only spot that needs the extra format options).

KFSPTS-19381 Fix Person doc phone number validation

---

src/main/resources/edu/cornell/kfs/module/cg/document/datadictionary/ProposalMaintenanceDocument.xml

Our 03/20/2020 financials upgrade accidentally removed a customization that allowed for entering an explicit proposal number on the Proposal Document. This PR reintroduces that customization, and also reimplements it to use KualiCo's DD-bean-field-override feature. (As far as I can tell, the edit-proposal-number customization was our only change to the "ProposalMaintenanceDocument-ProposalMaintenance" bean.)

KFSPTS-19638 Reimplement allowing custom proposal numbers

---

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/TaxRule.java
src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImpl.java
src/main/resources/edu/cornell/kfs/pmw/cu-ojb-pmw.xml
src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImplTest.java

PaymentWorks opted to create a new PO country field on the new foreign form for us.  To support this change we renamed poCountryCode to poCountryCodeLegacy and created a new poCountryCode.  This seems like the most supportable option as we move forward with the new form.
please note there is a related non-orod-SQL pr

KFSPTS-19404 handle new PMW PO country field

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/org/kuali/kfs/pdp/web/struts/FormatAction.java

We have a customization that redirects the user to the Format Summary (aka ProcessSummary) lookup after going through the formatting actions. This PR updates that customization so that the user will be redirected to the refactored ProcessSummary lookup, now that KualiCo has removed support for the old version of that lookup.

KFSPTS-20019 Redirect to refactored lookup after PDP format

---

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksTaxRuleDependencyServiceImpl.java
src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksTaxRuleDependencyServiceImplTest.java

In the enum PaymentWorksTaxClassification, the values for legacyFormTranslationToKfsOwnershipTypeCode and foreignFormTranslationToKfsOwnershipTypeCode are now in sync with this PR.  I opted to keep the two separate fields for now in order to get this fix handled quickly.  Also, we have a user story in the near future to remove legacy form processing code, which includes removal of legacyFormTranslationToKfsOwnershipTypeCode from this enum.

KFSPTS-20352 update PMW LLC ownership mapping

---

src/main/java/org/kuali/kfs/fp/document/service/impl/DisbursementVoucherTaxServiceImpl.java

There are some income-tax-related areas where the financials 10/29/2020 patch accidentally compares KualiDecimals against BigDecimals, which can result in unexpected errors. This PR adds some fixes for those by overlaying the DisbursementVoucherTaxServiceImpl class.
Note that some of the problematic areas were fixed by our initial commit of the 10/29/2020 patch to the develop branch. This PR expands the fix to another class that was having issues.

KFSPTS-20379 Fix DV income tax bug in 10/29/2020 patch

---

pom.xml
src/main/java/edu/cornell/kfs/fp/service/impl/CUPaymentMethodGeneralLedgerPendingEntryServiceImpl.java
src/main/java/edu/cornell/kfs/sys/batch/DocumentReindexStep.java
src/main/java/edu/cornell/kfs/sys/service/CuGeneralLedgerPendingEntryService.java
src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

Our existing DocumentReindexStep takes in a list of document numbers to index where the new kualiCo patch job re indexes based on document type.  I think we need to keep the existing batch job, but will follow up with Cathy.  I did update DocumentReindexStep to use the save index base code service as the new batch job so both jobs index documents in the same fashion

KFSPTS-20244 upgrade to the 11-12-2020 version of financials

---

src/main/java/org/kuali/kfs/sys/service/impl/GeneralLedgerPendingEntryServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This PR backports the GLPE fiscal period fix from KualiCo's 2020-12-10 patch.
I verified locally that KFS can still boot up with the changes in place, but I ran out of time today to validate the effects of the fix in my local environment. If the team is okay with deferring the testing until the changes move into DEV, then this PR can be merged after another developer approves it.
Note that CuGeneralLedgerPendingEntryServiceImpl currently does not have code changes in this PR; it has a method that sets up the GLPE fiscal period, but it uses the old behavior of setting it to null like we want it to. If you think that service method should be modified to do the parameter-based check on whether to set to null, please let me know.

KFSPTS-20565 Backport FINP-7275 GLPE fiscal period fix

---

src/main/java/org/kuali/kfs/sys/service/impl/GeneralLedgerPendingEntryServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This is a temporary backport of the FINP-7275 fiscal period posting fix from KualiCo, which is meant to be committed straight to the master branch with a tentative release to PROD on our next scheduled patch. This change will then be reverted once we're ready to move the 2020-11-12 financials changes forward to TEST, since the develop branch has its own version of this backport that is compatible with the 2020-11-12 patch.

KFSPTS-20565 Temp backport of FINP-7275 fix to master

---

src/main/java/edu/cornell/kfs/fp/batch/service/impl/CuDisbursementVoucherDocumentGenerator.java
src/main/java/edu/cornell/kfs/fp/document/service/CuDisbursementVoucherPayeeService.java
src/main/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherPayeeServiceImpl.java
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTest.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/fixture/DocGenVendorFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentEntryFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentListWrapperFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/CuDisbursementVoucherDocumentFixture.java
src/test/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherPayeeServiceImplVendorTypeTest.java
src/test/resources/edu/cornell/kfs/fp/batch/xml/dv-document-vendor-test.xml

The Create Accounting Documents Job had a bug in its DV generation process, where DV vendors were always given the "V" payee type, regardless of the vendor type defined on the vendor header record. This can cause the DV to erroneously allow the payment-reason-related business rules to pass, since some types of vendors are not allowed to be specified for particular DV payment reasons. This PR fixes the issue, where it will set up DV vendor payees with the correct payee type code, based on the map returned by the DisbursementVoucherPayeeServiceImpl.getVendorPayeeTypeCodeMapping() method. (The existing DV business rules will stop the document from being submitted if the given vendor payee is the wrong type for the given payment reason.)
A simple unit test and supporting classes were added, …

KFSPTS-20409 Fix vendor payee type setup from DV XML docs

---

src/main/java/edu/cornell/kfs/sys/service/impl/CuGeneralLedgerPendingEntryServiceImpl.java
src/main/java/org/kuali/kfs/sys/service/impl/GeneralLedgerPendingEntryServiceImpl.java

Our prior sprints preserved a GLPE-related helper method that KualiCo had removed, but it currently does not contain the advanced fiscal-period-deriving functionality from the FINP-7275 fix in base code. This PR updates the custom method to take advantage of the FINP-7275 changes.
This PR does not update the documents that rely on our custom method for GLPE generation. (I think our PREQ documents are the only ones actively using the custom CU GLPE method.) If we decide to allow for more use of the fiscal-period-choosing feature via a drop-down or other means, we would need to alter the affected documents appropriately, and I would suggest doing that in a separate user story.

KFSPTS-20744 Add fiscal period feature to custom GLPE code

---

src/main/java/edu/cornell/kfs/pdp/batch/service/PayeeACHAccountDocumentService.java
src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
src/test/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImplTest.java

I moved code from PayeeACHAccountExtractServiceImpl to the new service PayeeACHAccountDocumentServiceImpl to make  addACHAccount and updateACHAccountIfNecessary.  To avoid adding extra complications to this work, I didn't do "clean code" refactors.  If there are changes you think should be made now, please let me know

KFSPTS-21519 making adding and editing a PAAT document through batch job transactional

---

src/main/webapp/WEB-INF/tags/kr/documentPageWithModalInquiryMode.tag

KualiCo removed the "feedbackKey" attribute from various tags for the KEW-to-KFS patch. This PR fixes one of our custom tags to also remove that attribute.

KFSPTS-21744 Remove unneeded feedbackKey attribute

---

src/main/resources/OJB-repository.xml
src/main/resources/edu/cornell/kfs/cu-spring-kfs.xml
src/main/resources/institutional-config.properties
src/main/resources/org/kuali/kfs/kew/impl/config/OJB-repository-kew-connection.xml

The base KEW-to-KFS financials patch has some OJB repository files that hard-code MySQL as the database platform to use. This PR overlays the relevant files so that they will use the Oracle platform instead.
Note that our pre-upgrade SQL was using OJB's "Oracle9i" platform, which has a few differences from OJB's regular Oracle platform type. This PR reinstates the use of this "Oracle9i" type, and also adjusts the Kuali-specific "dbPlatform" bean override's setup in an attempt to avoid confusion with the OJB "Oracle9i" type. (Rice/KFS used to have a matching Oracle9iDatabasePlatform class, but it seems to have been removed for KEW-to-KFS since it was merely a subclass of OracleDatabasePlatform with no extra changes.)

KFSPTS-21705 Fix sequence handling for KEW conversion

---

src/main/java/org/kuali/kfs/module/purap/RequisitionStatuses.java
src/main/resources/institutional-config.properties

There were a few minor non-KEW-related changes from the 2021-01-28 patch, but one of our overlays was not updated to account for that and it started causing our unit tests to fail. This PR fixes the problematic file to correctly account for the 2021-01-28 financials patch changes.
There's still one config-related problem that DevOps needs to deal with for the upgrade PRs, but once that's taken care of, all of the unit tests on this PR should pass. Make sure you open the details on the checks/tests in Jenkins, to verify that the tests indeed passed.

KFSPTS-21650 Add missing 2021-01-28 changes impacting unit tests

---

src/main/java/org/kuali/kfs/sys/batch/DailyEmailStep.java
src/main/java/org/kuali/kfs/sys/batch/WeeklyEmailStep.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
src/main/resources/institutional-config.properties

This PR backports certain parts of KualiCo's FINP-7413 updates. Most of KualiCo's changes revolved around removing Quartz-related code and configuration, which complicates backporting the changes completely. As an alternative to forcibly excluding that code in our builds, this PR instead sets the "email.reminder.lifecycle.enabled" property to false, which is a much simpler way to disable the problematic Quartz-related parts for the 2021-01-28 release.
The batch-step-related parts of FINP-7413 have been backported in this PR, though they only introduced some minor setup improvements. If you think that part of the fix is not worth backporting at this time, please let me know.
Note that performing the Tidal and OpDoc setup for running the daily/weekly email reminder jobs is currently beyond …

KFSPTS-21534 Fix email reminder process

---

src/main/java/org/kuali/kfs/module/ar/document/PaymentApplicationAdjustmentDocument.java

I opted to back-port this change as an overlay as there was enough private elements in PaymentApplicationAdjustmentDocument such that it was starting to get confusing to add this change in CuPaymentApplicationAdjustmentDocument.
When reviewing this, the only changes are in the functions getTotalDollarAmount() and anAppaIsBeingAdjusted().  The rest of the file is base code

KFSPTS-21428 back-port FINP 7310

---

src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentAutofixStep.java
src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentNotificationStep.java
src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentNotifierImpl.java
src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentService.java
src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentServiceImpl.java
src/main/java/org/kuali/kfs/kew/web/StuckDocumentsAction.java
src/main/java/org/kuali/kfs/kew/web/StuckDocumentsForm.java
src/main/java/org/kuali/kfs/sys/KFSParameterKeyConstants.java
src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml
src/main/resources/institutional-config.properties
src/main/webapp/jsp/kew/StuckDocuments.jsp

NOTE: There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both PRs are good to go before merging.
This PR backports the relevant FINP-7470 portions from the 2021-04-08 financials patch, to allow the Stuck Document Notification/Autofix jobs to be executed by the batch scheduler instead of a Quartz-only process. For certain areas of the changes that were not practical to backport (such as file removals), the relevant workarounds have been noted in the comments.

KFSPTS-21535 Backport FINP-7470 Stuck Doc job changes

---

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java
src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java
src/main/java/edu/cornell/kfs/sys/batch/service/impl/PaymentWorksVendorLookupCriteriaPurgeServiceImpl.java
src/main/java/edu/cornell/kfs/sys/businessobject/PurgableBusinessObjectInterface.java
src/main/java/edu/cornell/kfs/sys/businessobject/PurgeableBusinessObjectInterface.java
src/main/java/edu/cornell/kfs/sys/businessobject/TableDetailsForPurge.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/TablePurgeRecordsDaoOjb.java
src/main/resources/edu/cornell/kfs/pmw/cu-ojb-pmw.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
src/test/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendorTest.java

This coding change added payment works vendor table to the purge process.  There are a couple of things to note.
I removed a primary key XML tag from cu-ojb-pmw.xml for CU_PMW_VENDOR_T.  PMW_VND_REQ_ID is not a primary key in the database, and there are records in table where PMW_VND_REQ_ID is null.  Without this OJB mapping change, those records could not be purged, as OJB requires primary keys to be filled in to delete a record.
I added a new interface PurgableBusinessObjectInterface to support objects with confidential data elements that should be printed to logs.  There is also the use case where there are more elements on the object than needs to be included in the delete log.

KFSPTS-15376 add payment works vendor to purge process

---

src/main/java/edu/cornell/kfs/krad/service/impl/CuMaintenanceXMLConverter.java
src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountGlobalMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/main/resources/edu/cornell/kfs/module/ld/cu-spring-ld.xml
src/main/resources/edu/cornell/kfs/module/ld/document/datadictionary/overrides/AccountGlobalMaintenanceDocument.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/AccountDelegateGlobalTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/AddWrapperElementTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/ChartTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/Legacy3xIndirectCostRecoveryTypeTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/Legacy5xIndirectCostRecoveryTypeTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyAccountDelegateGlobalTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyChartTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyHigherEducationFunctionTest.xml

This PR updates the maintenance XML conversion process (plus some data dictionary beans) so that older COA module maintenance documents can be successfully opened. The main user story has a comment with a summary of which documents were broken and what fixes were implemented.
Note that this PR only works with base financials COA documents (or CU-customized versions of base COA documents). The conversion of CU-specific COA documents will be handled in a separate user story.

KFSPTS-21725 Fix base COA XML conversion

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyAccountReversionGlobalTest.xml

This PR fixes the XML conversion rules pertaining to Account Reversion Global documents. These appear to be the only Cornell-specific COA documents requiring further XML conversion changes that are not already covered by the existing rules.

KFSPTS-21726 Fix acct reversion XML conversion

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyFiscalYearFunctionControlTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyNonresidentTaxPercentTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyTravelCompanyCodeTest.xml

This PR fixes the XML conversion rules for FP module documents. The comments in the main user story have more details on which documents where checked and what conversions needed to be added.

KFSPTS-21727 Fix FP XML conversion

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyCustomerProfileTest.xml

This PR fixes the maintenance XML conversion for older Customer Profile documents. Of all the maintenance documents in the PDP module, this was the only one that needed to have extra conversion rules added.

KFSPTS-21728 Fix CustomerProfile XML conversion

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyBenefitsCalculationTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyLaborBenefitRateCategoryTest.xml

This PR adds some minor XML conversion changes to fix attempts to open old LD maintenance docs. In the case of the LD module, the only extra thing needed was a minor property name change on the LaborBenefitRateCategory objects.

KFSPTS-21731 Fix LD XML conversion

---

src/main/java/edu/cornell/kfs/krad/service/impl/CuMaintenanceXMLConverter.java
src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyAssetGlobalTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacySecurityModelTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacySecurityModelTest2.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/ReferenceAttributeTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/SkipUnmatchedChildTest.xml

This PR updates the maintenance XML conversion process so that the XML element paths within "reference" attributes will also be converted. That way, if an XML element is renamed or has certain special conversions applied (like the move-to-parent conversion), the updated "reference" path should still lead to the intended value. Without converting the reference paths that need updates, XStream will fail when converting the XML into Java objects.
Some additional conversion rules have been added to address the "reference" issue and a few other issues with at least two docs that are known to be affected: Security Model and Asset Global.

KFSPTS-21968 Fix reference attribute conversion

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java
src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlChunk.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlQuery.java
src/test/java/edu/cornell/kfs/sys/util/CuSqlQueryTest.java

This PR implements the remaining KEW-to-KFS fixes that are needed for our custom maintenance DAO, which is used by our custom Document Requeuer Job. The old code was trying to derive certain table and column names from the JPA annotations on the appropriate objects, but KEW-upgraded KFS no longer has such annotations present. This PR updates the DAO to just hard-code the appropriate table and column names, given that much of the existing constructed SQL was already doing so for many of the other tables and columns. In addition, the setup of the SQL strings and query parameters has been simplified as part of this effort.
The commented-out parts in the maintenance service class have been removed, since a previous PR modified the ActionItemExtension so that the note timestamp now uses the …

KFSPTS-21563 Fix custom maintenance DAO

---

src/main/java/edu/cornell/kfs/kew/routeheader/dao/CuDocumentRouteHeaderDAO.java
src/main/java/edu/cornell/kfs/kew/routeheader/dao/impl/CuDocumentRouteHeaderDAOOjbImpl.java
src/main/java/edu/cornell/kfs/kew/routeheader/service/CuRouteHeaderService.java
src/main/java/edu/cornell/kfs/kew/routeheader/service/impl/CuRouteHeaderServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/edu/cornell/kfs/sys/util/CuOjbUtils.java
src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml

This PR migrates the needed portions of our old Cynergy RouteHeaderService customization to KFS, and updates them for KEW-to-KFS compatibility. Only the custom "getFinalizedDatesForDocumentType" service method needed to be kept and remediated, since the 1099/1042S tax batch job relies upon it.
The old version of the method in CynergyRouteHeaderServiceImpl used JPA and the Kuali Criteria API to retrieve the desired results. Since KFS still uses OJB and has removed the Rice JPA-related code for the KEW-to-KFS upgrade, this PR reimplements the method to use an OJB DAO and OJB report queries instead.

KFSPTS-21560 Update CU RouteHeaderService for KEW upgrade

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/dataaccess/ActionItemNoteDetailDto.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java
src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This PR implements some extra minor revisions to our custom Document Requeuer Job. The bulk of this job's remediation was already dealt with in the KFSPTS-21563 ticket, so this PR just cleans up a few more items:
* Updated one of the main SQL sections to use a sub-query that selects a smaller number of results, which also required adding more table aliases to the SQL accordingly.
* Made some minor tweaks to the printing of ActionItemNoteDetailDto objects, to make their toString() values more readable in the application logs.
* Cleaned up the Spring configuration for the job's main service, such as by injecting the required services into the bean.

KFSPTS-20966 Cleanup for Doc Requeuer Job

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/batch/DocumentReindexFlatFileInputType.java
src/main/java/edu/cornell/kfs/sys/batch/DocumentReindexStep.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This PR fixes a few bugs in the Document Reindexer Job, and also brings the code in line with our current coding practices.
Note that when the job fails, it will now throw an exception instead of returning false. I will create a separate user story to get our other cu-kfs batch jobs to follow this setup, since the KFS Javadocs suggest that throwing an exception is the correct approach for reporting a batch step failure.

KFSPTS-22105 Fix Document Reindexer Job

---

src/main/java/edu/cornell/kfs/krad/service/impl/CuMaintenanceXMLConverter.java
src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyNonresidentTaxPercentTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyRice20SecurityProvisioningTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyRice23SecurityProvisioningTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacySecurityGroupTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/TypedArrayListTest.xml

This PR fixes the maintenance XML conversion for older KSR Security Group and Security Provisioning documents.
Many of these objects' fields had Kuali numeric types that were later converted to regular Java numeric types. To simplify the required XML sub-element unwrapping that resulted from this change, I updated the maintenance XML converter to include a new rule type for doing so. This also required updating an existing unit test case that was relying upon KSR objects, and it allowed for simplifying the conversion of unrelated Nonresident Tax Percent objects.

KFSPTS-21721 Fix KSR maintenance doc conversion

---

src/main/java/edu/cornell/kfs/coa/batch/dataaccess/impl/WorkdayOpenAccountDaoJdbc.java
src/main/java/edu/cornell/kfs/coa/batch/service/impl/CreateWorkdayOpenAccountsCsvServiceImpl.java

This PR makes some minor code cleanup fixes for the 2021-09-28 rebasing efforts. Note that this PR will be merged into the rebasing branch and not into the current kfs-kew-upgrade branch.
There were a couple classes that were still using the old package names for certain classes. This PR fixes them to use the appropriate KEW-upgraded packages.
One small merge conflict had to be resolved on the target branch. The PaymentWorksVendor.xml DD file had to be updated so that the bean removal from KFSPTS-20147 would be handled properly, given that the KEW-to-KFS upgrade had made minor updates to the beans that had been removed.

KFSPTS-22565 Fix changes from 2021-09-28 rebase

---

src/main/java/edu/cornell/kfs/ksr/businessobject/SecurityProvisioningGroupDependentRoles.java
src/main/java/edu/cornell/kfs/ksr/document/validation/impl/SecurityProvisioningGroupRule.java
src/main/java/edu/cornell/kfs/ksr/document/validation/impl/SecurityRequestDocumentRule.java
src/main/resources/edu/cornell/kfs/ksr/businessobject/datadictionary/SecurityProvisioningGroupDependentRoles.xml
src/main/resources/edu/cornell/kfs/ksr/cu-ojb-ksr.xml
src/main/resources/edu/cornell/kfs/ksr/document/datadictionary/SecurityProvisioningMaintenanceDocument.xml

There are two PRs for this change: One in cu-kfs and one in nonprod-sql. Please make sure both are good to go before merging.
This PR adds an "active" flag to the KSR Dependent Roles objects, and adjusts the Provisioning and Security Request business rules to skip some of their validation for inactive ones. This allows for at least some minimal configuration of such objects, whose other fields are normally uneditable after creation (since most or all of their other fields are part of the primary key).

KFSPTS-22284 Allow inactivating KSR dependent roles

---

src/main/java/org/kuali/kfs/kew/messaging/exceptionhandling/DocumentMessageExceptionHandler.java
src/main/java/org/kuali/kfs/ksb/messaging/exceptionhandling/DefaultExceptionServiceImpl.java

This PR contains a trimmed-down version of the FINP-7647 fix, and has the minimal changes needed to get documents to successfully enter EXCEPTION routing. It's also based off of a portion of the FINP-7647 commits instead of the whole set, since some of the commits perform more cleanup that would likely break our current KEW-to-KFS code.
The DocumentMessageExceptionHandler addition/overlay only needed some minor adjustments to compile with the 2021-01-28 KFS code.

KFSPTS-22783 Backport modified variant of FINP-7647 routing fix

---

src/main/java/edu/cornell/kfs/sys/businessobject/actions/CreateDoneBatchFileActionsProvider.java
src/main/java/org/kuali/kfs/fp/document/web/struts/DisbursementVoucherAction.java
src/main/java/org/kuali/kfs/sys/document/web/renderers/GroupTitleLineRenderer.java

Many of the KEW-to-KFS URLs should no longer have "kr" path sections (though some still need them). This PR updates the relevant areas of cu-kfs that should not be using the "kr" path sections anymore:
* The biggest problem was in DisbursementVoucherAction, where the functionals were getting "Our Apologies" messages on DVs because we had forgotten to add some minor KEW-to-KFS changes into our overlay.
* I also noticed an issue where the Favorite Account sections on certain documents were using the wrong KEW-to-KFS URL to load the "add" button image.
* Some of the code for the Create Done Batch File lookup was using an unneeded "kr" part as well. However, its prior setup was still generating the URLs correctly, so this PR just cleans up the unnecessary "kr" usage.

KFSPTS-22970 Fix invalid 'kr' URL usage

---

src/main/java/edu/cornell/kfs/ksr/document/validation/impl/SecurityProvisioningGroupRule.java

This PR simplifies the business rules of the Security Provisioning document, to perform cleaner handling of the property paths in the validation error messages. The addLine validation already adds appropriate path prefixes in the superclass or other related classes, allowing for a simpler handling of prefixes when validating the existing line items.

KFSPTS-22261 Cleanup KSR provisioning validation

---

src/main/java/edu/cornell/kfs/web/filter/CornellLoginFilter.java
src/main/java/org/kuali/kfs/coa/businessobject/lookup/KualiAccountLookupableHelperServiceImpl.java
src/main/java/org/kuali/kfs/krad/maintenance/MaintenanceUtils.java

After review a couple of the NPE email from prod, it looks like this might be happening due to the logged in person is null.   This PR adds logging to the CornellLoginFilter to add more logging if the remote user can not be retrieved.   As apart of this review, please take a look at my note on the parent user story.  If you think anything else should be logged, please let me know.

KFSPTS-23120 add logging to log in filter to report when remote user is not available

---

src/main/java/edu/cornell/kfs/ksr/web/struts/SecurityRequestDocumentAction.java

The current KEW-to-KFS version of the Security Request Document assumes that each doc has a Request Role object for every provisioned group from the related Security Group. However, this prevents older KSR docs from being opened if a new Provisioning Group item was added after the Security Request was created.
This PR fixes the issue above so that if an unmatched Provisioning Group is discovered, the Security Request Document will log the condition instead of throwing an exception, and will omit the Provisioning Group's role from the document. The Cynergy-side KRAD version of the document already has a similar workaround (but without the logging part).

KFSPTS-23138 Fix handling of older KSR documents

---

src/main/java/edu/cornell/kfs/sec/businessobject/lookup/CuAccessSecurityAccountDelegateModelLookupableHelperServiceImpl.java
src/main/resources/edu/cornell/kfs/sec/cu-spring-sec.xml

One of the overrides from the SEC (Access Security) module was interfering with our CuAccountDelegateGlobal customization for the "Account Delegate Global from Model" page. This PR fixes the issue by overriding the problematic lookupableHelperService bean, so that it uses an appropriate CU-specific class with the CuAccountDelegateGlobal feature in place, while still preserving the appropriate SEC module functionality. (As for why this is not a problem in DEV/TEST/PROD, it could be that our overrides were structured to overwrite the problematic SEC one in our before-KEW setup.)
NOTE: I did notice errors like the following in the logs, but such errors already appear to be present in our other environments and they don't appear to be interfering with the Account Delegate Global document: …

KFSPTS-23162 Fix Account Delegate Global from Model page

---

src/main/webapp/scripts/core.js

Certain KFS browser cookies contain commas in the values, even though many cookies are not supposed to contain such content. This PR overlays the JavaScript file that manages the problematic cookies, to replace the commas with underscores instead. This helps prevent some invalid-cookie errors from appearing in the Catalina logs.
NOTE: If the reviewer decides to test this fix locally, you may have to clear your browser cache beforehand so that the browser will correctly use the overlayed JavaScript file.

KFSPTS-22469 Fix KFS cookie error messages

---

src/main/java/edu/cornell/kfs/concur/rest/jsonObjects/ConcurExpenseV3ListItemDTO.java
src/main/java/edu/cornell/kfs/concur/rest/jsonObjects/ConcurRequestV4AmountDTO.java
src/test/java/edu/cornell/kfs/concur/eventnotification/rest/jsonObjects/ConcurExpenseDTOJsonTest.java
src/test/java/edu/cornell/kfs/concur/eventnotification/rest/jsonObjects/ConcurRequestDTOJsonTest.java

Some minor class import tweaks were needed after the 2021-12-20 rebase.
Note that KFSPTS-23465 is the sub-task of KFSPTS-23315. This PR was named after the sub-task because we already have a separate commit for KFSPTS-23315 itself (as a result of last week's rebase).

KFSPTS-23465 Follow-up changes from 2021-12-20 rebase

---

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
src/main/java/org/kuali/kfs/module/ar/document/service/ContractsGrantsInvoiceDocumentService.java
src/main/java/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java
src/main/java/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java
src/main/resources/org/kuali/kfs/module/ar/document/validation/configuration/AccountsReceivableValidators.xml

This is an updated version of the #1239 PR. The only notable difference is that the addition of the "abstract='true'" setting in the bean file should no longer be a part of this changeset, since the change was already implemented for KFSPTS-23633, and was automatically brought into the "kfs-kew-rebase-2022-01-11" branch after performing another rebase from "develop".

KFSPTS-23538 Follow-up changes for 2022-01-11 rebase

---

src/main/java/edu/cornell/kfs/module/ar/service/impl/CuContractsGrantsInvoiceCreateDocumentServiceImpl.java
src/main/java/org/kuali/kfs/module/ar/batch/service/VerifyBillingFrequencyService.java
src/main/java/org/kuali/kfs/module/ar/batch/service/impl/VerifyBillingFrequencyServiceImpl.java
src/main/java/org/kuali/kfs/module/ar/businessobject/BillingPeriod.java
src/main/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriod.java
src/main/java/org/kuali/kfs/module/ar/service/ContractsGrantsInvoiceCreateDocumentService.java
src/main/java/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java

This PR implements Janet's requested CGB enhancements; namely, allowing manual invoices to be invoiced through the current date, and allowing manual invoices to use excluded-from-invoicing Awards. Portions of this code are based off of the KFSPTS-14970 enhancement that was removed by the KFSPTS-21538 work.
This code implements the invoice-through-current-date feature in a different way than the old implementation did. The previous code used a non-persisted field on the Awards to temporarily hold the Creation Process Type enum value, whereas this new code adds the value as an argument to the relevant method signatures. I believe the latter way is a cleaner way of adding the feature back in.
In addition, I noticed that KualiCo's excluded-from-invoicing suspension category gets removed in a …

KFSPTS-23675 Add CGB excluded-award and thru-curr-date features

---

src/main/java/org/kuali/kfs/kim/document/IdentityManagementGroupDocument.java
src/main/java/org/kuali/kfs/sys/identity/DefaultRoleTypeServiceImpl.java

This PR backports KualiCo's FINP-7913 fix that affects KIM Groups and Group Documents. Nicole had discovered an issue related to creating and saving Group Documents in the KEW-upgraded system, and it turns out KualiCo had prepared a fix for it in its 2021-10-14 patch.

KFSPTS-23501 Backport FINP-7913 group document fix

---

src/main/java/org/kuali/kfs/kim/document/rule/AttributeValidationHelper.java
src/main/java/org/kuali/kfs/kim/impl/role/RoleServiceImpl.java

This PR fixes a caching issue that can occur when using Redis. The cache keys for KIM Attributes and Roles have the same pattern, and Redis might not be respecting the differences in named caches, which can cause these objects' cache entries to interfere with each other. To fix the issue, the code that handles caching these objects has been updated to generate keys that are more unique.
Other areas of KFS prepend the method name to the cache keys (or start doing so when the FINP-7391 changes were added), so the affected files have been updated to generate similar keys for consistency. However, the key generation within financials is inconsistent about what separator is placed between the method name and the first attribute, so for now a dash ("-") is being used in the affected code. We …

KFSPTS-23531 Fix Person document edits

---

src/main/java/org/kuali/kfs/coa/service/impl/AccountServiceImpl.java
src/main/java/org/kuali/kfs/coa/service/impl/ObjectCodeServiceImpl.java
src/main/java/org/kuali/kfs/coa/service/impl/OrganizationServiceImpl.java
src/main/java/org/kuali/kfs/coa/service/impl/SubAccountServiceImpl.java
src/main/java/org/kuali/kfs/kew/rule/service/impl/RuleAttributeServiceImpl.java
src/main/java/org/kuali/kfs/kim/document/rule/AttributeValidationHelper.java
src/main/java/org/kuali/kfs/kim/impl/role/RoleServiceImpl.java

This backports changes for FINP-8169 and removes most of changes related to the fix on KFSPTS-23531.
KualiCo missed updating the getAttributeDefinitionByName on AttributeValidationHelper.java so I kept our fix in place. Please let me know if you think we should update the local fix to be more similar to the KualiCo changes. KualiCo created FINP-8210 to fix this method in base code.

KFSPTS-23878 Backport redis fixes on FINP-8169

---

src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java
src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml

We discovered some cases where phone numbers copied from the IWNT to the REQS document were in a format that the REQS docs considered to be invalid. As a minimal-effort workaround, this PR updates the generate-REQS-from-IWNT code so that it automatically alters the appropriate phone numbers to use the format expected by the Requisition.
I also noticed that the needed phone number formatting was already being performed in certain IWNT-to-REQS cases if the IWNT did not fill out the delivery section. This PR expands that formatting to encompass the cases where the IWNT delivery section has been filled out, and also cleans up the coding in the existing phone formatting case.

KFSPTS-23996 Fix IWNT-to-REQS phone number formatting

---

src/test/java/edu/cornell/kfs/sys/service/impl/AwsSecretServiceImplIntegrationTest.java

The test class related to AWS Secrets Manager is running its test methods in parallel at the moment. Some of the methods operate on the same AWS Secret, so there's the potential for data conflicts if such methods execute on different threads. This PR fixes the problem by forcing the class to run its test methods sequentially in a single thread.
I believe the problematic methods are set up in a manner where the run order doesn't matter, so long as they run sequentially. If you think a strict ordering of the methods needs to be enforced here, please let me know and I will add the appropriate JUnit 5 annotations to this class.

KFSPTS-24206 Run AWS Secrets tests in single thread

---

pom.xml
src/main/java/org/kuali/kfs/sys/service/impl/ReportGenerationServiceImpl.java
src/main/resources/org/kuali/kfs/coreservice/config/CoreServiceLocalSpringBeans.xml
src/main/resources/org/kuali/kfs/kim/spring-kim.xml
src/main/webapp/WEB-INF/krad-servlet.xml

This is the KFS-side equivalent of the Spring version upgrade that was recently performed on the Cynergy side.
This PR upgrades KFS to use the latest Spring 5.3.x release, and adds various other changes based on KualiCo's FINP-7916 ticket. The major changes include the following:
* Upgraded to version 5.3.18 of the Spring framework. (Note that certain other Spring JARs that are not part of the basic Spring framework have been left at their current versions.)
* For consistency with the Cynergy changes, the slf4j-api JAR has been updated to a newer version. Most of the rest of KualiCo's FINP-7989 logging-related changes have NOT been added here; we will deal with those when we upgrade to the related financials patch.
* Overlayed ReportGenerationServiceImpl to include the related KualiCo …

KFSPTS-24517 Upgrade to latest Spring 5.3.x release

---

pom.xml

We received a dependabot update for this spring dependency.  I created a Jira ticket for this update to use our standard process

KFSPTS-24684 Update spring-core from 5.3.18 to 5.3.19

---

src/main/java/edu/cornell/kfs/coa/dataaccess/AccountReversionDao.java
src/main/java/edu/cornell/kfs/coa/dataaccess/impl/AccountReversionDaoOjb.java
src/main/java/edu/cornell/kfs/coa/document/CuAccountGlobalMaintainableImpl.java
src/main/java/edu/cornell/kfs/coa/service/AccountReversionService.java
src/main/java/edu/cornell/kfs/coa/service/impl/AccountReversionDetailTrickleDownInactivationServiceImpl.java
src/main/java/edu/cornell/kfs/coa/service/impl/AccountReversionServiceImpl.java
src/main/java/edu/cornell/kfs/coa/service/impl/AccountReversionTrickleDownInactivationServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/resources/edu/cornell/kfs/coa/cu-spring-coa.xml
src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountGlobalMaintenanceDocument.xml

This PR adds and fixes downstream ("trickle down") BO inactivations when an Account (ACCT) or Account Global (GACC) document inactivates an Account BO.
* The ACCT document already had downstream inactivation handling, but the GACC document did not. Some code has been added that will allow the GACC to do so for the Accounts that it inactivates.
* Since we have BO notes enabled for Accounts, some adjustments have been made to the downstream Account Reversion inactivation, so that it will associate the generated notes against the correct objects.
* Based on Dave's feedback on the user story, the notes for farther-downstream Account Reversion "Detail" objects will be skipped for ACCT and GACC documents, due to the duplication of their content and the difficulties with consolidating that …

KFSPTS-24509 Fix downstream inactivation for ACCT and GACC

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/batch/SchedulerServiceFactoryBean.java
src/main/java/edu/cornell/kfs/sys/batch/service/CuSchedulerService.java
src/main/java/edu/cornell/kfs/sys/batch/service/impl/CuJobEntry.java
src/main/java/edu/cornell/kfs/sys/batch/service/impl/CuJobExecutionContext.java
src/main/java/edu/cornell/kfs/sys/batch/service/impl/CuSchedulerServiceImpl.java
src/main/java/edu/cornell/kfs/sys/context/CuKFSInitializeListener.java
src/main/java/org/kuali/kfs/ksb/messaging/exceptionhandling/DefaultExceptionServiceImpl.java
src/main/java/org/kuali/kfs/sys/batch/SchedulerDummy.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
src/main/resources/institutional-config.properties
src/main/webapp/WEB-INF/web.xml

KFS has the ability to retry certain document routing operations if they fail unexpectedly (such as due to an OptimisticLockException), but the code that does so depends on Quartz being enabled. Such processes are failing across our environments because of this, now that the KEW-upgraded code no longer prepares a KSB-related Quartz scheduler. This PR works around the problem by allowing the SchedulerService to handle the appropriate retries, and by customizing the SchedulerService to be usable without Quartz.
This PR also adds some basic code to allow a KFS instance to run batch jobs locally without Quartz, since I was relying upon a particular batch job to recreate the situation that would trigger the routing retries. (The run-local-batch-job feature is disabled by default, but it can be …

KFSPTS-24821 Allow certain processes to run without Quartz

---

src/main/resources/institutional-config.properties
src/main/webapp/WEB-INF/web.xml

This PR updates the idle timeout for KFS to 120 minutes. Please see comments on https://jira.cornell.edu/browse/KFSPTS-25161 for details about why both settings are needed

KFSPTS-25148 increase KFS idle timeout to 120 minutes

---

src/main/webapp/WEB-INF/tags/ksr/securityRequestPrincipal.tag
src/main/webapp/WEB-INF/tags/ksr/securityRequestRole.tag
src/main/webapp/WEB-INF/tags/ksr/securityRequestRoleQualifications.tag
src/main/webapp/WEB-INF/tags/ksr/securityRequestTabs.tag
src/main/webapp/jsp/ksr/SecurityRequestDocument.jsp

Security Request documents were relying upon a request-level "readOnly" variable to handle the read-only state on the downstream KSR tags, but that was causing other fields (like the note text field) to unexpectedly become read-only on uneditable documents. These documents were also missing the tag that adds the superuser tab, along with a few other misc. tags. This PR adds fixes for both of those issues.

KFSPTS-24770 Fix KSR read-only and superuser handling

---

src/main/java/edu/cornell/kfs/module/purap/document/service/CuB2BShoppingService.java
src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuB2BShoppingServiceImpl.java
src/main/java/edu/cornell/kfs/module/purap/service/JaggaerRoleService.java
src/main/java/edu/cornell/kfs/module/purap/service/impl/JaggaerRoleServiceImpl.java
src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml

This PR adjusts the creation of the Jaggaer Login XML so that it allows for specifying an arbitrary number of roles. It also adds some minimal code to allow deriving the appropriate roles based on a specified JaggaerRoleSet, though the full implementation of that functionality is being deferred to a future user story. The JaggaerRoleSet-based derivation is not actively used by the current code here.
Our original plan was to create custom JAXB DTOs for building the Login CXML in a cleaner fashion, but that approach required creating an unexpectedly large number of DTOs. After further discussion with the team, we decided to instead make the appropriate modifications to the existing string-concatenation-based process, and we'll handle converting this to a cleaner setup once KualiCo …

KFSPTS-24959 Allow for adding multiple roles to Jaggaer CXML

---

src/main/java/edu/cornell/kfs/module/purap/identity/CuPurapKimAttributes.java
src/main/resources/edu/cornell/kfs/module/purap/businessobject/datadictionary/CuPurapKimAttributes.xml

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
While preparing the Jaggaer KIM role SQL, I had discovered that some missing Data Dictionary configuration was preventing the Jaggaer Role attribute from displaying properly on the Permission lookup. This PR adds the needed DD beans to fix that, and bundles it with the main KIM-role-related SQL changes for that user story.
If you think this fix should be separated into a separate ticket, please let me know.

KFSPTS-25158 Fix display of Jaggaer roles in KIM

---

src/main/resources/edu/cornell/kfs/module/purap/businessobject/datadictionary/JaggaerRoleLinkMapping.xml
src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/JaggaerRoleLinkMappingMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/JaggaerRoleLinkMappingMaintenanceDocument.xml

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both PRs are good to go before merging.
This PR adds a new maintenance document for adding/editing Jaggaer Role Link Mapping BOs, and also adds the related lookup and inquiry screens.
The lookup and inquiry metadata has generally been structured to use the newer frameworks, but for consistency with KualiCo's other converted BOs, the new inquiry has been configured to allow for both the old and new setup. We can make further revisions in the future once KualiCo fully retires the old framework, but if you think we should not use the old inquiry framework here at all, please let me know.

KFSPTS-25511 Add document for Jaggaer link mapping

---

src/main/java/edu/cornell/kfs/concur/batch/ConcurEventNotificationProcessingStep.java
src/main/java/edu/cornell/kfs/concur/service/ConcurReportsService.java
src/main/java/edu/cornell/kfs/concur/service/impl/ConcurReportsServiceImpl.java
src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml

This PR fixes our ongoing Concur Event Notification Job (CN-07-01) problems by reconfiguring it to use Concur's newer OAuth2 setup.
To minimize the number of required code changes, I added a variable to ConcurReportsService to temporarily store the appropriate token. This variable will get populated when CN-07-01 starts and will get cleared when CN-07-01 finishes.
I'm currently only able to test out a portion of the changes locally, to prevent accidental updates to the failed events queue. I was at least able to confirm that the failed events queue can be successfully queried using the newer OAuth2 token. The rest of the process might not be fully testable in a non-PROD system; we may have to move things into PROD to verify that the Concur workflow updates to expense reports and travel …

KFSPTS-25823 Update old Concur event job to use new authentication

---

src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/edu/cornell/kfs/sys/businessobject/ISOCountry.java
src/main/java/edu/cornell/kfs/sys/businessobject/ISOFIPSCountryMap.java
src/main/java/edu/cornell/kfs/sys/dataaccess/ISOFIPSCountryMapDao.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/ISOFIPSCountryMapDaoOjb.java
src/main/java/edu/cornell/kfs/sys/exception/ManyFIPStoISOMappingException.java
src/main/java/edu/cornell/kfs/sys/exception/ManyISOtoFIPSMappingException.java
src/main/java/edu/cornell/kfs/sys/exception/NoFIPStoISOMappingException.java
src/main/java/edu/cornell/kfs/sys/exception/NoISOtoFIPSMappingException.java
src/main/java/edu/cornell/kfs/sys/service/ISOFIPSConversionService.java
src/main/java/edu/cornell/kfs/sys/service/impl/ISOFIPSConversionServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/ISOCountry.xml
src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/ISOFIPSCountryMap.xml
src/main/resources/edu/cornell/kfs/sys/cu-ojb-sys.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
src/main/resources/edu/cornell/kfs/sys/document/datadictionary/ISOCountryMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/datadictionary/ISOFIPSCountryMapMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/ISOCountryMaintenanceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/ISOFIPSCountryMapMaintenanceDocument.xml

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both PRs are good to go before merging.
This PR adds maintenance documents for adding/editing the generic ISO countries as well as one for mapping between these generic ISO countries and the existing FIPS countries.  The new KualiCo framework was used for these maintenance documents. The access security from the existing (FIPS) country maintenance document was use for these document's so that the same functional users would have access to both the FIPS and ISO versions.
Active indicators were added to both generic ISO country maintenance documents. The current PaymentWorks version of this country mapping does not have/use active indicators so that nuance was not included in the generic version of the service …

KFSPTS-25260: Generic ISO-to-FIPS Country code conversion mod.

---

src/main/java/edu/cornell/kfs/sec/document/CuSecurityModelMaintainableImpl.java

There seems to be a bug on the Security Model document, where the duplicate-Model-Definition check fails unexpectedly when multiple such BOs have both the same Definition ID and the same default null/uninitialized primary key (Model Definition ID). This PR adds a fix that auto-populates the latter ID when one of those BOs is newly added on the document.
We would like to notify KualiCo of this issue so that they can potentially fix it on their end, but our custom fix should be enough in the meantime.

KFSPTS-25728 Fix Security Model multi-Definition issue

---

src/main/webapp/WEB-INF/tags/ksr/securityRequestRole.tag
src/main/webapp/jsp/ksr/SecurityRequestWizard.jsp

This PR re-labels the security request wizard button from "submit" to "continue" as requested on KFSPTS-25919.
Cathy's major concern on KFSPTS-25330 was that there were user confusion as to what KIM role each checkbox was associated with .  Cathy thought move the role name under neath the horizontal line would help that greatly.  This PR does that, in addition to some other formating changes Chad H added on an early attempt to implement this fix

KFSPTS-25330 KFSPTS-25919 improve KSR

---

pom.xml

This PR excludes some conflicting dependencies that somehow went unnoticed during the 11/17/2021 patch preparation.
The biggest culprits were the Guava JAR, the Netty JARs and the Spring-related JARs. There are still some HttpClient-related JARs that have not been cleaned up yet, but their version numbers only seem to defer at the patch-number level and they don't interfere with launching KFS locally. To keep DEV moving forward, I would like to defer the HttpClient cleanup to another user story unless others disagree.

KFSPTS-26287 Fix critical conflicting dependencies in 2021-11-17 patch

---

src/main/java/edu/cornell/kfs/ksr/datadictionary/validation/PrimaryDepartmentCodeValidationPattern.java
src/main/resources/edu/cornell/kfs/ksr/cu-ksr-resources.properties
src/main/resources/edu/cornell/kfs/ksr/document/datadictionary/KSRBaseTypes.xml
src/main/resources/edu/cornell/kfs/ksr/document/datadictionary/SecurityRequestDocument.xml

This is an alternative version of the #1334 fix that addresses the underlying cause of the reported problem. It appears we already had some KSR Data Dictionary configuration for validating the Primary Department Code, but it was configured for KRAD-UI-based document validation instead. This PR updates the configuration to work with the KNS-based setup, and also adjusts it to fit with how KualiCo has configured similar validation beans.

KFSPTS-25850 Fix Dept Code validation on KSR docs

---

src/main/java/edu/cornell/kfs/module/purap/batch/JaggaerGenerateContractPartyCsvStep.java
src/main/java/edu/cornell/kfs/module/purap/batch/dataaccess/JaggaerUploadDao.java
src/main/java/edu/cornell/kfs/module/purap/batch/dataaccess/impl/JaggaerUploadDaoJdbc.java
src/main/java/edu/cornell/kfs/module/purap/batch/service/JaggaerGenerateContractPartyCsvService.java
src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlChunk.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlQueryPlatformAwareDaoBaseJdbc.java
src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml
src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateContractPartyCsvServiceImplTest.java
src/test/java/edu/cornell/kfs/sys/util/CuSqlQueryTest.java

This PR contains the changes needed to use parameterized SQL in JaggaerUploadDaoJdbc.  I fixed the logging problem I had mentioned before.
If you agree with this approach, I would like to create a follow up user story to update DocumentMaintenanceDaoJdbc to extend CuSqlQueryPlatformAwareDaoBaseJdbc so it can make use of various shared methods in the new abstract class.

KFSPTS-26048 parameterize SQL created in JaggaerUploadDaoJdbc

---

src/main/java/edu/cornell/kfs/concur/ConcurParameterConstants.java
src/main/java/edu/cornell/kfs/concur/batch/service/ConcurBatchUtilityService.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurAccessTokenV2ServiceImpl.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImpl.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceImpl.java
src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
src/main/resources/institutional-config.properties
src/test/java/edu/cornell/kfs/concur/ConcurTestConstants.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurAccessTokenV2GeolocationTest.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurAccessTokenV2ServiceImplTest.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceImplTest.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/MockConcurRequestV4ServiceEndpoint.java
src/test/java/edu/cornell/kfs/concur/util/MockConcurUtils.java
src/test/java/edu/cornell/kfs/concur/web/mock/MockConcurAuthenticationEndpointController.java

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
Concur's API documentation states that when a new access token is retrieved, a new geolocation URL might also get returned, not just a new refresh token. This PR updates our newer Concur API calls to always use the most recent geolocation.
The geolocation is stored in its own separate parameter. The other parameters for storing the newer endpoint URLs are now treated as relative URLs instead. The new code will concatenate the geolocation with the relative URL path to form the full API URL for the service call.
In the unlikely event that a malformed or malicious URL gets returned from Concur, this PR adds some basic regex-based validation of any newly-acquired geolocations. …

KFSPTS-26252 Add handling of Concur geolocation URLs

---

src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountDelegateGlobalMaintenanceDocument.xml

This PR reintroduces an Account Delegate Global bean override that was accidentally removed by the merge of the 01/05/2022 financials patch to the master branch.
Note that this PR will merge the changes into an emergency fix branch that will be used for creating an off-cycle KFS PROD WAR file. The emergency branch was based off of the "kfs-prod-2022-12-04-patch" tag.

KFSPTS-26887 Fix Account Delegate Global setup

---

src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxSqlUtils.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java
src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPdpBuilder.java
src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml

NOTE: I'm still wrapping up local validation of this. Please don't merge until I add a comment indicating it's safe to do so.
One of the recent KualiCo patches renamed the PDP Customer Profile's Chart field to Campus instead, but our custom Tax Processing Job did not get updated yet to compensate for that. This PR fixes the issue by making the following changes:
* In the PDP data query that still needs to reference the renamed field, that section and the related areas have been updated to correctly reference the new Campus field.
* In the section that validates the account and org data from the PDP transaction, that section has been updated to derive the Chart from the payment's accounting details instead of from the renamed field. (The functionals have requested this change; see the user …

KFSPTS-26979 Fix tax PDP handling for chart-to-campus rename

---

pom.xml

The dependabot update to cxf 3.4.10 is failing with a compile time problem where ehcache classes could not be found.  Upon reviewing the POM, it looks like we inherited ehcache from KualiCo.  I tried excluding ehcache from KualiCo jars and adding a new dependency for ehcache (2.10.6), the same version as we had pulled in.  I also found cxf-rt-security had ehcache 3.8.1, which was also excluded.
I am not sure if this is the best solution to doing this but it seems to work out.  Please let me know if you think there is a better approach.

KFSPTS-26956 update CXF from 3.3.10 to 3.4.10 and reconfigure how ehcache is setup in pom file

---

src/main/resources/edu/cornell/kfs/tax/batch/Default1099TaxOutputDefinition.xml

This PR is ready for review, it adjusts the header row values for the 1099 MISC.  Local validation shows the NEC file header is not altered.  I was expecting to have to update cu-kfs java code to be in line with changes made to the XML, but it doesn't look like it is required.

KFSPTS-27104 adjust 1099 header name box numbers

---

src/main/java/edu/cornell/kfs/coa/document/validation/impl/AccountExtensionRule.java
src/main/resources/CU-ApplicationResources.properties

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
This PR removes our custom Benefit Rate Category validation from the Account doc, because base financials code now has equivalent validation in place. The appropriate base validation will occur when the related boolean parameter is enabled (which is already enabled across our environments). Our addition of the error message property has also been removed since it seems to duplicate the one found in base code.
Note that the parameter referenced in the error message is actually supposed to have an "_IND" suffix. I will create a follow-up user story to report that naming discrepancy back to KualiCo.

KFSPTS-22413 Remove custom Benefit Rate Category rules

---

src/main/webapp/WEB-INF/tags/module/purap/iWantItems.tag

The 2022-04-13 financials upgrade removed the expanded textarea feature from KFS, but we accidentally forgot to remove the references to it from the IWNT document. This PR removes the expanded textarea icons from the IWNT document so that it will render successfully once more. The "wrap-break-word" CSS class has also been added, for consistency with similar removals of this feature from other documents.

KFSPTS-27518 Remove expanded textarea from IWNT

---

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java
src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/CuExtractPaymentServiceBase.java

There are PRs for this change in cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
This PR adjusts the Check/ACH extraction process so that it will analyze a CU-specific parameter to determine whether to use ISO 20022 output. The base financials parameter normally controls both the extraction output and the business rules validation on certain docs, but with this change we can keep those two scopes separated until we finish the ISO 20022 migration. We intend to remove the CU-specific parameter after the ISO 20022 transition is complete.
Note that, due to how some of the method visibility has been set up in base code, I added an intermediate abstract helper class to assist with some of the configuration. The new class should help keep some of the customized code …

KFSPTS-26954 Add CU parm to control ISO 20022 output

---

src/main/java/org/kuali/kfs/kew/actionrequest/service/impl/ActionRequestServiceImpl.java
src/main/java/org/kuali/kfs/kew/actions/LogDocumentActionAction.java
src/main/java/org/kuali/kfs/kew/api/document/DocumentRefreshQueue.java
src/main/java/org/kuali/kfs/kew/documentoperation/web/DocumentQueueOperationAction.java
src/main/java/org/kuali/kfs/kew/impl/document/DocumentRefreshQueueImpl.java
src/main/java/org/kuali/kfs/kew/impl/stuck/StuckDocumentServiceImpl.java
src/main/java/org/kuali/kfs/module/purap/document/web/struts/RequisitionAction.java
src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml

This PR backports the FINP-9050 feature that allows certain special document actions (like a manual doc requeue) to add a message to the Route Log. This also required backporting a portion of the FINP-8777 fix, so that the messages would actually get written to the Route Log. (Much of FINP-8777 consisted of code formatting changes, so I only backported the part that contains the critical `saveActionTaken()` call.)
Note that FINP-9050's new REQS message in `RequisitionAction` contained a minor typo, which has been fixed in our overlay for the moment. Furthermore, during my testing I also discovered an existing issue, where document types with nested "split" nodes cannot be exported successfully. (The latter was likely caused by FINP-7919 from the 2022-01-12 patch.) I will create follow-up …

KFSPTS-27595 Backport FINP-9050 and FINP-8777 route log fixes

---

src/main/java/edu/cornell/kfs/concur/ConcurConstants.java
src/main/java/edu/cornell/kfs/concur/ConcurKeyConstants.java
src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceImpl.java
src/main/java/edu/cornell/kfs/concur/businessobjects/ConcurEventNotificationProcessingResultsDTO.java
src/main/resources/edu/cornell/kfs/concur/cu-concur-resources.properties
src/test/java/edu/cornell/kfs/concur/ConcurTestConstants.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceImplTest.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceUpdateRequestTest.java
src/test/java/edu/cornell/kfs/concur/batch/service/impl/fixture/RequestV4PersonFixture.java
src/test/java/edu/cornell/kfs/concur/web/mock/MockConcurRequestV4WorkflowController.java

This is an updated version of the declined #1376 changes regarding the new Concur API workflow handling. As was discussed in the user story, the new version of this code will always approve incoming Travel Requests, even if their accounts fail validation.
In addition, this PR will add an extra approve-anyway warning to the validation messages if a Request fails account validation. The message is not being added to the workflow action itself, but it will be added to the Event Notification V2 report.
Please let me know if you have any questions or concerns about this updated approach.

KFSPTS-26275 Add CNCR Request V4 workflow handling

---

src/main/java/edu/cornell/kfs/kew/api/document/CuDocumentRefreshQueue.java
src/main/java/edu/cornell/kfs/kew/impl/document/CuDocumentRefreshQueueImpl.java
src/main/java/edu/cornell/kfs/sys/dataaccess/DocumentMaintenanceDao.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java
src/main/java/edu/cornell/kfs/sys/service/DocumentMaintenanceService.java
src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java
src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml

This PR updates our restore-notes-after-requeue functionality so that it also applies to regular document requeues, not just those from the Document Requeuer Job. For the moment, I've structured things so that the Document Requeuer Job should still be runnable. Once we're ready to remove that batch job for good, we can simplify the related code in a future ticket.

KFSPTS-27615 Restore action notes after any doc requeue

---

pom.xml

This PR updates cu-kfs to use a newer version of the related ISO 20022 library; specifically, the version that base financials upgraded to for its 2022-08-17 patch. We can potentially remove this change in the future once we've upgraded to the 2022-08-17 patch or later.

KFSPTS-26964 Upgrade ISO 20022 library version

---

pom.xml
src/main/java/edu/cornell/kfs/module/purap/document/dataaccess/impl/CuPaymentRequestDaoOjb.java

Please do ***NOT*** merge this yet! If these changes move forward mostly as-is, then we'll need to coordinate with DevOps to add another system property setting when migrating to our various KFS environments. It would also be helpful to test this in the sandbox environment first.
This PR upgrades the Oracle JDBC driver to the latest stable one that's compatible with our Oracle version. Note that, in order for `java.sql.Date` objects to work properly with the new driver, we need to add the following JVM property (as previously noted on the user story):
```
-Doracle.jdbc.DateZeroTime=true
```
This PR also removes a temporary workaround from the Payment Request creation process, where we were manually converting a `java.time.LocalDate` into a `java.sql.Date`. Such a conversion is not …

KFSPTS-18715 Upgrade database driver

---

src/main/java/org/kuali/kfs/kim/impl/role/RoleServiceBase.java
src/main/java/org/kuali/kfs/kim/impl/role/RoleServiceImpl.java

It appears that the KimApiServiceLocator is not finding the KimTypeInfoService when the abstract class is requesting it.
Adding a call in extended class (RoleServiceImpl) when the service class (KimTypeInfoService) value is set to also assign that same reference value to the service attribute of the same name in the abstract super class (RoleServiceBase) fixes this issue. Having the error logging messages in the abstract class should help to identify any future fixes should they be necessary.
Due to base code Financials patch release 2022-07-13 being on the develop branch already, that base code version of our customized files was used for comparison when preparing this fix.

KFSPTS-28071: Fix KSR documents routing to exception.

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/edu/cornell/kfs/sys/exception/ManyFIPSCountriesForNameException.java
src/main/java/edu/cornell/kfs/sys/exception/ManyISOCountriesForNameException.java
src/main/java/edu/cornell/kfs/sys/exception/NoFIPSCountriesForNameException.java
src/main/java/edu/cornell/kfs/sys/exception/NoISOCountriesForNameException.java
src/main/java/edu/cornell/kfs/sys/service/CountryService.java
src/main/java/edu/cornell/kfs/sys/service/ISOCountryService.java
src/main/java/edu/cornell/kfs/sys/service/ISOFIPSConversionService.java
src/main/java/edu/cornell/kfs/sys/service/impl/CountryServiceImpl.java
src/main/java/edu/cornell/kfs/sys/service/impl/ISOCountryServiceImpl.java
src/main/java/edu/cornell/kfs/sys/service/impl/ISOFIPSConversionServiceImpl.java
src/main/java/edu/cornell/kfs/sys/service/impl/ISOFIPSCountryMapServiceImpl.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

This PR updates the ISO 20022 extraction so that it will properly convert country names and FIPS country codes into ISO country codes. As per the user story's requirements and comments, if a unique mapping doesn't exist or if the code/name is blank, then country code "ZZ" (Unknown) will be used by default.
I also added some helper methods that will be needed when we eventually perform the full FIPS-to-ISO transition at some future date. Some of those methods are not fully implemented yet since their functionality is not needed at this time.

KFSPTS-26963 Improve country handling for ISO 20022

---

src/main/resources/edu/cornell/kfs/fp/document/workflow/DisbursementVoucherDocument.xml
src/main/resources/edu/cornell/kfs/fp/document/workflow/GeneralLedgerTransferDocument.xml
src/main/resources/edu/cornell/kfs/module/ar/document/workflow/CustomerCreditMemoDocument.xml
src/main/resources/edu/cornell/kfs/module/ar/document/workflow/CustomerInvoiceDocument.xml
src/main/resources/edu/cornell/kfs/module/ar/document/workflow/CustomerInvoiceWriteoffDocument.xml
src/main/resources/edu/cornell/kfs/module/ld/document/workflow/BenefitExpenseTransfer.xml
src/main/resources/edu/cornell/kfs/module/ld/document/workflow/SalaryExpenseTransfer.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PaymentRequestDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderAmendmentDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderCloseDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderPaymentHoldDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderRemovePaymentHoldDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderReopenDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderRetransmitDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderSplitDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderVoidDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/RequisitionDocument.xml
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/VendorCreditMemoDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/AuxiliaryVoucherDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/BudgetAdjustmentDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/DistributionOfIncomeAndExpenseDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/IndirectCostAdjustmentDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/InternalBillingDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/NonCheckDisbursementDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/PreEncumbranceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/ProcurementCardDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/TransferOfFundsDocument.xml

This PR updates the appropriate doc type workflow XML files to include KualiCo's ObjectCode routing feature. Also, certain documents that don't necessarily have this routing (such as some of the PO variants) have still been updated to at least include the new app doc statuses related to this.
Note that these changes only affect the workflow XML files, which need to be manually ingested into KFS to have any effect. The changes do NOT affect runtime code, data dictionary configuration, OJB configuration, etc.
If the KualiCo patch gets merged prior to this PR, then I would like to rebase this feature branch afterwards.

KFSPTS-24999 Add ObjectCode routing to doc types

---

src/main/java/edu/cornell/kfs/pdp/CUPdpConstants.java
src/main/java/edu/cornell/kfs/pdp/CUPdpKeyConstants.java
src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PaymentUrgency.java
src/main/java/edu/cornell/kfs/pdp/service/CuPaymentDetailService.java
src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentDetailServiceImpl.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/CheckExtractTypeContext.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/ExtractTypeContext.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java
src/main/resources/edu/cornell/kfs/pdp/cu-pdp-resources.properties
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
src/main/resources/institutional-config.properties

This is ready for initial review, but I wanted to perform some more testing before moving this out of the Draft state.
This PR makes the following changes that are required for the ISO 20022 conversion and the associated Cornell-side processing:
* Immediate Check payments will now be separated into a distinct ISO 20022 file. The resulting file will eventually be used by Cornell for printing immediate Checks, and it will be also sent to the bank to notify them of our locally-printed Checks.
* The queries for PDP Check payments can now be limited based on the immediate processing flag. Some additional overlay changes have also been introduced, to help distinguish between the immediate and non-immediate Check processing when generating the ISO 20022 files.
* To support the needs of our local …

KFSPTS-28624 Add ISO 20022 Immediate Check handling

---

src/main/java/edu/cornell/kfs/pdp/CUPdpConstants.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java

This PR adds a few changes requested by the new bank:
* The file/message ID in the ISO 20022 file has to be unique over a period of a few weeks, as required by the bank. Base financials is just using the PDP Process ID as the file/message ID, resulting in both the Check file and the ACH file (and our custom Immediate Check file) having the same ID for a given PDP Process. To satisfy the uniqueness requirements, this PR appends an extra suffix to the file/message ID based on the types of transactions being processed.
* The bank does not want us to add the Creditor Reference Information section if the payment does not have a related Purchase Order. This PR updates the relevant code so that the section will only be included when the payment specifies a PO number.

KFSPTS-28680 Update ISO 20022 msg ID and creditor handling

---

src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml

This PR fixes a minor misconfiguration on one of our overridden beans. The change is necessary to get the e-SHOP integration working again for the 2022-10-19 financials upgrade.
We might be able to remove the bean override altogether, since I don't think it's introducing anything new on the cu-kfs side anymore. If you think it makes sense to remove it now instead of in a future story, please let me know.

KFSPTS-29020 Fix bean setup affecting e-SHOP

---

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java
src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java

This PR updates the Check side of the PDP Extract process so that the legacy/proprietary Check XML will still get generated when creating ISO 20022 XML. That way, we can continue using the proprietary XML to handle Immediate Checks locally until we're fully ready to use the ISO 20022 XML for our local Checks.
Note that the FastTrack Check files are not needed for local Check printing, so they won't get generated when running in ISO 20022 mode. Also, these changes should only affect the Check file side of the PDP Extract; the ACH side should remain as-is.

KFSPTS-28621 Allow creating legacy Check XML while in ISO 20022 mode

---

src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java

This PR fixes the ISO 20022 files so that the Invoice/Credit Note indicator will get filled in on payments sourced from PDP feeds. It also allows for placing the KFS doc number into the invoice number field when necessary, similar to (but not exactly like) the functionality in our FastTrack file generation code.

KFSPTS-29283 Fix missing Doc Reference Info for ISO 20022

---

src/main/resources/edu/cornell/kfs/module/ld/document/workflow/BenefitExpenseTransfer.xml
src/main/resources/edu/cornell/kfs/module/ld/document/workflow/SalaryExpenseTransfer.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/BudgetAdjustmentDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/DistributionOfIncomeAndExpenseDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/IndirectCostAdjustmentDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/NonCheckDisbursementDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/PreEncumbranceDocument.xml
src/main/resources/edu/cornell/kfs/sys/document/workflow/TransferOfFundsDocument.xml

When we added the Object Code routing to our documents locally, some of the doc type XML files left out the "Parallel" routing indicator on several route nodes, causing them to default to "Sequential" routing and to mess up the route behavior in Production. This PR fills in the gaps by updating the doc type XML to include the "Parallel" routing indicator on the appropriate nodes.
Note the following:
* There were no changes to runtime code or config files, only to the workflow XML files that we're keeping in the codebase for reference.
* The associated SQL changes will automatically update the relevant route nodes at the database level, so that we don't have to ingest the XML at this time. The changes were made on the PR below (which has already been merged):
* …

KFSPTS-29360 Fix parallel routing config on route nodes

---

src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java
src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml

This PR improves the country handling in the ISO 20022 extraction. If a transaction has a blank country code but still appears to reference a domestic state code and zip code, then the "US" country code will be used in the file entry. Otherwise, the "ZZ" (Unknown) code will be used instead.
Note that, similar to KualiCo's `PostalCodeValidationServiceImpl` class, the updated code is using a `ZipcodeValidationPattern` instance to assist with the zip code pattern checking.

KFSPTS-29464 Improve ISO 20022 blank country handling

---

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java

There are PRs for this in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
This PR makes the following improvements to the ISO 20022 extraction:
* Modifies the execution/extraction date on the ACH file to be 1 day later than the current date.
* Modifies the Check file so that the "Forms Code" on the Check entries is now derived from a parameter, rather than being hard-coded.

KFSPTS-29497 Improve handling of ISO 20022 ACH dates and Check forms

---

src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuEscapeHandler.java
src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java
src/test/java/edu/cornell/kfs/pdp/batch/service/impl/CuEscapeHandlerTest.java

This PR makes a few additional changes to the ISO 20022 file generation:
* Sets up a custom `EscapeHandler` implementation (used by the relevant ISO 20022 Java library) that performs the char escaping (or non-escaping) requested by the new bank. The new class also works around a bug in the library's code that could cause quotes to be duplicated in the ISO 20022 file output.
* Adjusts the file generation to use the Java library's standard means of controlling the XML namespacing in the file output, rather than using KualiCo's string substitution hack.

KFSPTS-26965 Fix ISO 20022 XML namespacing and char escaping

---

src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java
src/main/webapp/WEB-INF/tags/module/purap/iWantAccountInfo.tag
src/main/webapp/WEB-INF/tags/module/purap/iWantItems.tag
src/main/webapp/scripts/module/purap/iWantDoc.js

This PR introduces a few fixes to the IWant Document:
* Fixed a bug that was preventing the Requestor's address from auto-updating when entering a different Requestor NetID.
* Fixed an issue where Requestor or Deliver To addresses could end up with the word "null" on address lines containing null data. (Note that this only affects the auto-population of addresses from KIM data; any pre-stored IWNT "default" delivery addresses are beyond the scope of this PR.)
* Fixed some bugs that were interfering with real-time updates to Item and Account totals on the IWNT form. Some cases required specifying the `readOnlyAlternateDisplay` attribute on the relevant tags, to prevent KFS from writing the initial displayed value to a location that is not affected by the `setRecipientValue()` function.

KFSPTS-27527 Fix handling of IWNT amounts and addresses

---

src/main/java/org/kuali/kfs/pdp/batch/service/impl/Iso20022FormatExtractor.java

The new bank doesn't want the check stubs to contain newlines, so this PR changes the ISO 20022 process to replace them.
The current solution doesn't string-normalize the text; if you have a strong opinion about adding that, please let me know.

KFSPTS-29602 Replace newlines in ISO 20022 check stubs

---

src/main/resources/edu/cornell/kfs/module/purap/document/workflow/PurchaseOrderAmendmentDocument.xml

I have made changes to the route node logic in the document type XML.  I wasn't sure if I should remove the category statuses "Disapproved C and G" and "Awaiting C and G Approval".  I was leaning toward not to avoid search related problems, but I am not certain.
The user story references some responsibilities.  Should I add sub tasks for Nicole to deactivate those?

KFSPTS-28557 remove Award node for purchase order amendment documents

---

src/main/java/edu/cornell/kfs/module/purap/document/CuPurchaseOrderAmendmentDocument.java

Remove code in the method CuPurchaseOrderAmendmentDocument.answerSplitNodeQuestion corresponding to the split node removal in https://github.com/CU-CommunityApps/cu-kfs/pull/1504

KFSPTS-29735 Removed unused split node

---

pom.xml

This PR and a new log4j dependency log4j-layout-template-json and  updates log4j to version 2.21.1 per @dp65  needs to DataDog.
We were previously at 2.18 so this update is only a few minor patches newer.  Also KualiCo is 2.20: https://github.com/KualiCo/financials/blob/master/pom.xml .  So it seems safe to do this update.

KFSPTS-29958 update log4j to 2.21.1 and add log4j-layout-template-json

---

src/main/java/edu/cornell/kfs/kew/impl/document/CuDocumentRefreshQueueImpl.java
src/main/java/edu/cornell/kfs/sys/dataaccess/ActionItemNoteDetailDto.java
src/main/java/edu/cornell/kfs/sys/dataaccess/DocumentMaintenanceDao.java
src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java
src/main/java/edu/cornell/kfs/sys/service/DocumentMaintenanceService.java
src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java
src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

The #1524 PR accidentally removed a customization that auto-restores action list notes after a document gets requeued. This PR reintroduces the needed customization, while still excluding the old Doc Requeuer Job feature that #1524 intended to remove.

KFSPTS-30352 Reinstate action note restoration feature

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountDelegate.xml

#1526 initially reduced the Account Delegate multi-value lookup limit to 10000, and then #1529 reduced it to 5000. However, we recently discovered an issue where if the GADI document's delegates span more than 1000 unique accounts, then one of the downstream database queries will fail due to an IN clause being too large. This PR fixes the issue by reducing that multi-value lookup's limit even further; namely, down to 1000 (our DB's current max size for SQL IN clauses).

KFSPTS-30416 Reduce delegate lookup limit to 1000

---

src/main/java/edu/cornell/kfs/fp/CuFPConstants.java
src/main/java/edu/cornell/kfs/fp/CuFPKeyConstants.java
src/main/java/edu/cornell/kfs/fp/CuFPParameterConstants.java
src/main/java/edu/cornell/kfs/fp/batch/CreateAccountingDocumentReportItem.java
src/main/java/edu/cornell/kfs/fp/batch/service/CreateAccountingDocumentReportService.java
src/main/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentReportServiceImpl.java
src/main/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/fp/businessobject/CreateAccountingDocumentFileEntry.java
src/main/java/edu/cornell/kfs/fp/exception/DuplicateCreateAccountingDocumentFileException.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/fp/cu-ojb-fp.xml
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
src/test/java/edu/cornell/kfs/fp/CuFPTestConstants.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestBase.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestDuplicates.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentListWrapperFixture.java

There are PRs for this in both cu-kfs and nonprod-sql. Please make sure both PRs are good to go before merging.
Also, I'm waiting for functional feedback on some of the new messages introduced by these changes. Please don't merge until after I hear back about any needed wording changes.
This PR allows the Create Accounting Documents Job to prevent the processing of files that were already handled in a previous run; such functionality is controllable by a new parameter. I believe I've implemented the requirements noted in the user story, but please let me know if I missed anything. (Adding the new table to the Purge Job will be handled in a follow-up user story, as noted in the ticket.)
I also fixed a pre-existing bug that was preventing certain error information from being displayed …

KFSPTS-20442 Add create-acct-doc duplicate file checks

---

src/main/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentReportServiceImpl.java

This PR makes adjustments to how some of the error reports are formatted:
* If a document within the file fails for certain non-business-rule reasons (such as a not-authorized exception when creating the KFS doc), the report will now use the regular layout instead of one of the total-file-failure layout. The problematic docs will be noted in the appropriate sections.
* If a file fails for certain header validation reasons (such as an invalid report email address), the related total-file-failure layout will now attempt to avoid outputting the error message twice. The #1535 changes fixed a bug that was preventing some file-level error messages from being printed to the reports, but this had the side effect of potentially printing some of the messages twice. (The upstream code prepares a …

KFSPTS-30149 Fix create-acct-doc report formatting

---

src/main/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImpl.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestDI.java
src/test/resources/edu/cornell/kfs/fp/batch/xml/single-di-invalid-create-date-test.xml

The #1535 Create-Acct-Doc changes incorrectly assumed that an exception would be thrown by the XML parser if the file's create date could not be converted properly; it's actually being set to null on the POJO in such cases. This PR adjusts those prior changes so that if such a null create date is encountered, it will be logged as a warning and then it will be ignored, thus avoiding unexpected NullPointerExceptions when preparing the file entry BOs. (The Create Accounting Documents Job does not need that particular date field for its processing, so it's safe to ignore invalid values  there.)

KFSPTS-30631 Fix handling of bad Create-Acct-Doc create dates

---

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksNewVendorCreateKfsAchStep.java
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksNewVendorCreateKfsVendorStep.java
src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksUploadSuppliersStep.java
src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java

The payment works integration is currently working again, payment works reverted a change they implemented that caused our problem.
The change in this PR should allow the PMW batch jobs to fail gracefully when an API error happens again.  if an API error happens again, this change should make it so a batch container restart won't be required to run a job again.  The functionals and Sandy agreed that we don't want to purse a more complicated solution at this time.

KFSPTS-30931 update PMW to gracefully fail when payment works endpoints have exceptions

---

pom.xml

There are PRs for this in cu-kfs and cornell_customizations. Please make sure both PRs are good to go before merging.
Our WAR overlay is not properly excluding the archaic Log4J libraries from the base KFS WAR. This PR fixes and simplifies that configuration to get the Log4J exclusions working again. (Note that only the "log4j-*" JARs are being excluded; the "log4j2-*" JARs are being left as-is for now.)
In addition, since this PR is cleaning up the Log4J setup anyway, it's also upgrading the Log4J JARs to one of the newer versions. There's currently another version that's slightly newer than the one used by this PR, but that newer one was only released last week so I wasn't sure if it was too early for us to try and use it. If you think we should upgrade to that latest one anyway, please …

KFSPTS-31128 Update Log4J version

---

src/main/java/org/kuali/kfs/sys/cache/CacheConfiguration.java

NOTE: Please read through the last paragraph BEFORE merging!
Base financials code is excluding the cache's name from the Redis cache entries' keys, but this impacts cache-clearing operations so that they clear all of the caches, not just the named cache. (For example, routing a Parameter Document to FINAL would normally only clear the "ParameterType" cache, but this setup would cause such documents to potentially clear all the caches, including the "BatchFile" cache.) This PR fixes the problem by removing the piece of problematic configuration that is suppressing the extra info from the cache keys.
When this PR's changes are in place, the Redis cache entries should have keys that are in `CacheName::CacheKey` format (such as `DocumentTypeType::documentTypeId=6048273`). Our old …

KFSPTS-31172 Fix cache slowness in KFS

---

src/main/java/edu/cornell/kfs/fp/document/validation/impl/CuDisbursementVoucherDocumentPreRules.java

An initial review can be performed now if desired, but please don't merge until after I get functional feedback on whether the scope of the changes should be expanded further.
DV documents have a pre-rules question that allows for auto-clearing the Wire Transfer tab if the payment method has been set to something other than Wire Transfer. To keep this feature working with our Wire Transfer extended attribute, this PR updates the relevant pre-rules sections so that the extension fields will also be cleared out.

KFSPTS-30809 Fix clearing of DV Wire Transfer tab

---

src/main/java/edu/cornell/kfs/kim/CuKimConstants.java
src/main/java/edu/cornell/kfs/kim/CuKimPropertyConstants.java
src/main/java/edu/cornell/kfs/kim/impl/identity/PersonExtension.java
src/main/java/edu/cornell/kfs/kim/inquiry/CuPersonInquirableImpl.java
src/main/java/edu/cornell/kfs/kim/util/CuKimUtils.java
src/main/java/edu/cornell/kfs/kim/web/struts/form/CuIdentityManagementPersonDocumentForm.java
src/main/java/org/kuali/kfs/kim/document/IdentityManagementPersonDocument.java
src/main/java/org/kuali/kfs/kim/impl/identity/Person.java
src/main/webapp/WEB-INF/tags/kim/personEmail.tag
src/main/webapp/WEB-INF/tags/kim/personName.tag
src/main/webapp/WEB-INF/tags/kim/personPhone.tag
src/main/webapp/WEB-INF/web.xml

The 01/29 upgrade initially set up the custom name/email/phone masking to behave similarly to KualiCo's customized address masking. However, part of that workaround was causing browser session issues when entering NetIDs into certain form fields.
This PR removes the problematic configuration that was interfering with the browser sessions. As a result, the name/email/phone masking has been adjusted to behave similarly to the pre-01/29 releases, where the Person info is generally masked on most screens (even to users with unmasking permissions), though the Person Inquiry and/or Person Document have some easing of those restrictions.
Note that KualiCo's address masking (and our related custom alt-address masking) are still working as-is, for consistency with base code behavior. Also note …

KFSPTS-31509 Improve Person masking behavior

---

src/main/java/edu/cornell/kfs/sec/CuSecParameterConstants.java
src/main/java/edu/cornell/kfs/sec/service/impl/CuAccessSecurityServiceImpl.java
src/main/resources/edu/cornell/kfs/sec/cu-spring-sec.xml

There are PRs for this in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging. Also, please coordinate with the team on whether these changes should be merged before or after the merging of the 2023-01-29 financials upgrade.
If the KIM permissions and Access Security restrictions are configured in a certain way, there are situations where users can view a document for which they have an active Action Request, but then lose that access after taking action. To allow such users to continue to view documents that they had previously received during routing, this PR customizes the Access Security processing to look for both prior and current requests.
Note that, as requested, the relaxed restrictions are only applied to a specific set of documents (controlled by a …

KFSPTS-28426 Allow SEC view-doc overrides based on route log

---

src/main/resources/edu/cornell/kfs/kim/cu-ojb-kim.xml
src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml

The KFSPTS-31521 changes fixed the maintenance XML conversion for older pre-01-29-patch documents, but then the functionals discovered that the maintenance docs were encountering errors upon taking workflow action. Further analysis revealed that the OJB list proxying on the PersonExtension's affiliations list was messing up newly-saved maintenance XML, at least on the Person references within BO Notes. To prevent future list-proxy-related and Note-related issues, this PR changes the problematic list to a non-proxy one, and also adds a maintenance XML conversion rule to remove the Person references on the BO Notes, similar to the Person removal rules introduced by KFSPTS-31521.

KFSPTS-31545 Fix handling of Person references on BO Notes

---

src/main/java/edu/cornell/kfs/kim/impl/identity/CuPersonServiceImpl.java

This PR backports the FINP-10589 KualiCo fix, which corrects a case sensitivity issue when searching for users by principal name. Since we already had a CU override of the affected service, and since the needed code changes were very small, the backport was added to the CU subclass instead of in an overlay.
Note that a small modification was made to the backported fix, as noted in the code comments, due to a possible misconfiguration from KualiCo. I will create a follow-up user story to report the issue back to KualiCo.

KFSPTS-31462 Backport FINP-10589 case sensitivity fix

---

src/main/java/edu/cornell/kfs/fp/batch/service/impl/PreEncumbranceDocumentGenerator.java
src/main/java/edu/cornell/kfs/fp/batch/xml/AccountingXmlDocumentAccountingLine.java
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestBase.java
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestPE.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingDocumentMapping.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentAccountingLineFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentEntryFixture.java
src/test/java/edu/cornell/kfs/fp/batch/xml/fixture/AccountingXmlDocumentListWrapperFixture.java
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-doc-types-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/multi-pe-document-test.xml
src/test/resources/edu/cornell/kfs/fp/batch/xml/single-pe-document-test.xml

This PR add pre encumbrance documents to the create accounting document job.  The KFS system user already has permissions to initiate the PE document, so no SQL or permission changes are needed.

KFSPTS-31435 add PE documents to create accounting documents job

---

src/main/webapp/WEB-INF/tags/kr/user.tag
src/main/webapp/WEB-INF/tags/sys/employee.tag

Part of the 01/29/2023 patch's CU-specific Person name masking has special configuration in place to handle the masking of Ad Hoc Person differently. However, we accidentally overlooked Ad Hoc Person object properties related to KualiCo's Document FYI Notes feature. This PR updates our customization to properly handle the FYI Notes recipient textboxes.

KFSPTS-31661 Fix note FYI feature

---

src/main/java/org/kuali/kfs/datadictionary/legacy/CuDataDictionaryService.java
src/main/resources/edu/cornell/kfs/coa/cu-ojb-coa.xml

This PR fixes two bugs related to the Account Delegate Global documents:
* It adds the appropriate OJB metadata to allow the doc's Account lookup search results to display the names of the Fiscal Officer, Account Manager and Account Supervisor. Prior to this fix, those fields contained empty values in the search results. (The 01/29/2023 patch now allows BOs to load their Person objects from the database directly.)
* It adjusts our property-name-replacing customization that's related to implementing our custom Person data masking. Prior to this fix, the customization was not traversing the Data Dictionary bean graph deeply enough in certain cases, resulting in errors/warnings that caused certain Account Delegate Global fields to display empty labels. With these changes in place, the …

KFSPTS-31781 Fix Account Delegate Global displays

---

src/main/java/edu/cornell/kfs/coa/service/impl/CuAccountServiceImpl.java
src/main/java/org/kuali/kfs/kim/service/impl/UiDocumentServiceImpl.java
src/main/java/org/kuali/kfs/kim/service/impl/UiDocumentWorkflowHelper.java
src/main/resources/edu/cornell/kfs/kim/cu-spring-kim.xml

This PR backports KualiCo's FINP-9525 fix, which prevents a requeue of all pending Account-route-node documents when inactivating a Person that has no Fiscal Officer delegations. It also includes a fix for preventing such mass requeues when performing minor changes on a Role document; however, the latter part of the fix doesn't seem to be working in certain cases. Nevertheless, the functionals are fine with this backported FINP moving forward as-is, and we'll report the latter issue to KualiCo and/or use a separate user story for fixing it as needed.

KFSPTS-31931 Backport FINP-9525 doc requeue fix

---

src/main/java/edu/cornell/kfs/krad/service/BlackListAttachmentService.java
src/main/java/edu/cornell/kfs/krad/service/impl/BlackListAttachmentServiceImpl.java
src/main/java/edu/cornell/kfs/krad/service/impl/CuAttachmentServiceImpl.java
src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java
src/main/java/edu/cornell/kfs/sys/CUKFSParameterKeyConstants.java
src/main/java/org/kuali/kfs/kns/web/struts/action/KualiDocumentActionBase.java
src/main/resources/CU-ApplicationResources.properties
src/main/resources/edu/cornell/kfs/krad/config/CUKRADSpringBeans.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuAttachmentServiceImplTest.java

The only difference between this version of the code and the previous version is the user error message in file CU-ApplicationResources.properties

KFSPTS-31189: Create blacklist parameter and service that disallow attachments on KFS documents based on the file extensions listed in the parameter.

---

src/main/java/edu/cornell/kfs/krad/service/impl/CuDocumentServiceImpl.java
src/main/java/edu/cornell/kfs/module/purap/CUPurapConstants.java
src/main/java/edu/cornell/kfs/module/purap/CUPurapKeyConstants.java
src/main/java/edu/cornell/kfs/module/purap/document/authorization/IWantDocumentAuthorizer.java
src/main/java/edu/cornell/kfs/module/purap/document/authorization/IWantDocumentPresentationController.java
src/main/java/edu/cornell/kfs/module/purap/document/web/struts/IWantDocumentAction.java
src/main/java/edu/cornell/kfs/module/purap/document/web/struts/IWantDocumentForm.java
src/main/resources/edu/cornell/kfs/module/purap/cu-purap-resources.properties
src/main/resources/edu/cornell/kfs/module/purap/document/workflow/IWantDocument.xml
src/main/webapp/WEB-INF/tags/module/purap/iWantContract.tag

**Note**: in addition to the return to SSC functionality, the following were also implemented as part of this user story:
- the Purchasing Assistant role has been renamed to Procurement Contract Assistant(cu) (KFSPTS-31840). The necessary code changes were added so that the contract functionality would still work
- Contract Tab I Want Doc: Add Jaggaer to label (KFSPTS-31837) - this change has been implemented

KFSPTS-30888 add return to SSC functionality

---

src/main/java/edu/cornell/kfs/fp/CuFPConstants.java
src/main/java/edu/cornell/kfs/fp/CuFPKeyConstants.java
src/main/java/edu/cornell/kfs/fp/batch/AccountingXmlDocumentInputFileType.java
src/main/java/edu/cornell/kfs/sys/batch/CuXmlBatchInputFileTypeBase.java
src/main/resources/edu/cornell/kfs/fp/batch/accountingXmlDocument.xsd
src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
src/test/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImplTestBase.java
src/test/java/edu/cornell/kfs/sys/util/GlobalResourceLoaderUtils.java

This PR updates the Create Accounting Documents Job so that it uses our extension to the base financials JAXB file type, rather than using our CU-specific JAXB file type that delegates to our custom `CUMarshalService`. Note the following, though:
* We're currently using a custom listener/handler when processing the Accounting Document XML, so that we can catch and report parsing errors on a per-document-entry basis. KualiCo's base XML file type class doesn't allow for specifying such listeners/handlers at parsing time, and trying to reconfigure JAXB to set up some auto-handling of that seems to be impractical. Thus, I had to introduce a custom parsing method variant in our base extension.
* A simple XSD schema has been added since the base financials class expects schema validation to be …

KFSPTS-30386 Move Accounting Document XML filetype to new class

---

src/main/java/edu/cornell/kfs/module/purap/document/authorization/IWantDocumentAuthorizer.java
src/main/java/edu/cornell/kfs/module/purap/document/authorization/IWantDocumentPresentationController.java
src/main/webapp/WEB-INF/tags/module/purap/iWantContract.tag

This PR adjusts the editability of the IWNT Procurement Assistant NetID, so that it's only editable at a specific route node by a specific role's members.

KFSPTS-32444 Fix editing of IWNT Proc Assistant NetID

---

src/main/webapp/jsp/kim/IdentityManagementPersonDocument.jsp
src/main/webapp/jsp/kim/IdentityManagementRoleDocument.jsp

This PR adds the Notes and Attachments tab to the Person Document and the Role Document. Note that, because both of these documents set the "readOnly" flag at the request level, it needs to be temporarily set to false when rendering the Notes and Attachments tab; otherwise the add-line section might not be fully editable. Also, the Person Document needed a minor tweak to allow for adding attachments.

KFSPTS-32580 Enable notes on Person and Role docs

---

src/main/java/org/kuali/kfs/sys/context/BatchStepExecutor.java

This PR fixes the issue that is causing our batch jobs to get stuck when they throw exceptions. It appears that KualiCo messed up the `BatchStepExecutor` class's log-related refactoring for FINP-9025, so I overlayed it to rearrange the error handling and have it create the .error file(s) at the correct times.

KFSPTS-32020 Fix batch jobs getting stuck when encountering errors

---

src/main/resources/edu/cornell/kfs/tax/cu-tax-resources.properties
src/main/resources/institutional-config.properties

This PR removes some unneeded properties from our KFS `institutional-config.properties` file. Some pertained to a Rice auto-XML-ingestion feature that no longer exists in KFS, others pertained to Quartz jobs that were later converted into KFS batch jobs, and one pertained to a thread dump feature that was removed by FINP-7441.
Also, for consistency with our other application resource property files, the two tax-related `message.batchUpload.*` properties have been moved into the appropriate tax module file instead.
There are some unneeded `data.xml.*` properties in the KFS config property template in kuali-puppet as well. If you think a related kuali-puppet PR should be created as part of this cleanup work, please let me know.

KFSPTS-31658 Clean up config properties

---

src/main/webapp/WEB-INF/tags/ksr/securityRequestRole.tag

This PR adds icons/links to KSR documents that allow for opening the associated Roles' inquiries in a new tab/window. Because Role inquiries take a long time to render or potentially time out if they have a large number of members (due to the inquiries displaying a non-paged members list), I configured the KSR docs to render only the open-in-new-tab links, rather than additionally rendering the usual open-in-modal links. That's why the proposed changes do NOT use the `kul:inquiry` tag.
The changes have been configured to be similar to other areas of KFS that render the open-in-new-tab links directly.

KFSPTS-24998 Add role inquiry links to KSR docs

---

src/main/java/org/kuali/kfs/module/cam/businessobject/actions/AssetActionsProvider.java

After the 4/19 upgrade functionals noticed that the custom links on the Asset lookup results show up for users that don't have them displayed in the previous version. After looking into the current production code it looks like the Actions column is fully ignored in the old lookup if the user does not have edit permission for Assets. Similar logic was implemented in the AssetActionsProvider.

KFSPTS-33649 only add custom actions if user can edit

---

src/main/java/edu/cornell/kfs/vnd/batch/VendorEmployeeComparisonResultCsv.java
src/test/java/edu/cornell/kfs/vnd/batch/service/impl/fixture/VendorComparisonResultRowFixture.java

This PR fixes the VN-99-03 batch job so that, rather than expecting the CSV file's boolean values to be written as "yes"/"no" (case-insensitive), it can now handle KualiCo's other accepted boolean string values as well (0, 1, N, Y, etc.).
Some (but not all) of the associated unit test data has been updated, so that the tests can validate both the yes/no setup and the 1/0 setup.

KFSPTS-32561 Fix boolean value handling for VN-99-03

---

src/main/resources/edu/cornell/kfs/vnd/cu-spring-vnd.xml

Base code doesn't explicitly specify "reports/vnd" as a mapped batch file directory. This PR adds such a mapping, so that the related KIM permissions will properly allow authorized users to download files from the "reports/vnd" directory.

KFSPTS-34001 Fix permission handling for Vendor report files

---

src/main/java/edu/cornell/kfs/module/purap/document/CuPaymentRequestDocument.java
src/main/java/edu/cornell/kfs/module/purap/document/CuVendorCreditMemoDocument.java
src/main/java/org/kuali/kfs/module/purap/document/PaymentRequestDocument.java

The post XML ingestion SQL from the 2023-04-19 KualiCo patch did not update canceled or disapproved PREQ documents.  This code change allows those PREQ documents to be opened.

KFSPTS-34074 allow older PREQ and CM documents in canceled or disapproved status to be opened

---

src/main/java/edu/cornell/kfs/vnd/batch/service/VendorEmployeeComparisonReportService.java
src/main/java/edu/cornell/kfs/vnd/batch/service/impl/VendorEmployeeComparisonReportServiceImpl.java
src/main/java/edu/cornell/kfs/vnd/batch/service/impl/VendorEmployeeComparisonServiceImpl.java
src/main/resources/edu/cornell/kfs/vnd/cu-spring-vnd.xml
src/main/resources/edu/cornell/kfs/vnd/cu-vnd-resources.properties
src/test/java/edu/cornell/kfs/vnd/CuVendorTestConstants.java
src/test/java/edu/cornell/kfs/vnd/batch/service/impl/VendorEmployeeComparisonServiceResultFileTest.java
src/test/java/edu/cornell/kfs/vnd/batch/service/impl/annotation/VendorComparisonResultRow.java
src/test/java/edu/cornell/kfs/vnd/batch/service/impl/fixture/VendorComparisonResultRowFixture.java
src/test/resources/edu/cornell/kfs/vnd/batch/service/impl/cu-spring-vnd-empl-comparison-result-test.xml
src/test/resources/edu/cornell/kfs/vnd/batch/service/impl/empl-compare-report/rpt-multiple-rows.txt
src/test/resources/edu/cornell/kfs/vnd/batch/service/impl/empl-compare-report/rpt-row-with-missing-data.txt
src/test/resources/edu/cornell/kfs/vnd/batch/service/impl/empl-compare-report/rpt-single-active-row.txt
src/test/resources/edu/cornell/kfs/vnd/batch/service/impl/empl-compare-report/rpt-single-inactive-row.txt

This PR makes some additional VN-99-03 batch job enhancements to accompany the #1697 changes:
* Adds a "Vendor Type" column to the batch job's generated report file. As requested by the functionals, the column is only being added to the report file, not to the CSV files being sent to/from Workday.
* Right-justifies the report's existing "Vendor ID" column.
* Made a few other misc. changes, such as fixing the cleanup of failed report generation attempts and improving the setup of the related unit tests.

KFSPTS-32561: Sub-task KFSPTS-34103: Adjust columns in VN-99-03 report file

---

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/OffsetDefinition.xml

There are PRs for this change in cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
This PR backports KualiCo's FINP-9919 code changes, which fix some misconfigured items related to the Offset Definition lookup.

KFSPTS-34243 Backport FINP-9919 Offset Definition fix

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/AccountCustomAddressTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/AccountTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/AwardTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyAccountTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyAwardTest.xml
src/test/resources/edu/cornell/kfs/krad/service/impl/ProposalTest.xml

We discovered during FYE2025 Dress Rehearsal testing that the 08/30/2023 patch's removal of the Org field `organizationInFinancialProcessingIndicator` was preventing certain maintenance documents (especially Account documents) from opening successfully, due to improper maintenance XML conversion. We had already included the relevant FINP-10001 maintenance XML conversion changes as part of the 08/30/2023 upgrade; however, it appears that KualiCo's new conversion rules are not sufficient for converting nested Organization objects within another BO (Account, Award, etc.). This PR adds another set of conversion rules to properly convert those nested objects.
NOTE: For the refactoring of the unit tests, the contents of `AccountTest.xml` have been transferred over to `LegacyAccountTest.xml`, …

KFSPTS-34870 Fix Org/Account maintenance XML conversion

---

src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/CuPaymentRequestDocument.xml
src/main/webapp/WEB-INF/tags/module/purap/paymentRequestInit.tag
src/main/webapp/scripts/module/purap/preqInitUtils.js

This PR adds a CU-specific implementation of the proposed FINP-10238 PREQ enhancement, which updates the PREQ initialization screen to auto-populate the Invoice Received Date from the Invoice Date if the former is blank. Note that KualiCo has not implemented FINP-10238 yet, which is why we have to create our own implementation of it.
In addition to the "onblur" handling proposed by FINP-10238, this CU-specific implementation adds such handling to the "onchange" event as well, so that the field will update properly when the user enters a date via the date-picker widget instead of direct input. Furthermore, our version will perform a simple regex check on the Invoice Date before using it to populate the Invoice Received Date, to help reduce the risk of auto-populating malformed dates.
Note …

KFSPTS-35018 Add CU-specific version of FINP-10238 PREQ fix

---

src/main/java/edu/cornell/kfs/kim/CuKimConstants.java

There are PRs for this change in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging.
The only change on the code side was adding a new affiliation code constant, for consistency with the other affiliations. Nothing is actively using the new constant at this time.

KFSPTS-34289 Add MACHINE Person affiliation type

---

src/main/java/edu/cornell/kfs/module/purap/rest/resource/CuEinvoiceApiResource.java

There are PRs for the related user story in cu-kfs, einvoice-api-server and einvoice-website. Please make sure all of them are good to go before merging.
The primary changes are on the eInvoice application/website side; however, I did discover an issue where if there are no invitation records in the Postgres database, then opening the Invitations screen/tab could cause the related KFS API call to search for all KFS Vendors (thus potentially causing the API call to time out or encounter some other error). This specific PR fixes the bug by making the API call return an empty array if no vendor numbers were passed in.
If you think this fix should be deferred to another user story or should be implemented on the eInvoice application side instead, please let me know.

KFSPTS-32702 Fix eInvoice unbounded query issue

---

src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java
src/main/java/org/kuali/kfs/module/cam/businessobject/AssetLocationGlobal.java

Asset Location Global documents, like other global maintenance documents, persist the maintenance BO (and child objects) to the corresponding database tables upon saving, instead of merely storing the BO in the XML content prior to finalization. However, the Asset Location Global Detail child objects have database constraints on the Building and Room references, which can interfere with saving docs containing invalid Building/Room data because save-only maint doc actions aren't aborted for regular business rule failures. This PR fixes the problem by using KualiCo's existing `isPersistable()` Global BO method to include the appropriate validation, thus forcing the save operation to abort if the current data would result in a DB-level constraint violation.
Note that it was more convenient …

KFSPTS-34457 Fix Asset Location Global on-save issue

---

src/main/resources/edu/cornell/kfs/pdp/document/datadictionary/CuPayeeACHAccountMaintenanceDocument.xml

With our upgrade to the 06/28/2023 financials patch, The Payee ACH Account Maintenance Document (PAAT) was supposed to mark the Standard Entry Class field as a required one. However, that change was accidentally overlooked during the upgrade, and the affected section of bean XML was completely overridden on our side (thus preventing us from picking up the change automatically). This PR fixes the problem by adding the needed configuration setting to the appropriate bean override.

KFSPTS-35342 Fix required field setting on PAAT doc

---

src/main/java/edu/cornell/kfs/kim/batch/dataaccess/impl/KimFeedEdwDaoJdbc.java
src/main/java/edu/cornell/kfs/kim/batch/service/impl/KimFeedServiceImpl.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlQuery.java
src/main/java/edu/cornell/kfs/sys/util/CuSqlQueryPlatformAwareDaoBaseJdbc.java

I updated KimFeedEdwDaoJdbc to extend CuSqlQueryPlatformAwareDaoBaseJdbc to make use of the logging functionality.  If you think KimFeedEdwDaoJdbc should continue to extend PlatformAwareDaoBaseJdbc, I could move the logging functionality to a static utility class.  Let me know if you think that would be a better approach.

KFSPTS-31717 update KIM Feed V2 logging details

---

src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml
src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java
src/test/resources/edu/cornell/kfs/krad/service/impl/VendorSupplierDiversityTest.xml

One of our previous financials patch upgrades resulted in the removal of a custom extended attribute for Vendor Supplier Diversity, thus requiring some changes to our maintenance XML conversion rules so that older Vendor documents could still be opened. However, that particular set of conversion rule changes was accidentally misconfigured, resulting in errors when users attempt to open or act upon older Vendor documents containing Supplier Diversity data. This PR fixes the issue by correcting the problematic conversion rules; it also adds a new unit test case to verify their correctness.

KFSPTS-35584 Fix Vendor maintenance XML conversion

---

src/main/java/edu/cornell/kfs/sys/service/impl/CuEmailServiceImpl.java
src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml

The 12/20/2023 financials upgrade changed email messages so that the tenant name (or the "No tenant specified" message when tenant name isn't configured) is always included in the email subject line. This PR modifies the email service so that if the environment hasn't configured a tenant name, the "No tenant specified" message will be omitted from the email subject line.

KFSPTS-35626 Omit tenant message from email subjects

---

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java
src/main/java/org/kuali/kfs/sys/web/struts/ErrorHandlerAction.java
src/main/resources/institutional-config.properties

Please don't merge this yet.
I want to see if developers agree with this approach.  If you agree with this approach, I will rebuild sandbox from this branch and add a new property just for sandbox "cu.appspider.enabled=true".
If this configuration affects app spider scanning as we hope, we can merge this code to develop and send it through our regular code migration path.
The goal is to be able display the "our apologies" screen rather than the stack trace display in a non prod environment.  This will hopefully prevent app spider from detecting false vulnerabilities.

KFSPTS-35705 KFSPTS-25264 display our apologies screen when app spider testing is enabled
