CU-CommunityApps/cu-kfs

src/main/resources/edu/cornell/kfs/module/ld/document/datadictionary/YearEndSalaryExpenseTransferDocument.xml, src/main/resources/edu/cornell/kfs/module/ld/document/validation/configuration/CuYearEndSalaryExpenseTransferValidations.xml
This used to be a sub-task of another story before becoming a full story, hence the odd branch name.
=> KFSPTS-5238: Replaced org review with account review on YEST documents, and removed its org-assigned validation.

src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardFlatInputFileType.java, src/main/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/fp/businessobject/ProcurementCardTransactionDetailExtendedAttribute.java, src/main/java/edu/cornell/kfs/fp/businessobject/ProcurementCardTransactionExtendedAttribute.java, src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataBase.java, src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataDetail.java, src/main/java/edu/cornell/kfs/fp/businessobject/PurchasingDataRecord.java, src/main/java/edu/cornell/kfs/fp/businessobject/USBankAddendumRecord.java, src/main/java/edu/cornell/kfs/fp/businessobject/USBankRecordFieldUtils.java, src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionDetail.xml, src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionDetailExtendedAttribute.xml, src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/ProcurementCardTransactionExtendedAttribute.xml, src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/PurchasingDataDetail.xml, src/main/resources/edu/cornell/kfs/fp/businessobject/datadictionary/PurchasingDataRecord.xml, src/main/resources/edu/cornell/kfs/fp/cu-ojb-fp.xml
This is the same code as #35 . I had to back it out of develop due to some issues in the processing of the procurementCardDocumentJob this week. After some testing, I believe that the issues were due to there being bank files that had been uploaded in DEV but not yet processed.
So, assuming you see no issues with the code, here's what I'd like to do:
1) Review and confirm that it's good to go (just in case)
2) Wait until Monday to merge
3) On Monday, I'll request that Prod Control run the process to make sure that all the existing bank files have been processed before the code and SQL goes back in.
4) :+1:
=> [KFSPTS-4808] Level3 PCard Type 50 record implementation

src/main/resources/edu/cornell/kfs/coa/document/workflow/SubAccountGlobalMaintenanceDocument.xml
This change will need to be ingested as is progresses through each of the environments.
=> KFSPTS-5204:Update document header label on Sub-Account Global edoc.

README.md
Check out this fabulous README.
=> [KFSPTS-4976] create a readme for the cu-kfs project

src/main/java/edu/cornell/kfs/module/purap/document/CuPaymentRequestDocument.java
This is a quick change to copy the PO's document explanation over to the PREQ's document explanation.
=> KFSPTS-5332: Updated PREQ creation process to copy the doc header explanation from the PO.

src/main/java/edu/cornell/kfs/coa/businessobject/A21SubAccountChange.java, src/main/java/edu/cornell/kfs/coa/businessobject/IndirectCostRecoveryAccountChange.java, src/main/java/edu/cornell/kfs/coa/businessobject/SubAccountGlobal.java, src/main/java/edu/cornell/kfs/coa/document/SubAccountGlobalMaintainableImpl.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRule.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalRule.java, src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/A21SubAccountChange.xml, src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/IndirectCostRecoveryAccountChange.xml, src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/SubAccountGlobal.xml, src/main/resources/edu/cornell/kfs/coa/cu-ojb-coa.xml, src/main/resources/edu/cornell/kfs/coa/document/datadictionary/SubAccountGlobalMaintenanceDocument.xml
Hi Chad, After testing in DEV I found a couple of issues with some reference objects not being refreshed and fixed that. I have also changed the order for the ICR rate and type to match the Sub-Account doc.  Please review at your convenience. Thank you.
=> KFSPTS-4792 Add new fields to Sub-Account Global doc

src/main/java/edu/cornell/kfs/tax/CUTaxConstants.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/Transaction1099Summary.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1099Processor.java, src/main/java/edu/cornell/kfs/tax/service/PaymentReason1099BoxService.java, src/main/java/edu/cornell/kfs/tax/service/impl/PaymentReason1099BoxServiceImpl.java, src/main/resources/edu/cornell/kfs/tax/cu-spring-tax.xml, src/test/java/edu/cornell/kfs/tax/service/impl/PaymentReason1099BoxServiceImplTest.java
This is ready for review again.
@bhutchinson since you also reviewed the original PR with Chad H, I am pinging you in as well
=> KFSPTS-5409 mapping payment reasons to 1099 tax box

src/main/java/edu/cornell/kfs/module/purap/document/CuRequisitionDocument.java, src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuPurchaseOrderServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/CuRequisitionAction.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/sys/businessobject/NoteExtendedAttribute.java, src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/RequisitionDocument.xml, src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/Note.xml, src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/NoteExtendedAttribute.xml, src/main/resources/edu/cornell/kfs/sys/cu-ojb-sys.xml, src/main/webapp/WEB-INF/tags/module/purap/camsDetail.tag, src/main/webapp/WEB-INF/tags/module/purap/notes-sciquest.tag, src/main/webapp/scripts/module/purap/reqsNotes.js
should be copied to the PO. (KFSPTS-5924: put back what once was lost)
=> KFSPTS-4490: Added checkbox on REQS notes to indicate whether they

src/main/java/edu/cornell/kfs/coa/businessobject/CuAccountGlobal.java, src/main/java/edu/cornell/kfs/coa/businessobject/GlobalObjectWithIndirectCostRecoveryAccounts.java, src/main/java/edu/cornell/kfs/coa/businessobject/IndirectCostRecoveryAccountChange.java, src/main/java/edu/cornell/kfs/coa/businessobject/SubAccountGlobal.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/AccountGlobalPreRules.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRule.java, src/main/java/edu/cornell/kfs/coa/service/GlobalObjectWithIndirectCostRecoveryAccountsService.java, src/main/java/edu/cornell/kfs/coa/service/impl/GlobalObjectWithIndirectCostRecoveryAccountsServiceImpl.java, src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/java/org/kuali/kfs/coa/document/validation/impl/AccountGlobalRule.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/AccountGlobal.xml, src/main/resources/edu/cornell/kfs/coa/cu-ojb-coa.xml, src/main/resources/edu/cornell/kfs/coa/cu-spring-coa.xml, src/main/resources/edu/cornell/kfs/coa/document/datadictionary/AccountGlobalMaintenanceDocument.xml, src/test/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRuleTest.java, src/test/java/edu/cornell/kfs/coa/fixture/A21IndirectCostRecoveryAccountFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/A21SubAccountFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/AccountFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/AccountGlobalDetailFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/AccountGlobalFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/IndirectCostRecoveryAccountChangeFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/IndirectCostRecoveryAccountFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/SubAccountGlobalDetailFixture.java, src/test/java/edu/cornell/kfs/coa/fixture/SubAccountGlobalFixture.java, src/test/java/edu/cornell/kfs/coa/service/impl/GlobalObjectWithIndirectCostRecoveryAccountsServiceImplTest.java
Latest round of requested code review changes.
=> Kfspts 3599-new-4

src/main/java/edu/cornell/kfs/sys/businessobject/FavoriteAccount.java, src/main/java/edu/cornell/kfs/sys/businessobject/UserProcurementProfile.java, src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/FavoriteAccount.xml, src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/UserProcurementProfile.xml, src/main/resources/edu/cornell/kfs/sys/cu-ojb-sys.xml, src/main/resources/edu/cornell/kfs/sys/document/datadictionary/UserProcurementProfileMaintenanceDocument.xml
Hi Bryan,
Please review code changes related to KFSPTS-5490 to add active indicator on User Profile and Favorite Account. I have also assigned you the PR for the related SQL: https://github.com/CU-CommunityApps/nonprod-sql/pull/16
Please note I did tiny bit of cleaning with the changes too.
Please don't merge yet as I am still waiting for feedback from Cathy but wanted to get this out for review. (I don't expect significant changes after functional feedback)
=> KFSPTS-5490 Add active indicator for User Profile and Favorite Account

src/main/resources/CU-ApplicationResources.properties
Hi Bryan,
I compared the develop and master files and found 3 error messages missing. They were all added on this commit.
=> KFSPTS-3599 add missing error messages

pom.xml, src/main/java/edu/cornell/kfs/fp/CuFPConstants.java, src/main/java/edu/cornell/kfs/fp/batch/LoadAWSBillsStep.java, src/main/java/edu/cornell/kfs/fp/businessobject/AmazonBillingCostCenterDTO.java, src/main/java/edu/cornell/kfs/fp/businessobject/AmazonBillingDistributionOfIncomeTransactionDTO.java, src/main/java/edu/cornell/kfs/fp/service/AmazonWebServicesBillingService.java, src/main/java/edu/cornell/kfs/fp/service/impl/AmazonWebServicesBillingServiceImpl.java, src/main/java/edu/cornell/kfs/fp/xmlObjects/AmazonAccountDetail.java, src/main/java/edu/cornell/kfs/fp/xmlObjects/AmazonAccountDetailContainer.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml, src/test/java/edu/cornell/kfs/fp/service/impl/AmazonWebServicesBillingServiceImplTest.java
Please don't merge this yet, I need to verify some outputs with Nicole, and see it run against the WS after it has been restored.  I would like some feedback on the code in the mean time.
=> KFSPTS-5988 Implement AWS billing integration

src/main/java/edu/cornell/kfs/fp/batch/ApproveDvsSpawnedByRecurringDvStep.java, src/main/java/edu/cornell/kfs/fp/dataaccess/RecurringDisbursementVoucherSearchDao.java, src/main/java/edu/cornell/kfs/fp/dataaccess/impl/RecurringDisbursementVoucherSearchDaoJdbc.java, src/main/java/edu/cornell/kfs/fp/service/RecurringDisbursementVoucherDocumentService.java, src/main/java/edu/cornell/kfs/fp/service/impl/RecurringDisbursementVoucherDocumentServiceImpl.java, src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
New pull request was required due to inability to auto merge after PR205 changes were made. 
This PR contains those requested changes.
=> KFSPTS-5860: Create new batch job that will automatically approve DV documents spawned by the Recurring DV document.

src/main/java/edu/cornell/kfs/fp/CuFPConstants.java, src/main/java/edu/cornell/kfs/fp/businessobject/RecurringDisbursementVoucherPDPStatus.java, src/main/java/edu/cornell/kfs/fp/document/service/CuDisbursementVoucherExtractionHelperService.java, src/main/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherExtractionHelperServiceImpl.java, src/main/java/edu/cornell/kfs/fp/document/web/struts/RecurringDisbursementVoucherAction.java, src/main/java/edu/cornell/kfs/fp/document/web/struts/RecurringDisbursementVoucherForm.java, src/main/java/edu/cornell/kfs/fp/service/RecurringDisbursementVoucherDocumentService.java, src/main/java/edu/cornell/kfs/fp/service/RecurringDisbursementVoucherPaymentMaintenanceService.java, src/main/java/edu/cornell/kfs/fp/service/impl/RecurringDisbursementVoucherDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/fp/service/impl/RecurringDisbursementVoucherPaymentMaintenanceServiceImpl.java, src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml, src/main/webapp/WEB-INF/tags/fp/recurringDVPDPStatus.tag
This is takes care of border case of the an approved DV that hasn't been extracted yet.  Code that cancels the other cases remains the same.
=> KFSPTS-6324 Implement cancel of spawned DVs from recurring DV

src/main/resources/edu/cornell/kfs/core/documentstore/InstitutionPreferences.json
This is one of two related PRs for KFSPTS-6608, the other is in CU-CommunityApps/config.
=> KFSPTS-6608: add KFS Help menu link

src/main/resources/edu/cornell/kfs/sys/workflow/FinancialsParameterMaintenanceDocument.xml
This is one of two related pull requests that should be reviewed and merged together. The other is in the nonprod-sql repo.
=> KFSPTS-6698: update workflow config for new PARM doc type

src/main/java/edu/cornell/kfs/krad/service/impl/CuDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImpl.java, src/main/java/edu/cornell/kfs/krad/service/impl/CuMaintenanceXMLConverter.java, src/main/java/edu/cornell/kfs/krad/service/impl/NoOpMaintainableXMLConversionServiceImpl.java, src/main/java/org/kuali/kfs/krad/service/impl/DocumentServiceImpl.java, src/main/resources/edu/cornell/kfs/krad/config/CUKRADSpringBeans.xml, src/main/resources/edu/cornell/kfs/krad/config/MaintainableXMLUpgradeRules.xml, src/test/java/edu/cornell/kfs/krad/service/impl/CuMaintainableXMLConversionServiceImplTest.java, src/test/resources/edu/cornell/kfs/krad/service/impl/AccountCustomAddressTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/AccountReversionTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/AccountTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/AttributeSetTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/BasicConversionTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/DateFieldTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/LegacyNotesTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/MoveNodesToParentTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/NoteTypeReferenceTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/ObjectCodeGlobalTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/Rice2xNotesTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/TypedArrayListTest.xml, src/test/resources/edu/cornell/kfs/krad/service/impl/VendorTest.xml
This PR incorporates changes suggested in PR #245 as well as a couple more fixes found while testing those suggestions.
=> KFSPTS-6707: remediate KFS maintenance XML conversion feature

src/main/java/edu/cornell/kfs/sys/dataaccess/impl/PreferencesDaoDynamoDB.java, src/test/java/edu/cornell/kfs/sys/dataaccess/impl/PreferencesDaoDynamoDBTest.java
KFS's REST preferences endpoint is adding certain empty preferences by default, which don't appear to be used anywhere else yet but are causing problems with saving them to DynamoDB. This PR adds a fix adapted from one developed by Bryan, which will remove the empty default preferences for now. This may need revisiting in the future if a KFS patch ends up adding functionality for these new preferences.
=> KFSPTS-7336: Added fix to remove certain empty DynamoDB preferences.

src/main/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherPayeeServiceImpl.java
We had a customization in the DV Payee Service that fixed a KFS 5.x issue with sending an ad hoc to the initiator. However, this is now fixed in KFS 7.x, so our fix is breaking the fix in base code. This PR just removes our custom fix so that the base code can create the ad hoc request properly.
=> KFSPTS-7626: Fixed ad hoc to initiator when changing DV address.

src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/CuElectronicInvoiceRejectDocument.xml
I needed to add some currency-related config to the EIRT "Grand Total" field so that EIRT doc searches could handle the attribute value properly.
=> KFSPTS-7605: Fixed error when performing EIRT doc searches.

src/main/resources/edu/cornell/kfs/sys/businessobject/datadictionary/KfsBaseAttributeDefinitions.xml
Our base DD attributes file was out-of-sync with the KFS 7.x version of it. This brings it up-to-date while still preserving our existing customizations to it.
If you think the file should be modified to only include the things that we have specifically overridden, please let me know.
=> KFSPTS-7616: Update base DD bean overrides with KFS 7.x changes.

src/main/resources/edu/cornell/kfs/core/documentstore/InstitutionPreferences.json
These are the preferences JSON changes that go along with the related SQL PR that was just merged.
=> KFSPTS-7798: Add permission to restrict Current Account Balance lookup.

src/main/webapp/static/xsd/fp/disbursementVoucher.xsd
Reverts CU-CommunityApps/cu-kfs#305
=> Revert "KFSPTS-7795: fix DV Upload"

src/main/resources/edu/cornell/kfs/gl/businessobject/datadictionary/CurrentAccountBalance.xml, src/main/resources/edu/cornell/kfs/gl/cu-spring-gl.xml
This PR adjusts the result fields on the Current Account Balance lookup to match our current setup in PROD, which is what the functionals want as per the related user story.
=> KFSPTS-7878: Rename or remove Current Account Balance lookup columns.

src/main/java/edu/cornell/kfs/concur/batch/ConcurStandardAccountingExtractToPdpAndCollectorStep.java, src/main/java/edu/cornell/kfs/concur/batch/service/ConcurStandardAccountingExtractService.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractServiceImpl.java, src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
As per the recent discussion, the changes for this PR just rename the batch job/step and add a new service method for the SAE-to-collector processing.
=> KFSPTS-7909: Add template SAE-to-collector processing.

src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationProcessingServiceImpl.java, src/main/java/edu/cornell/kfs/concur/rest/xmlObjects/ConcurEventNotificationListDTO.java, src/main/java/edu/cornell/kfs/concur/service/ConcurEventNotificationService.java, src/main/java/edu/cornell/kfs/concur/service/ConcurReportsService.java, src/main/java/edu/cornell/kfs/concur/service/impl/ConcurEventNotificationServiceImpl.java, src/main/java/edu/cornell/kfs/concur/service/impl/ConcurReportsServiceImpl.java, src/main/java/edu/cornell/kfs/sys/service/CUMarshalService.java, src/main/java/edu/cornell/kfs/sys/service/impl/CUMarshalServiceImpl.java, src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml, src/test/java/edu/cornell/kfs/concur/rest/xmlObjects/ConcurEventNotificationListDTOTest.java, src/test/java/edu/cornell/kfs/concur/rest/xmlObjects/fixture/failed-event-queue-response-example.xml, src/test/java/edu/cornell/kfs/concur/service/impl/ConcurEventNotificationServiceImplTest.java
This adds the failed event queue processing the the concurEventNotificationProcessingBatchJob.  Note the unit tests will fail till some new parameters are added to the properties file.  I would like this code reviewed before I work with Chad B. to add the new properties file items.
=> KFSPTS-8228 failed event queue

src/main/java/edu/cornell/kfs/concur/ConcurConstants.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountExtractPdpEntryServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractServiceImpl.java, src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml, src/test/java/edu/cornell/kfs/concur/batch/fixture/PdpFeedAccountingEntryFixture.java, src/test/java/edu/cornell/kfs/concur/batch/fixture/PdpFeedDetailEntryFixture.java, src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountExtractPdpEntryServiceImplTest.java
Non Reimbursable expenses paid on the corporate care now deduct amounts from payments made to the traveler.
=> KFSPTS-8530 pdp handle cbcp

src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/IWantDocumentFeedServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/document/CuRequisitionDocument.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/IWantDocumentAction.java
This should match #388 except that it will be merged into the develop branch so it can follow our normal path to production.
=> KFSPTS-8521: fix name masking for IWNT and REQS

src/main/java/edu/cornell/kfs/concur/ConcurKeyConstants.java, src/main/java/edu/cornell/kfs/concur/ConcurParameterConstants.java, src/main/java/edu/cornell/kfs/concur/batch/service/ConcurBatchUtilityService.java, src/main/java/edu/cornell/kfs/concur/batch/service/ConcurRequestExtractReportService.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestExtractCreatePdpFeedServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestExtractFileServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestExtractReportServiceImpl.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml, src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImplTest.java, src/test/resources/edu/cornell/kfs/concur/batch/service/impl/fixture/simpleContents.txt
Updates to the code so we send a notification email to dfa-travel about the report from a request extract run
=> Kfspts 8510 request extract email

src/main/java/edu/cornell/kfs/concur/batch/report/ConcurBatchReportLineValidationErrorItem.java, src/main/java/edu/cornell/kfs/concur/batch/report/ConcurBatchReportMissingObjectCodeItem.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilder.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractReportServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractValidationServiceImpl.java, src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractCollectorBatchBuilderTest.java
This updates the SAE report file to log more information. It adds several additional fields to the error output, and also groups error lines by Report ID.
=> KFSPTS-8414: Updates to format of SAE report.

src/main/java/edu/cornell/kfs/vnd/document/CuVendorMaintainableImpl.java
There is dependent SQL in PR#156 that needs to go with this code change.
=> KFSPTS-9544: Temporarily cease maintaining information in the PaymentWorks staging table for vendor maintenance edocs.

pom.xml, src/main/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherExtractionHelperServiceImpl.java, src/main/java/edu/cornell/kfs/sys/batch/service/impl/CuAutoDisapproveDocumentsServiceImpl.java, src/main/java/org/kuali/kfs/pdp/businessobject/PaymentDetail.java
This reverts commit fff594091a95a8c723e2f16a08d4eb4a4aff2a70.
=> Revert "KFSPTS-9265 upgrade to 2017-06-01 version of financials (#432)"

pom.xml, src/main/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherExtractionHelperServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/CuAutoClosePurchaseOrderServiceImpl.java, src/main/java/org/kuali/kfs/fp/document/web/struts/CapitalAssetInformationActionBase.java, src/main/webapp/WEB-INF/tags/fp/advanceDeposits.tag
There are also SQL changes for this patch, so the related nonprod-sql PR has to be merged in conjunction with this one.
=> KFSPTS-9271: Upgrade to 2017-06-22 version of Financials.

src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java
Only an update to the existing hard-coded values is being done at this time. We will use a future user story to make this address more easily configurable.
=> KFSPTS-9610: Update payer address in FastTrack file output

pom.xml, src/main/java/org/kuali/kfs/fp/document/web/struts/CapitalAssetInformationActionBase.java, src/main/java/org/kuali/kfs/module/cam/document/service/impl/GlLineServiceImpl.java, src/main/java/org/kuali/kfs/module/purap/document/web/struts/PurchasingActionBase.java, src/main/java/org/kuali/kfs/sys/document/workflow/FinancialSystemSearchableAttribute.java, src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/ObjectCode.xml, src/main/resources/edu/cornell/kfs/pdp/businessobject/datadictionary/PayeeACHAccount.xml, src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml, src/main/webapp/WEB-INF/tags/fp/capitalAssetInfoDetail.tag
NOTE: There are PRs in cu-kfs and nonprod-sql for this change. Please make sure both PRs are good to go before merging.
=> KFSPTS-10067: Upgrade to 2017-09-07 version of financials

src/main/java/edu/cornell/kfs/module/cg/document/validation/impl/AwardExtensionRule.java, src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/Award.xml
Overriding federal pass-through validations and labels
=> KFSPTS 9986

src/main/java/edu/cornell/kfs/coa/document/validation/impl/AccountExtensionRule.java, src/main/java/org/kuali/kfs/coa/document/validation/impl/AccountGlobalRule.java
This fixes an Account document validation bug from the 09/07 patch, as well as an Account Global validation bug that may have predated the patch.
=> KFSPTS-10422: Fix ICR validation on account docs

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/resources/CU-ApplicationResources.properties
=> Remove unused Budget Construction constants and properties

src/main/java/edu/cornell/kfs/concur/ConcurConstants.java, src/main/java/edu/cornell/kfs/concur/service/impl/ConcurAccessTokenServiceImpl.java, src/main/java/edu/cornell/kfs/concur/web/struts/ConcurManageAccessTokenAction.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/java/edu/cornell/kfs/sys/businessobject/WebServiceCredential.java, src/main/java/edu/cornell/kfs/sys/service/WebServiceCredentialService.java, src/main/java/edu/cornell/kfs/sys/service/impl/WebServiceCredentialServiceImpl.java, src/main/resources/edu/cornell/kfs/sys/cu-ojb-sys.xml
This reverts commit 1651cf68e8129ce3a32625fe57da130ba115252b.
=> Reverting KFSPSTS-10646 

src/main/java/edu/cornell/kfs/concur/ConcurConstants.java, src/main/java/edu/cornell/kfs/concur/service/impl/ConcurAccessTokenServiceImpl.java, src/main/java/edu/cornell/kfs/concur/web/struts/ConcurManageAccessTokenAction.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/java/edu/cornell/kfs/sys/businessobject/WebServiceCredential.java, src/main/java/edu/cornell/kfs/sys/service/WebServiceCredentialService.java, src/main/java/edu/cornell/kfs/sys/service/impl/WebServiceCredentialServiceImpl.java, src/main/resources/edu/cornell/kfs/sys/cu-ojb-sys.xml
Fix issue with active parameter constants in the ConcurTokenService.
=> KFSPTS 10646 patch

src/main/java/edu/cornell/kfs/module/purap/document/validation/impl/CuPurchaseOrderAmendmentAccountValidation.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/CuPurchaseOrderAction.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/CuPurchaseOrderForm.java, src/main/java/edu/cornell/kfs/module/purap/service/impl/CuPurchaseOrderAmendmentAccountingLineRuleHelperServiceImpl.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml, src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/PurchaseOrderAmendmentDocument.xml, src/main/resources/edu/cornell/kfs/module/purap/document/validation/configuration/PurapValidatorDefinitions.xml, src/main/resources/edu/cornell/kfs/module/purap/document/validation/configuration/PurchaseOrderAmendmentValidation.xml
This is a fixed version of the #495 code changes.
=> KFSPTS-10604: Allow expired accounts on POA documents

src/main/java/edu/cornell/kfs/gl/batch/service/impl/CuPosterServiceImpl.java
This method override is nearly identical to foundation code, it was just changed to avoid inserting the continuation-account warning into the errors list. This was necessary in order to allow ICR continuation-account-related entries to post, due to the Poster treating these types of warnings as errors.
I will be providing a description of the problem to Cathy, so that she can move forward with reporting this bug to KualiCo.
=> KFSPTS-10774: Fix ICR continuation account handling

pom.xml, src/main/java/org/kuali/kfs/fp/document/web/struts/CapitalAssetInformationActionBase.java, src/main/java/org/kuali/kfs/module/purap/document/PurchasingAccountsPayableDocument.java, src/main/java/org/kuali/kfs/module/purap/document/PurchasingDocumentBase.java, src/main/java/org/kuali/kfs/module/purap/document/web/struts/PurchasingActionBase.java, src/main/webapp/WEB-INF/web.xml
NOTE: There are PRs for this in both cu-kfs and nonprod-sql. Please make sure both are good to go before merging them.
Some of the overlays have also been updated to account for cleanup and other improvements in the base KFS files. Please let me know if you find any problematic changes in those overlays.
=> KFSPTS-10764: Upgrade to 2017-10-19 version of financials

src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksDtoToPaymentWorksVendorConversionServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java
This reverts commit 7bd29355b3fad94e0a3133e36f4f2dbb4878052d.
=> Revert "KFSPTS-11065: Fix issue with Remit and Bank Address construct being c… (#520)"

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/Account.xml
Please let me know if there is a number that would be better for the length.
=> KFSPTS 11582 Increase the Length of the Account Extension Fields in the Lookup Results 

src/main/java/edu/cornell/kfs/vnd/document/CuVendorMaintainableImpl.java
This reverts commit 38cf5969cdd875ce2bbadcaebdbbff5ed758ce1a.
=> Revert "KFSPTS-11657: PMW changes to track approve-disapprove action on PVEN.… (#554)"

src/main/java/edu/cornell/kfs/krad/service/impl/CuAttachmentServiceImpl.java, src/test/java/edu/cornell/kfs/krad/service/impl/CuAttachmentServiceImplTest.java, src/test/resources/edu/cornell/kfs/krad/service/fixture/error.txt
Please don't merge this yet, still in local validation
=>  KFSPTS-10829 adding logging to attachment service, and update tests to use mockito

src/main/webapp/WEB-INF/tags/module/ar/contractsGrantsInvoiceSummaryResultContent.tag, src/main/webapp/jsp/module/ar/FederalFinancialReport.jsp
This is a fix we have had in the CGB environment and is needed in develop for turning on CGB in DEV.
=> KFSPTS-11759 KFSPTS-10229 customize cgb/ar pages to use CuAward instead of Award

src/main/webapp/WEB-INF/web.xml
This reverts commit ef83654d8be1c05cc71fa7700871df5eca832d38.
=> Revert "KFSPTS-8197 enable java melody system actions (#409)"

src/main/java/edu/cornell/kfs/module/ezra/service/impl/EzraServiceImpl.java, src/main/resources/edu/cornell/kfs/module/ezra/cu-spring-ezra.xml
I have attempted to use the WorkflowDocumentService for routing within the EzraServiceImpl
=> KFSPTS-12304: Workaround for Award eDocs Exception 

src/main/java/edu/cornell/kfs/module/ezra/service/impl/EzraServiceImpl.java, src/main/resources/edu/cornell/kfs/module/ezra/cu-spring-ezra.xml
This reverts commit a1390a83b60cdd8e670befd36ea0049d6a359901.
Will recommit with changes to fix the NPE in base code.
=> Revert "KFSPTS-12304: Workaround for Award eDocs Exception  (#601)"

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java, src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java, src/main/java/edu/cornell/kfs/pmw/batch/dataaccess/PaymentWorksVendorDao.java, src/main/java/edu/cornell/kfs/pmw/batch/dataaccess/impl/PaymentWorksVendorDaoJdbc.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksBatchUtilityServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksDtoToPaymentWorksVendorConversionServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorPayeeAchServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java, src/main/resources/edu/cornell/kfs/pmw/batch/businessobject/datadictionary/PaymentWorksVendor.xml, src/main/resources/edu/cornell/kfs/pmw/cu-ojb-pmw.xml
This is not quite ready to be merged yet since I'm still validating locally. However, I wanted to go ahead and open up a PR for this, in case someone has cycles to review this to make sure it's meeting the expected functionality.
=> KFSPTS-11963: Add PMW column for supplier upload status

src/main/java/edu/cornell/kfs/pmw/batch/dataaccess/impl/PaymentWorksVendorDaoJdbc.java
- Refactored to eliminate duplicate code
- Using JDBC PreparedStatement
- Would it be more efficient to use an ORM like OJB or an existing Class/Library?
=> KFSPTS-12638: Update PMW Vendor DAO class to use secure parameters

src/main/java/edu/cornell/kfs/module/ar/document/service/impl/CuContractsGrantsInvoiceDocumentServiceImpl.java, src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml
=> KFSPTS-12656 Customize CGI Doc Service to default to Last Modified Date 

src/main/java/com/rsmart/kuali/kfs/cr/batch/service/impl/StaleCheckExtractServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurStandardAccountingExtractServiceImpl.java, src/main/java/edu/cornell/kfs/fp/batch/service/impl/AdvanceDepositServiceImpl.java, src/main/java/edu/cornell/kfs/fp/batch/service/impl/CreateAccountingDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/receiptProcessing/service/impl/ReceiptProcessingServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/PayeeACHAccountExtractServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksBatchUtilityServiceImpl.java, src/main/java/edu/cornell/kfs/sys/util/LoadFileUtils.java, src/main/java/edu/cornell/kfs/tax/service/impl/TaxProcessingServiceImpl.java, src/main/java/edu/cornell/kfs/vnd/batch/service/impl/VendorBatchServiceImpl.java, src/main/java/edu/cornell/kfs/vnd/batch/service/impl/VendorInactivateConvertBatchServiceImpl.java, src/test/java/edu/cornell/kfs/sys/util/LoadFileUtilsTest.java
This is ready for code review, however, it should not be merged till after the stale checks code is ready to move to master
=>  KFSPTS-10399 create shared safelyLoadFileBytes utility

src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalPreRules.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalRule.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java, src/main/resources/CU-ApplicationResources.properties
This reverts commit 756ae9075f4299c667d6d675f496f0d63568d1a7.
=> Revert "KFSPTS-13778: More fixes for Sub-Account Global (#673)"

src/main/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriod.java, src/test/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriodSTest.java
TimeBasedBillingPeriod.java has been done via an overlay as the Jira suggests we will contribute this back to KualiCo.  I added a LOG object, and updated  determineStartDateByFrequency.  Everything else in TimeBasedBillingPeriod is as it is in base code
=> KFSPTS-13005 creating CU Customization of TimeBasedBillingPeriod

src/main/java/edu/cornell/kfs/coa/businessobject/SubAccountGlobal.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/GlobalIndirectCostRecoveryAccountsRule.java, src/main/java/edu/cornell/kfs/coa/document/validation/impl/SubAccountGlobalRule.java, src/main/java/edu/cornell/kfs/sys/CUKFSPropertyConstants.java, src/main/java/org/kuali/kfs/coa/document/validation/impl/AccountGlobalRule.java
This PR makes a couple fixes to the GSACC validation, most notably with regards to validating the ICR account allocations (and printing appropriate messages when validation fails).
=> KFSPTS-14181 Fixes for GSACC new-sub-account feature

src/main/resources/edu/cornell/kfs/coa/document/datadictionary/SubAccountGlobalMaintenanceDocument.xml
This fix is needed to correct an issue that came up during the KFSPTS-14181 DEV validation.
=> KFSPTS-14389 Fix new-sub-account routing setup for GSACC

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/sys/dataaccess/ActionItemNoteDetailDto.java, src/main/java/edu/cornell/kfs/sys/dataaccess/DocumentMaintenanceDao.java, src/main/java/edu/cornell/kfs/sys/dataaccess/impl/DocumentMaintenanceDaoJdbc.java, src/main/java/edu/cornell/kfs/sys/service/impl/DocumentMaintenanceServiceImpl.java
I've made changes to make each individual document update transactional.  Previously the whole loop of documents to update was transactional.  This should improve performance.
=>  KFSPTS-14446 persist action notes in document requeuer job

pom.xml
Please note there is a note on the user story to update powermockito version, we are already up to date with KualiCo's version
=> KFSPTS-11408 remove easymock dependency

src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java
This reverts commit a39e6cc4b042bdb75398abd3ee7513e6a04736e8.
=> Revert "KFSPTS-15359 update ach address (#776)"

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java, src/main/java/edu/cornell/kfs/pdp/batch/service/CuPayeeAddressService.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuPayeeAddressServiceImpl.java, src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
This code change moves check address values to parameters.
=>  KFSPTS-15359 moving check address values to parameters

pom.xml, src/main/java/edu/cornell/kfs/module/ar/service/impl/CuAREmailServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/businessobject/lookup/CuACHPayeeLookupableHelperServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuAchServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuFormatServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentFileServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuPaymentMaintenanceServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/web/struts/CuFormatAction.java, src/main/java/org/kuali/kfs/pdp/businessobject/PaymentDetail.java, src/main/java/org/kuali/kfs/pdp/businessobject/PaymentGroup.java, src/main/java/org/kuali/kfs/pdp/service/impl/PaymentFileServiceImpl.java, src/main/java/org/kuali/kfs/pdp/web/struts/FormatAction.java, src/main/java/org/kuali/kfs/sec/document/web/SecAccountingLineGroupImpl.java, src/main/java/org/kuali/kfs/sys/web/struts/KualiAccountingDocumentActionBase.java, src/main/webapp/WEB-INF/tags/module/purap/camsLocation.tag
A lot of the changes in this release were code-formatting-related ones. I have tried to incorporate that cleanup into our overlays and extensions as needed, though there were a few formatting changes that were not practical to bring in and there were a few that been retroactively added from prior changes. Some of the format updates were also not fully adhering to how the formatting is supposed to be set up in other places (especially with regards to operators on line breaks); I've kept the new formatting close to what KualiCo currently has for the affected files.
=> KFSPTS-15426 Upgrade to 2019-04-11 version of financials

src/main/java/cynergy/CynergyKimFeed.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSParameterKeyConstants.java, src/main/java/edu/cornell/kfs/sys/batch/RunKimFeedStep.java, src/main/java/util/SimpleCommandLineParser.java, src/main/resources/edu/cornell/kfs/sys/cu-spring-sys.xml
This is an updated version of the #792 PR changes. This revision of the feature fixes an issue where CynergyKimFeed was using an older outdated version of the relevant JDBC driver.
Note that this PR copies the KIM feed code into KFS with only minimal changes, so the code does not adhere to our current coding standards at the moment. We have a follow-up PR that will focus on refactoring the KIM feed code accordingly.
=> KFSPTS-14985 Import KIM feed to KFS with minimal changes

src/main/java/edu/cornell/kfs/fp/CuFPParameterConstants.java, src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardFlatInputFileType.java, src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardSkippedTransaction.java, src/main/java/edu/cornell/kfs/fp/batch/ProcurementCardTransactionResult.java, src/main/java/edu/cornell/kfs/fp/batch/service/ProcurementCardSkippedTransactionEmailService.java, src/main/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardSkippedTransactionEmailServiceImpl.java, src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml, src/test/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardSkippedTransactionEmailServiceImplTest.java
Please note, there is  a related PR in non prod SQL.  
This code is ready for review now.  However, I don't have an example PCDO file that contains the error condition.  The parent user story does have an example CBCP file, and this code appears to process that file well.  
I would like to verify this code against a PCDO file before merging this.  So please do NOT merge this yet.
=>  KFSPTS-15528  Skip transaction type 0108 on PCDO and CBCP

src/main/java/edu/cornell/kfs/module/ar/document/validation/impl/AutoApproveDisabledSuspensionCategory.java, src/main/java/edu/cornell/kfs/module/cg/businessobject/AwardAccountExtendedAttribute.java, src/main/java/edu/cornell/kfs/module/cg/businessobject/AwardExtendedAttribute.java, src/main/java/edu/cornell/kfs/module/cg/document/CuAwardMaintainableImpl.java, src/main/java/edu/cornell/kfs/module/cg/document/validation/impl/AwardExtensionRule.java, src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/sys/CUKFSKeyConstants.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml, src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/Award.xml, src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/AwardAccount.xml, src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/AwardAccountExtendedAttribute.xml, src/main/resources/edu/cornell/kfs/module/cg/businessobject/datadictionary/AwardExtendedAttribute.xml, src/main/resources/edu/cornell/kfs/module/cg/cu-ojb-cg.xml, src/main/resources/edu/cornell/kfs/module/cg/document/datadictionary/AwardMaintenanceDocument.xml, src/test/java/edu/cornell/kfs/module/ar/document/validation/impl/AutoApproveDisabledSuspensionCategoryTest.java
Please don't merge this yet.  There are some open questions to Janet and I need to do some more local validation.  When taking a look at AwardMaintenanceDocument, please note I couldn't get  AwardMaintenanceDocument-Accounts section to work using the standard data dictionary over rides.   It might be easier to discuss verbally what I was finding.
I am opening this up for code review to get feedback on AwardMaintenanceDocument-Accounts section and the code in general.  Please do NOT merge this code yet.
=> KFSPTS-15573 adding more award extended attributes

pom.xml, src/main/java/org/kuali/kfs/module/ld/document/SalaryExpenseTransferDocument.java, src/main/resources/edu/cornell/kfs/gl/cu-spring-gl.xml, src/main/resources/edu/cornell/kfs/gl/document/workflow/GeneralLedgerTransferDocument.xml, src/main/resources/edu/cornell/kfs/module/ld/businessobject/datadictionary/PositionData.xml, src/main/resources/edu/cornell/kfs/module/ld/cu-ojb-ld.xml, src/main/webapp/WEB-INF/tags/kr/htmlControlAttribute.tag, src/test/java/edu/cornell/kfs/fp/document/service/impl/CuDisbursementVoucherTaxServiceImplTest.java
NOTE: This release introduces a new General Ledger Transfer (GLT) document. I've added its new doc type XML to this PR to make it more convenient to get and ingest the XML. (The base financials code has the GLT doc type embedded in a larger doc type XML file, so that larger file is not feasible to ingest because it would affect several other doc types as well.) If you think the doc type should be placed elsewhere, please let me know.
=> KFSPTS-15981 Upgrade to 2019-05-23 version of financials

src/main/resources/edu/cornell/kfs/coa/businessobject/datadictionary/SubFundProgram.xml
This reverts commit ca7e1056dab7c26c80d3d9a84c5106f46238e10b.
=> Revert "KFSPTS-15510 Fix sub-fund program description max length (#823)"

src/main/java/edu/cornell/kfs/rass/batch/AwardTranslationDefinition.java
There are awards in KFS that don't have a fund manager, so the batch job needs to check that on the update step.
=> KFSPTS-16311 fix RASS job fund manager handling

src/main/java/edu/cornell/kfs/rass/batch/RassOrganizationConverterForAward.java, src/main/java/edu/cornell/kfs/rass/batch/RassOrganizationConverterForProposal.java, src/main/java/edu/cornell/kfs/rass/batch/RassProjectDirectorConverter.java, src/main/java/edu/cornell/kfs/rass/batch/RassPropertyDefinition.java, src/main/java/edu/cornell/kfs/rass/batch/RassValueConverter.java, src/main/java/edu/cornell/kfs/rass/batch/RassValueConverterBase.java, src/main/java/edu/cornell/kfs/rass/batch/service/impl/RassUpdateServiceImpl.java, src/main/resources/edu/cornell/kfs/rass/cu-spring-rass.xml, src/test/java/edu/cornell/kfs/rass/batch/RassValueConverterBaseTEst.java, src/test/java/edu/cornell/kfs/rass/batch/RassValueConverterBaseTest.java, src/test/java/edu/cornell/kfs/rass/batch/xml/fixture/RassXmlAgencyEntryFixture.java
This is ready for review.  Please don't merge tyet though.  I have an open question to Janet concerning Grant number
=> KFSPTS-16436 implement truncating for RASS integration

src/main/java/edu/cornell/kfs/module/ar/CuArPropertyConstants.java, src/main/java/edu/cornell/kfs/module/ar/document/service/impl/CuContractsGrantsInvoiceDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/cg/businessobject/AwardExtendedAttribute.java
This is a re-work of the original change set to set the purchase order placeholder differently depending on the invoice option.
=> KFSPTS-16483: Additional CGB Invoice placeholders for Award and Award Account.

src/main/java/org/kuali/kfs/pdp/businessobject/ACHBank.java, src/test/java/org/kuali/kfs/pdp/businessobject/ACHBankTest.java
We were not able to reproduce this problem locally, however adding these setter should get us past these problems.  I added some log statements in hopes to help future debugging needs
=> KFSPTS-16975 adding bank state and postal code setters to ACHBank, also added logging to help with future debugging

src/main/java/org/kuali/kfs/sys/context/BatchStepRunner.java
This PR overlays BatchStepRunner from base KFS code with the addition of including PojoPlugin init call
I was able to do a trial run of this change in the emergency environment, and things seemed to work successfully
=> KFSPTS-16975 create CU customization of BatchStepRunner

src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java
This reverts commit d06d5f1d3a635ce64cda9f33dc03bd36f9d9ae1f.
=> Revert "KFSPTS-16448: Have FastTrack mod output invoice number and invoice date for DVs when that data exists. (#872)"

src/main/java/edu/cornell/kfs/sys/CUKFSConstants.java, src/main/java/edu/cornell/kfs/tax/CUTaxConstants.java, src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRow1099Processor.java, src/main/resources/edu/cornell/kfs/tax/batch/Default1099TaxOutputDefinition.xml, src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml
Several changes were necessary for the 1099 file generation this year, especially regarding the ability to display country information for foreign addresses. The KFSPTS-16824 sub-task summarizes the extent of the needed changes.
=> KFSPTS-16112 Changes to 1099 tax file format

src/main/java/edu/cornell/kfs/module/cam/batch/service/impl/CuAssetDepreciationServiceImpl.java
I brought in runDepreciation() from AssetDepreciationServiceImpl in base code into CuAssetDepreciationServiceImpl and changed one line to use java.sql.Date instead of java.util.Date.
=> KFSPTS-17761 fixing asset depreciation batch job

src/main/java/edu/cornell/kfs/pdp/service/impl/CuPendingTransactionServiceImpl.java, src/main/resources/edu/cornell/kfs/pdp/cu-spring-pdp.xml
@cah292  This makes updates as requested in the user story.  I wasn't able to verify this fixes the bug locally.  I think this scenario is going to need to be tested in dev unless you know of steps to verify locally
=> KFSPTS-17693 update pay reqs when related checks are canceled

src/main/java/edu/cornell/kfs/fp/batch/service/impl/CuDisbursementVoucherDocumentGenerator.java, src/main/java/edu/cornell/kfs/fp/batch/xml/DisbursementVoucherPaymentInformationXml.java, src/main/resources/edu/cornell/kfs/fp/cu-spring-fp.xml
Please see https://jira.cornell.edu/browse/KFSPTS-18181 for the business rules we are attempting to implement.
Some error handling and edge case handling is deferred to future user stories.  I think we also want to defer unit testing till later
=> KFSPTS-18181 adding vendor address ID to create accounting document Job DV processing

src/main/java/org/kuali/kfs/module/ar/businessobject/InvoiceGeneralDetail.java
This commit brings in InvoiceGeneralDetail into our overlay.  The only edit to the class is where kualiModuleService is defined, and the comments above it.
=> KFSPTS-18320 Backport FINP-6611

src/main/java/edu/cornell/kfs/pdp/CUPdpKeyConstants.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuPdpEmailServiceImpl.java, src/main/resources/CU-ApplicationResources.properties
This reverts commit 6cce08bc13476aa0bac70e7d6496c8f9e9a996b0.
=> Revert "KFSPTS-16448: Have FastTrack mod output invoice number and invoice date to FastTrack file and advices for DVs when that data exists. (#888)"

src/main/java/edu/cornell/kfs/coa/businessobject/CuAccountGlobal.java
This was implemented per notes on KFSPTS-17596
=> KFSPTS-17596 fixing account global to handle sub fund

pom.xml, src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurDTOMarshalTest.java, src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurEventNotificationListDTOTest.java
…e (#941)"
This reverts commit 18ac5808b3ede3310c4a704e8660d7c99a5dcb20.
=> Revert "KFSPTS-17530 Update cu-kfs POM and other files for Java 11 use (#941)"

src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherConstants.java, src/main/java/edu/cornell/kfs/pdp/CUPdpKeyConstants.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuPdpEmailServiceImpl.java, src/main/resources/CU-ApplicationResources.properties, src/test/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImplTest.java
This reverts commit 6fe5b0358092a1466e38993374c5bdcdd79421da.
=> Revert "KFSPTS-16448: Mod to output DV invoice number and invoice date to advices and check stub note text when that data exists. (#950)"

pom.xml, src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurDTOMarshalTest.java, src/test/java/edu/cornell/kfs/concur/eventnotification/rest/xmlObjects/ConcurEventNotificationListDTOTest.java, src/test/java/edu/cornell/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImplTest.java, src/test/java/edu/cornell/kfs/module/ld/batch/service/impl/CuFileEnterpriseFeederHelperServiceImplTest.java, src/test/java/edu/cornell/kfs/module/ld/batch/service/impl/CuFileEnterpriseFeederServiceImplTest.java, src/test/java/edu/cornell/kfs/module/receiptProcessing/service/CuReceiptProcessingServiceImplPositiveTest.java
PR created to test the j11 jenkins unit tests job
=> KFSPTS-17530 Update KFS for running on Java 11

src/main/java/edu/cornell/kfs/module/ar/batch/service/CuVerifyBillingFrequencyService.java, src/main/java/edu/cornell/kfs/module/ar/batch/service/impl/CuVerifyBillingFrequencyServiceImpl.java, src/main/java/edu/cornell/kfs/module/ar/service/impl/CuContractsGrantsInvoiceCreateDocumentServiceImpl.java
This reverts commit 70b1652edd2325ae2a65432eca751743f85ce82d.
=> Revert "KFSPTS-17450: Fix to make lastBilledDate today for first predetermined or milestone invoice created via batch or manually. (#946)"

src/main/java/edu/cornell/kfs/fp/document/CuDisbursementVoucherConstants.java, src/main/java/edu/cornell/kfs/pdp/CUPdpKeyConstants.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java, src/main/java/edu/cornell/kfs/pdp/service/impl/CuPdpEmailServiceImpl.java, src/main/resources/CU-ApplicationResources.properties, src/test/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImplTest.java
This reverts commit 3985ec4844f47f749c5251f436f2fac877642aff.
=> Revert "KFSPTS-16448: Mod to output DV invoice number and invoice date to advices and check stub note text when that data exists. (#967)"

src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksConstants.java, src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksKeyConstants.java, src/main/java/edu/cornell/kfs/pmw/batch/PaymentWorksNewVendorCreateKfsVendorStep.java, src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksFieldMapping.java, src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java, src/main/java/edu/cornell/kfs/pmw/batch/businessobject/options/PaymentWorksCustomAttributeValueToUseValuesFinder.java, src/main/java/edu/cornell/kfs/pmw/batch/service/PaymentWorksFormModeService.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksDtoToPaymentWorksVendorConversionServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksFormModeServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksWebServiceCallsServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/xmlObjects/PaymentWorksCustomFieldDTO.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/pmw/batch/businessobject/datadictionary/PaymentWorksFieldMapping.xml, src/main/resources/edu/cornell/kfs/pmw/batch/document/datadictionary/PaymentWorksFieldMappingMaintenanceDocument.xml, src/main/resources/edu/cornell/kfs/pmw/cu-ojb-pmw.xml, src/main/resources/edu/cornell/kfs/pmw/cu-spring-pmw.xml, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksDtoToPaymentWorksVendorConversionServiceImplTest.java, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksFormModeServiceImplTtest.java, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImplTest.java, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceTest.java
This is not ready to be merged yet, as I have some open questions to payment works on some custom fields.  Also, I have some debugging code in place that I will remove after my questions have been answered.
There is a related non prod SQL PR associated with this change.
In addition to changes needed for the new fields, I have fixed an NPE bug that was discovered in PaymentWorksVendorToKfsVendorDetailConversionServiceImpl during earlier testing, The bug was in truncateValueToMaxLength, and I made use of StringUtils to fix this bug.
I am opening this up for code review so I can get feedback  while I am waiting for a PMW response
=> KFSPTS-18905 pmw foreign vendors step 2 adding new fields

src/main/java/edu/cornell/kfs/module/cam/CuCamsConstants.java, src/main/java/edu/cornell/kfs/module/cam/document/service/CuAssetService.java, src/main/java/edu/cornell/kfs/module/cam/document/service/impl/CuAssetServiceImpl.java, src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java, src/main/java/edu/cornell/kfs/module/cam/web/filter/CuCapAssetInventoryServerAuthFilter.java, src/main/resources/edu/cornell/kfs/module/cam/cu-spring-cam.xml
- Added API call to update the Capital Asset based on the Capital Asset Number (Primary Key)
- Added method to update Capital Asset conditionCode, buildingNumber, buildingRoomNumber, lastInventoryDate to CuAssetServiceImpl
- Updated /conditions API call to include both code and name
- Updated Capital Asset Lookup to include capitalAssetNumber and organizationName
=> KFSPTS-19231 KFS API for Capital Asset Inventory Update

src/main/java/edu/cornell/kfs/module/cam/web/filter/CuCapAssetInventoryServerAuthFilter.java
As requested, I added cognito_access_token to the request.  I did run into a problem with the netid field not being populated in the servlet request.  I am not sure if that is related to this change, or a bug with a previous change.
=> KFSPTS-19579 added cognito_access_token to the request in hopes of solving session time out issue

src/main/java/edu/cornell/kfs/pmw/batch/businessobject/PaymentWorksVendor.java, src/main/java/edu/cornell/kfs/pmw/batch/service/PaymentWorksVendorSupplierDiversityService.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksNewVendorRequestsServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorSupplierDiversityServiceImpl.java, src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImpl.java, src/main/resources/edu/cornell/kfs/pmw/cu-ojb-pmw.xml, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorSupplierDiversityServiceImplTest.java, src/test/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImplTest.java
Please note, there is a related SQL PR now
=> KFSPTS-19821 handle state diversities without federal diversity and fix typos

src/main/java/edu/cornell/kfs/module/cam/rest/resource/CuCapAssetInventoryApiResource.java
There are PRs for this in both cu-kfs and CapAsset-React-Website.
=> KFSPTS-19435 Improve API for CapAsset update operation

src/main/java/edu/cornell/kfs/tax/CUTaxConstants.java, src/main/java/edu/cornell/kfs/tax/FormTypes1099.java, src/main/java/edu/cornell/kfs/tax/businessobject/ObjectCodeBucketMapping.java, src/main/java/edu/cornell/kfs/tax/businessobject/options/FormType1099ValuesFinder.java, src/main/resources/edu/cornell/kfs/tax/businessobject/datadictionary/ObjectCodeBucketMapping.xml, src/main/resources/edu/cornell/kfs/tax/cu-ojb-tax.xml, src/main/resources/edu/cornell/kfs/tax/document/datadictionary/ObjectCodeBucketMappingMaintenanceDocument.xml, src/test/java/edu/cornell/kfs/tax/FormTypes1099Test.java
Please note there is a related non-prod-sql PR that should be merged with this.
=> KFSPTS-19988 adding 1099 form type to labor object code to 1099 box mapping

src/main/java/edu/cornell/kfs/module/purap/document/service/impl/CuB2BPurchaseOrderSciquestServiceImpl.java
Note that this was based on the existing ShipPayTerms.
=> KFSPTS-20884 add Shipping Title to PO cxml

src/main/java/edu/cornell/kfs/pmw/batch/service/impl/PaymentWorksVendorToKfsVendorDetailConversionServiceImpl.java, src/main/java/edu/cornell/kfs/vnd/businessobject/VendorDetailExtension.java, src/main/java/edu/cornell/kfs/vnd/businessobject/options/EinvoiceIndicatorValuesFinder.java, src/main/resources/edu/cornell/kfs/vnd/businessobject/datadictionary/VendorDetailExtension.xml, src/main/resources/edu/cornell/kfs/vnd/cu-ojb-vnd.xml, src/test/java/edu/cornell/kfs/vnd/businessobject/options/EinvoiceIndicatorValuesFinderTest.java, src/test/java/edu/cornell/kfs/vnd/fixture/VendorDetailExtensionFixture.java, src/test/resources/edu/cornell/kfs/krad/service/impl/VendorTest.xml
Please note there is a related PR in https://github.com/CU-CommunityApps/nonprod-sql/pull/925
=> KFSPTS-21309 update einvoiceindicator to support None, SFTP, or Web

src/main/java/org/kuali/kfs/module/ar/document/web/struts/PaymentApplicationAdjustmentAction.java
This commit adds a new overlay PaymentApplicationAdjustmentAction, it is base code's version of the file for our current version of KFS and then adds on the change committed with https://github.com/KualiCo/financials/commit/52f20bfe0520cb4c0db62d4b678844d8974336c5 .
We only made changes to the route function as shown in the KualiCo fix.
=> KFSPTS-21426 backport FINP 7302

src/main/java/edu/cornell/kfs/module/ar/CuArConstants.java, src/main/java/edu/cornell/kfs/module/ar/batch/service/CuVerifyBillingFrequencyService.java, src/main/java/edu/cornell/kfs/module/ar/batch/service/impl/CuVerifyBillingFrequencyServiceImpl.java, src/main/java/edu/cornell/kfs/module/ar/service/CuContractsGrantsInvoiceCreateDocumentService.java, src/main/java/edu/cornell/kfs/module/ar/service/impl/CuContractsGrantsInvoiceCreateDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/ar/web/struts/CuContractsGrantsInvoiceSummaryAction.java, src/main/java/org/kuali/kfs/integration/cg/ContractsAndGrantsBillingAward.java, src/main/java/org/kuali/kfs/module/ar/batch/service/impl/VerifyBillingFrequencyServiceImpl.java, src/main/java/org/kuali/kfs/module/ar/businessobject/BillingPeriod.java, src/main/java/org/kuali/kfs/module/ar/businessobject/LetterOfCreditBillingPeriod.java, src/main/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriod.java, src/main/java/org/kuali/kfs/module/cg/businessobject/Award.java, src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml, src/main/webapp/WEB-INF/institutional-struts-config.xml, src/test/java/org/kuali/kfs/module/ar/businessobject/TimeBasedBillingPeriodSTest.java
This reverts commit 70a46b482af1f8efd8927fdf24c0fed0e6f7aaa4.
=> Revert "KFSPTS-21538 remove KFSPTS-14970 (#1110)"

src/main/java/org/kuali/kfs/module/ar/businessobject/lookup/ContractsGrantsPaymentHistoryReportLookupableHelperServiceImpl.java
I brought in ContractsGrantsPaymentHistoryReportLookupableHelperServiceImpl as a new overlay item, then back-ported FINP-7396
=> KFSPTS-21430 back-port FINP-7396

src/main/java/edu/cornell/kfs/module/ar/document/service/impl/CuInvoicePaidAppliedServiceImpl.java, src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml
This PR backports FINP-7572 from kualico, the pull request for this change can be found here: https://github.com/KualiCo/financials/pull/4401 .  Note, we don't typically back port unit test code.
=> KFSPTS-22158 backport FINP-7572

src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java, src/main/java/edu/cornell/kfs/tax/businessobject/TransactionDetail.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPdpBuilder.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPrintProcessor.java, src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml, src/main/resources/edu/cornell/kfs/tax/batch/DefaultTransactionRowOutputDefinition.xml, src/main/resources/edu/cornell/kfs/tax/cu-ojb-tax.xml
(1167)
This reverts commit 0e3be83d5677adc795cc24f382c3fba5cf44dd2d.
=> Revert "KFSPTS-22312 Tax Add 3 Fields to Transaction Detail Report"

src/main/java/org/kuali/kfs/kns/util/CookieUtils.java, src/main/webapp/META-INF/context.xml, src/main/webapp/WEB-INF/web.xml
This change allows for better cookie persistence when using eshop
=> KFSPTS-22552 add cookie processor setting to context.xml

src/main/java/edu/cornell/kfs/tax/batch/CUTaxBatchConstants.java, src/main/java/edu/cornell/kfs/tax/businessobject/TransactionDetail.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TaxTableRow.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowDvBuilder.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPRNCBuilder.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPdpBuilder.java, src/main/java/edu/cornell/kfs/tax/dataaccess/impl/TransactionRowPrintProcessor.java, src/main/resources/edu/cornell/kfs/tax/batch/DefaultTaxDataDefinition.xml, src/main/resources/edu/cornell/kfs/tax/batch/DefaultTransactionRowOutputDefinition.xml, src/main/resources/edu/cornell/kfs/tax/cu-ojb-tax.xml
This reverts commit c7e9a8ebbc649ec3976a27c3f0dd4cf6b3dcd841.
=> Revert "KFSPTS-22312 Add Fields to Tax Output (#1196)"

src/main/java/org/kuali/kfs/sys/document/workflow/FinancialSystemSearchableAttribute.java
This reverts commit 8e1e2aec193391b626a5bebb1cdfffbf9e34ff05.
=> Revert "KFSPTS-23032: Log additional information to analyze NullPointerException email. (#1203)"

src/main/java/org/kuali/kfs/module/ar/ArKeyConstants.java, src/main/java/org/kuali/kfs/module/ar/document/service/ContractsGrantsInvoiceDocumentService.java, src/main/java/org/kuali/kfs/module/ar/document/service/impl/ContractsGrantsInvoiceDocumentServiceImpl.java, src/main/java/org/kuali/kfs/module/ar/document/validation/impl/ContractsGrantsInvoiceDocumentValidation.java, src/main/java/org/kuali/kfs/module/ar/service/impl/ContractsGrantsInvoiceCreateDocumentServiceImpl.java, src/main/resources/edu/cornell/kfs/module/ar/cu-ar-resources.properties, src/main/resources/org/kuali/kfs/module/ar/document/validation/configuration/AccountsReceivableValidators.xml
Initial attempt to see if unit tests pass or fail for the FINP-5295 backport.
=> KFSPTS-23439: Backport FINP-5295 onto KualiCo patch 2021-01-21 versions of the same files.

src/main/java/org/kuali/kfs/module/ar/batch/service/impl/VerifyBillingFrequencyServiceImpl.java
This PR makes one minor follow-up change to the rebased KEW upgrade code; namely, a minor update to a class import.
The rebase process did not encounter any merge conflicts.
Note that this is keyed according to the sub-task, since user story KFSPTS-23538 already has an associated commit.
=> KFSPTS-23580 Follow-up changes for 2022-01-19 KEW rebase

README.md
This PR is only meant for testing the merge of a mock emergency fix, as part of the dry-run testing of the move-KEW-to-master process. Chad H will merge this to a testing-only branch and not to the actual develop branch.
=> This is only a test change

src/main/java/org/kuali/kfs/module/purap/document/dataaccess/impl/PaymentRequestDaoOjb.java, src/main/java/org/kuali/kfs/module/purap/document/service/impl/PaymentRequestServiceImpl.java
This PR backports the FINP-8283 fix, which is a follow-up fix for the FINP-8270 changes that we had backported in a previous PR.
=> KFSPTS-24344 Backport FINP-8283 dup-invoice-check fix

src/main/java/org/kuali/kfs/kew/actionrequest/service/impl/ActionRequestServiceImpl.java
This reverts commit 42521fc4fc6a4895241eed1dbb2f46e8b8c64cc3.
=> Revert "KFSPTS-24455: Backport FINP-8326 Route log is not reflecting requeued document changes (#1267)"

src/main/java/org/kuali/kfs/kew/engine/BlanketApproveEngine.java
I brought in the overlay for BlanketApproveEngine and then added the customizations we added on https://github.com/CU-CommunityApps/cornell_customizations/blob/master/src/main/java/org/kuali/rice/kew/engine/BlanketApproveEngine.java
=> KFSPTS-24745 Reimplement customization to have blanket approvals generate FYI requests

src/main/java/edu/cornell/kfs/module/purap/document/CuPaymentRequestDocument.java
We sometimes encounter OptimisticLockExceptions when the eInvoice Route Job routes multiple PREQs for the same PO in quick succession. These documents are all trying to make updates to the same PO document during routing, and some of the threads appear to be retrieving and updating the PO before one of the other threads has finished doing so.
This PR fixes the issue by leveraging KEW's lock-route-header functionality. KEW allows for a document to also lock some other documents during routing, which can be specified via a particular method. An appropriate override of this method has been added to the PREQ document so that it will also lock the document representing the "current" version of the Purchase Order.
=> KFSPTS-24844 Fix bulk-routing many PREQs for same PO

src/main/java/edu/cornell/kfs/module/purap/CUPurapConstants.java, src/main/java/edu/cornell/kfs/module/purap/CUPurapPropertyConstants.java, src/main/java/edu/cornell/kfs/module/purap/businessobject/JaggaerRoleLinkMapping.java, src/main/java/edu/cornell/kfs/module/purap/identity/JaggaerKimTypeService.java, src/main/java/edu/cornell/kfs/module/purap/identity/JaggaerPermissionTypeService.java, src/main/java/edu/cornell/kfs/module/purap/identity/JaggaerRoleTypeService.java, src/main/java/edu/cornell/kfs/module/purap/service/JaggaerRoleLinkMappingService.java, src/main/java/edu/cornell/kfs/module/purap/service/impl/JaggaerRoleLinkMappingServiceImpl.java, src/main/resources/edu/cornell/kfs/module/purap/cu-ojb-purap.xml, src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml
This adds the framework for Jaggaer roles to links from KFS
there is a related non-prod-sql PR that needs to be reviewed at the same as this
=> KFSPTS-25480 new jaggaer role to varous links mapping

src/main/java/edu/cornell/kfs/module/purap/JaggaerConstants.java, src/main/java/edu/cornell/kfs/module/purap/service/impl/JaggaerRoleServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/web/struts/JadgaerAdminB2BAction.java, src/main/java/edu/cornell/kfs/module/purap/web/struts/JaggaerAdminB2BAction.java, src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml, src/main/webapp/WEB-INF/institutional-struts-config.xml, src/test/java/edu/cornell/kfs/module/purap/service/impl/JaggaerRoleServiceImplTest.java
Please note there is a related non-prod SQL PR.  These two PR should be merged at the same time
=> KFSPTS-25536 implement Jaggaer admin link

src/main/java/edu/cornell/kfs/module/purap/web/struts/ContractsPlusB2BAction.java, src/main/webapp/WEB-INF/institutional-struts-config.xml
Please note, there is also a related PR in non-prod-sql, please don't merge this PR till both are ready
=> KFSPTS-25494 enable contracts plus link

src/main/java/edu/cornell/kfs/concur/ConcurConstants.java, src/main/java/edu/cornell/kfs/concur/ConcurParameterConstants.java, src/main/java/edu/cornell/kfs/concur/batch/ConcurEventNotificationV2ProcessingStep.java, src/main/java/edu/cornell/kfs/concur/batch/service/ConcurEventNotificationV2ReportService.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurEventNotificationV2ReportServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurRequestV4ServiceImpl.java, src/main/java/edu/cornell/kfs/concur/businessobjects/ConcurEventNotificationProcessingResultsDTO.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/concur/cu-spring-concur.xml
this is NOT ready for review yet
=> KFSPTS-22328 create concur event notification v2 results report

src/test/java/edu/cornell/kfs/module/ld/document/service/impl/CuLaborPendingEntryConverterServiceImplTest.java, src/test/java/org/kuali/kfs/sys/fixture/UserNameFixture.java
I changed the user to bs622, who has made recent salary transfer documents in the "R" account range
=> KFSPTS-23784 fix unit tests after utest refresh

src/main/java/edu/cornell/kfs/module/purap/document/dataaccess/impl/CuPaymentRequestDaoOjb.java
The 2022-04-13 financials upgrade added an Invoice Date check to the PREQ creation process, but the related code is passing a `java.time.LocalDate` parameter to the query instead of a `java.sql.Date` parameter. This seems to work fine in KualiCo's environment(s) since they're likely using a newer MySQL JDBC driver; however, our environments are encountering exceptions because our Oracle JDBC driver doesn't recognize the `java.time.*` classes as being valid for SQL date-time purposes.
This PR overrides the problematic method to convert the `java.time.LocalDate` object into a `java.sql.Date` object when adding the Invoice Date criteria to the query. That will at least fix the problem for the short term. In the long term, though, we may want to investigate updating our Oracle JDBC driver …
=> KFSPTS-27531 Fix PREQ date check for Oracle compatibility

src/main/java/edu/cornell/kfs/module/purap/businessobject/options/OrderCompletedValuesFinder.java, src/main/resources/CU-ApplicationResources.properties, src/main/webapp/WEB-INF/tags/module/purap/iWantAdHocRecipients.tag
This reverts commit 98465afd663af3c852de41fc41bea0aa0fbfa9f2.
=> Revert "KFSPTS-27209: I Want Doc update language on ad hoc approver screen. (#1398)"

src/main/java/org/kuali/kfs/sys/context/KFSConfigurer.java
This PR adds a potential fix for running a KFS batch instance on the 2022-06-29 financials code. That patch's Spring-MVC-related changes broke some functionality that normally doesn't set up a servlet context (such as batch processing). To fix the issue, we've backported KualiCo's FINP-8867 fix, which initializes a mock/dummy servlet context for such cases.
=> KFSPTS-27854 Backport FINP-8867 batch-related fix

src/main/java/edu/cornell/kfs/module/purap/businessobject/options/OrderCompletedValuesFinder.java, src/main/resources/CU-ApplicationResources.properties, src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/IWantDocument.xml, src/main/webapp/WEB-INF/tags/module/purap/iWantAccountInfo.tag, src/main/webapp/WEB-INF/tags/module/purap/iWantAdHocRecipients.tag, src/main/webapp/WEB-INF/tags/module/purap/iWantNotes.tag, src/main/webapp/WEB-INF/tags/module/purap/iWantOrderCompleted.tag, src/main/webapp/WEB-INF/tags/module/purap/iWantVendor.tag
=> KFSPTS-27209: Update language on I Want Document.

src/main/webapp/WEB-INF/tags/module/purap/iWantNotes.tag, src/main/webapp/WEB-INF/tags/module/purap/iWantVendor.tag, src/main/webapp/jsp/module/purap/IWant.jsp
The functional users have requested additional language changes to the ones already made and applied to the develop branch while validating in DEV.
In order to meet our sprint deadlines for the upcoming patch release, this pull request will be applying those additional changes outlined on sub-task KFSPTS-27969 of original user story KFSPTS-27209 on top of the first set of changes instead of performing our normal process of reverting the original and reapplying.
=> KFSPTS-27209-subtask-KFSPTS-27969: I Want document additional langauage adjustments requested.

src/main/java/edu/cornell/kfs/fp/document/web/struts/CuDisbursementVoucherAction.java, src/main/java/edu/cornell/kfs/module/purap/CUPurapKeyConstants.java, src/main/java/edu/cornell/kfs/module/purap/document/service/IWantDocumentService.java, src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/CuRequisitionAction.java, src/main/resources/edu/cornell/kfs/module/purap/cu-purap-resources.properties, src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml, src/main/resources/institutional-config.properties
NOTE: I'm still waiting on a functional question from the user story. Once I get a response and make any needed follow-up changes, I'll update this PR to make it ready to merge once approved.
=> KFSPTS-27944 Add create-REQS/DV document note to IWNT

src/main/java/edu/cornell/kfs/module/purap/CUPurapConstants.java, src/main/java/edu/cornell/kfs/module/purap/CUPurapParameterConstants.java, src/main/java/edu/cornell/kfs/module/purap/JaggaerConstants.java, src/main/java/edu/cornell/kfs/module/purap/batch/JaggaerGenerateSupplierXmlStep.java, src/main/java/edu/cornell/kfs/module/purap/batch/JaggaerUploadSupplierXmlStep.java, src/main/java/edu/cornell/kfs/module/purap/batch/service/JaggaerGenerateSupplierXmlService.java, src/main/java/edu/cornell/kfs/module/purap/batch/service/JaggaerUploadFileService.java, src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateSupplierXmlServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerUploadFileServiceImpl.java, src/main/resources/edu/cornell/kfs/module/purap/cu-spring-purap.xml, src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateSupplierXmlServiceImplTest.java
Please note there is a related PR in non prod SQL
=> KFSPTS-28264 create base Jaggaer Upload supplier XML job

src/main/java/org/kuali/kfs/kew/api/document/DocumentProcessingQueue.java, src/main/java/org/kuali/kfs/kew/impl/document/DocumentProcessingQueueImpl.java, src/main/resources/edu/cornell/kfs/kew/config/cu-spring-kew.xml
This is ready for initial review, but I would like to do a little more local testing before it gets merged.
=> KFSPTS-29211 Fix ad hoc routed docs going to EXCEPTION

src/main/resources/edu/cornell/kfs/module/ar/cu-spring-ar.xml
This PR updates the spring configuration  for CGB as requested in the Jira.  Please be sure to read the parent user story to see if the reviewer understands the Jira requested changes the same way as I do.
=> KFSPTS-29081 update cgb spring configuration

src/main/java/edu/cornell/kfs/module/purap/document/IWantDocument.java, src/main/resources/edu/cornell/kfs/module/purap/cu-ojb-purap.xml, src/main/resources/edu/cornell/kfs/module/purap/document/datadictionary/IWantDocument.xml, src/main/webapp/WEB-INF/tags/module/purap/iWantDocumentOverview.tag, src/main/webapp/scripts/module/purap/iWantDoc.js
This reverts commit d000f53f834edec08e6d91014cbf21c2ffd77067.
=> Revert "KFSPTS-30712 Add processorNetId Field to IWNT Document (#1546)"

pom.xml
There are PRs for this in cu-kfs, cornell_customizations, cynergy-server-customizations and cynergy-standalone. Please make sure all four are good to go before merging.
I also had a quick question about the scope of the changes. I recently noticed that the cu-kfs WAR is using two different versions of the Log4J dependencies. I currently have the 01/29/2023 financials upgrade set up to fix that, but I'm wondering if it would make sense to bundle that fix with this dependency-updating PR. Please let me know your thoughts on that. (If we do decide to bundle in the Log4J version fix, it might make sense to update the Cynergy-side Log4J versions as well.)
=> KFSPTS-31070 Upgrade to latest Spring 5.3.x version

pom.xml
There are PRs for this in cu-kfs, cornell_customizations, cynergy-server-customizations, cynergy-standalone, cynergy-adf-core-lib and cynergy_adf_core. Please make sure all of them are good to go before merging.
This PR upgrades KFS to a newer CXF version (along with one of its other related libraries), to address a Dependabot alert.
=> KFSPTS-31256 Upgrade CXF version

src/main/java/edu/cornell/kfs/kim/KimFeed.java
We've received a request to stop treating the "Affiliate" affiliation type as an employee-ID-supporting one. This PR updates the KIM Feed Batch Job to tread "Affiliate" affiliations the same as the other non-employee affiliation types (Student, Alumni, etc.).
Note that there's no associated SQL PR for this. I would suggest using the KIM Feed process to correct the existing KFS data once these changes are in place. We can ask Chris Grippin to generate appropriate KIM Feed delta rows for "Affiliate" users as needed.
=> KFSPTS-31229 Remove empl info from Affiliate entries

pom.xml
There are PRs for this change in cu-kfs, cornell_customizations, cynergy-server-customizations and cynergy-standalone. Please make sure all four are good to go before merging.
=> KFSPTS-31580 Upgrade to Spring 5.3.34

src/main/java/edu/cornell/kfs/ksr/KSRConstants.java, src/main/java/edu/cornell/kfs/ksr/businessobject/SecurityRequestRole.java, src/main/java/edu/cornell/kfs/ksr/service/impl/SecurityRequestDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/ksr/util/KSRUtil.java, src/main/resources/edu/cornell/kfs/ksr/cu-spring-ksr.xml, src/main/webapp/WEB-INF/tags/ksr/securityRequestRoleQualifications.tag
This reverts commit 1cc618a0e9e45a37a78d020aefe39792e2f6346c.
A spelling error was discovered, reverting so it can be fixed.
=> Revert "KFSPTS-31685 update KSR to prevent edit of qualifiers in KSR by parameter (#1612)"

src/main/java/org/kuali/kfs/datadictionary/legacy/MaintenanceDocumentDictionaryService.java
This PR fixes an Award-doc-related issue by backporting the FINP-10787 code changes. It only involved overlaying 1 file and adding a few new lines to it.
NOTE: The related user story originally requested backporting FINP-10710, but upon further analysis, it was determined that FINP-10787 should be backported instead.
=> KFSPTS-32353 Backport FINP-10787 Award doc fix

src/main/java/edu/cornell/kfs/module/purap/document/IWantDocument.java, src/main/java/edu/cornell/kfs/module/purap/document/service/IWantDocumentService.java, src/main/java/edu/cornell/kfs/module/purap/document/service/impl/IWantDocumentServiceImpl.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/IWantDocumentAction.java, src/main/java/edu/cornell/kfs/module/purap/document/web/struts/IWantDocumentForm.java, src/main/webapp/WEB-INF/tags/module/purap/iWantDvPayments.tag, src/main/webapp/jsp/module/purap/IWant.jsp
This PR adds a new tab to the IWNT doc that shows a limited set of payment information from the associated DV document (if any).
=> KFSPTS-32805 Show DV payment info on IWNT doc

src/main/java/edu/cornell/kfs/pdp/CUPdpParameterConstants.java, src/main/java/edu/cornell/kfs/pdp/batch/service/impl/CuExtractPaymentServiceImpl.java
This PR has dependent SQL in nonprod-sql PR: https://github.com/CU-CommunityApps/nonprod-sql/pull/1463
Make sure both are acceptable and merged together.
=> KFSPTS-32809: Print Boss only processing ISO 20022 check file format. Removing KFS proprietary format for checks.

src/main/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateSupplierXmlServiceImpl.java, src/test/java/edu/cornell/kfs/module/purap/batch/service/impl/JaggaerGenerateSupplierXmlServiceImplTest.java
This reverts commit 11077502d38f9b4a4107824a31bacc37812985d3.
=> Revert "KFSPTS-34600: Convert Jaggaer joda DateTimeFormatter to java time DateTimeFormatter. (#1727)"

src/main/resources/edu/cornell/kfs/module/ld/cu-spring-ld.xml
This backports https://github.com/KualiCo/financials/commit/4dc73dd78e017301dce0695849a251edd60471d5 which is a small part of FINP-10395
=> KFSPTS-34828 partial back port of FINP-10395 to fix opening general ledger from salary expense transfer document

src/main/java/edu/cornell/kfs/concur/ConcurParameterConstants.java, src/main/java/edu/cornell/kfs/concur/batch/service/ConcurBatchUtilityService.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurBatchUtilityServiceImpl.java, src/main/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceImpl.java, src/test/java/edu/cornell/kfs/concur/batch/service/impl/ConcurExpenseV3ServiceUpdateReportStatusTest.java, src/test/java/edu/cornell/kfs/concur/util/MockConcurUtils.java
Please note there is a related PR in non-prod SQL
=> KFSPTS-34645 disable adding accounting detail messages to concur expense reports during validation

src/main/java/edu/cornell/kfs/sys/CUKFSParameterKeyConstants.java
This code PR has a dependent nonprod-sql repository PR that must be merged at the same time:
https://github.com/CU-CommunityApps/nonprod-sql/pull/1574
=> KFSPTS-33845: Delete parameter NON_REQUEUABLE_DOCUMENT_TYPES
